src/DotVVM.Framework/Controls/HtmlGenericControl.cs
I think this type of text shouldn't be in public source files nor in inline documentation.
=> Remove easter egg

src/DotVVM.Framework/Configuration/DefaultDataProtectionProvider.cs, src/DotVVM.Framework/DotVVM.Framework.csproj, src/DotVVM.Framework/Hosting/OwinExtensions.cs
I'm creating a self-host web application with Owin but without ASP MVC nor .Net Core.
For some reason unknown to me app.GetDataProtectionProvider() returns NULL and I'm getting a NullReferenceException in DotVVM.Framework.Security.DefaultCsrfProtector.GetOrCreateSessionId when there is a request.
I propose a new class DefaultDataProtectionProvider that returns the appBuilder.CreateDataProtector which returns something usable when the request arrives to DefaultCsrfProtector.
=> If DataProtectionProvider comes as null from owin create a new one

src/DotVVM.Framework/ViewModel/Serialization/ViewModelMapperHelper.cs, src/DotVVM.Framework/ViewModel/Serialization/ViewModelPropertyMap.cs, src/DotVVM.Framework/ViewModel/Serialization/ViewModelSerializationMap.cs, src/DotVVM.Framework/ViewModel/Serialization/ViewModelSerializationMapper.cs, src/DotVVM.Samples.Common/DotvvmStartup.cs, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/Serialization/Serialization.cs
Bind, Protect, Ignore, client extenders and JsonConverter are supported
Short sample:
```C#
config.GetSerializationMapper()
.Map(typeof(ViewModel1), map =>
{
map.Property(nameof(ViewModel1.Property)).Bind(Direction.ServerToClient);
map.Property(nameof(ViewModel1.Property2)).Protect(ProtectMode.EncryptData);
map.Property(nameof(ViewModel1.Property2)).AddClientExtender(new ClientExtenderInfo { Name = "nnn", Parameter = ""});
map.Property(nameof(ViewModel1.IgnoredProperty)).Ignore();
})
.Map(typeof(AnotherViewModel), map =>
{
map.Property(nameof(AnotherViewModel.Prop)).Ignore();
});
```
=> Added API to configure serializer from code.

src/DotVVM.Framework.Tests.Common/Runtime/HtmlWriterTests.cs, src/DotVVM.Framework/Controls/HtmlWriter.cs, src/DotVVM.Framework/Controls/KnockoutBindingGroup.cs
Should resolve #321, but I have basically removed one [check](https://github.com/riganti/dotvvm/compare/empty-binding-groups?expand=1#diff-74cad2da3bf59959ab8d2007e5e1d038L135), do you think it's OK? Why was there the check?
=> Removed a check for empty binding group.

src/DotVVM.Framework/Routing/DotvvmRouteTable.cs, src/DotVVM.Framework/Routing/RouteTableGroup.cs
Route groups can be added to a RouteTable, described in https://github.com/riganti/dotvvm/issues/224. Group has its prefixes for route name, url and virtual path. The group can be retrieved and works as a RouteTable.
=> Added route groups

src/DotVVM.Framework/DependencyInjection/DotVVMServiceCollectionExtensions.cs, src/DotVVM.Framework/Hosting/DefaultStopwatch.cs, src/DotVVM.Framework/Hosting/DotvvmPresenter.cs, src/DotVVM.Framework/Hosting/DotvvmRequestContext.cs, src/DotVVM.Framework/Hosting/IDotvvmRequestContext.cs, src/DotVVM.Framework/Hosting/IStopwatch.cs, src/DotVVM.Framework/Hosting/RequestTracingConstants.cs, src/DotVVM.Framework/Testing/TestDotvvmRequestContext.cs
Added gathering of timestamps during the exectuion of the request described in https://github.com/riganti/dotvvm/issues/369. It uses the IStopwatch interface to register a System.Diagnostics.Stopwatch singleton object.
=> Gather timestamps during the execution of the request

src/DotVVM.Framework/Controls/Button.cs, src/DotVVM.Framework/Controls/LinkButton.cs, src/DotVVM.Framework/Controls/MultiSelectHtmlControlBase.cs, src/DotVVM.Framework/Controls/SelectHtmlControlBase.cs, src/DotVVM.Framework/Controls/SelectHtmlControlHelpers.cs, src/DotVVM.Framework/Controls/TextBox.cs, src/DotVVM.Samples.ApplicationInsingts.Owin/ApplicationInsights.config, src/DotVVM.Samples.Common/DotVVM.Samples.Common.csproj, src/DotVVM.Samples.Common/ViewModels/ControlSamples/Button/ButtonOnclickViewModel.cs, src/DotVVM.Samples.Common/Views/ControlSamples/Button/ButtonOnclick.dothtml, src/DotVVM.Samples.Common/Views/ControlSamples/LinkButton/LinkButtonOnclick.dothtml, src/DotVVM.Samples.Tests/Control/ButtonTests.cs, src/DotVVM.Samples.Tests/Control/LinkButtonTests.cs, src/DotVVM.Samples.Tests/SamplesRouteUrls.cs
- Changed the order of rendering `onclick` attributes in `Button`, `LinkButton` and added tests cases for that. 
- Also changed the order with `onchanged` attributes in `TextBox`, `SelectHtmlControlBase` and `MultiSelectHtmlControlBase`. 
- There is also `onclick` attribute in `CheckableControlBase` but the order is correct in that control.
- Issue https://github.com/riganti/dotvvm/issues/357
=> Onclick attribute rendering

src/DotVVM.Framework/Hosting/ErrorPages/ErrorFormatter.cs, src/DotVVM.Framework/Hosting/ErrorPages/ExceptionAdditionalInfo.cs, src/DotVVM.Framework/Hosting/ErrorPages/ExceptionSectionFormatter.cs, src/DotVVM.Framework/Runtime/Commands/CandidateBindings.cs, src/DotVVM.Framework/Runtime/Commands/EventValidator.cs, src/DotVVM.Framework/Runtime/Commands/InvalidCommandInvocationException.cs
Added properties with information about commands on the page to exception thrown when invoking invalid command. Properties contain key which describes the group of bindings and command bindings that did not match path, binding id or validation path with information why the validation failed.
Problem is described in https://github.com/riganti/dotvvm/issues/315.
=> Better exception information on invalid command invocation

src/DotVVM.Samples.Common/Controls/DerivedControl.cs, src/DotVVM.Samples.Common/Controls/ServerSideStylesControl.cs, src/DotVVM.Samples.Common/DotVVM.Samples.Common.csproj, src/DotVVM.Samples.Common/DotvvmStartup.cs, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/ServerSideStyles/ServerSideStylesViewModel.cs, src/DotVVM.Samples.Common/Views/FeatureSamples/ServerSideStyles/ServerSideStyles.dothtml, src/DotVVM.Samples.Common/Views/FeatureSamples/ServerSideStyles/ServerSideStyles_DotvvmProperties.dothtml, src/DotVVM.Samples.Tests/Feature/ServerSideStylesTests.cs, src/DotVVM.Samples.Tests/SamplesRouteUrls.cs
Added tests for server-side styles:
- I used `ServerSideStylesControl` and `DerivedControl` which are Code-only controls so the styles do not disrupt other controls
- I used `customTagName` for testing HTML elemets
- Issue https://github.com/riganti/dotvvm/issues/399
=> Tests for server-side styles

src/DotVVM.Framework/Binding/CustomDefaultProperty.cs, src/DotVVM.Framework/Binding/DotvvmPropertyWithFallback.cs, src/DotVVM.Framework/Controls/ButtonBase.cs, src/DotVVM.Framework/Controls/CheckableControlBase.cs, src/DotVVM.Framework/Controls/DataPager.cs, src/DotVVM.Framework/Controls/FormControls.cs, src/DotVVM.Framework/Controls/SelectorBase.cs, src/DotVVM.Framework/Controls/TextBox.cs, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/FormControlsEnabled/FormControlsEnabled.cs, src/DotVVM.Samples.Common/Views/FeatureSamples/FormControlsEnabled/FormControlsEnabled.dothtml, src/DotVVM.Samples.Tests/Feature/FormControlsEnabledTests.cs, src/DotVVM.Samples.Tests/SamplesRouteUrls.cs
_proposed in #296_
Adds a FormControls.Enabled property to all HTML elements which disables controls inside that are not explicitly enabled.
- Button (ButtonBase)
- CheckBox (CheckableControlBase)
- ComboBox (SelectorBase)
- DataPager
- LinkButton (ButtonBase)
- ListBox (SelectorBase)
- RadioButton (CheckableControlBase)
- TextBox
- Button
- CheckBox
- DataPager
- RadioButton
- TextBoxGroup
- Button
- Calendar
- CheckBox
- CheckBoxList
- ColorPicker
- ComboBox
- DataPager
- DateTimePicker
- DateTimeRangerPicker
- DropDownList
- MultiSelect
- NumericUpDown
- RadioButton
- RadioButtonList
- RangeCalendar
- RangeSlider
- Rating
- Slider
- TextBox
ListView (Business pack) does not have an Enabled property
DateTimePicker (Bootstrap) does not have an Enabled property
DropDownButton (Bootstrap) …
=> Feature: FormControls.Enabled

.editorconfig
Updated .editorconfig with formatting settings that are supported in the new version of Visual Studio. I think that these settings reflect the current style best, but there is no research behind it :) It's mostly a default, except:
* csharp_new_line_before_open_brace - the expressions don't have a new line before open brace
* csharp_indent_labels = no_change - I think this was the default when I have used it, but it does not matter as label is IMO used only once :P
I have also added options to trim trailing whitespace and an option to insert the final newline.
=> Updated .editorconfig with formatting settings

src/DotVVM.Framework/Controls/RouteLinkHelpers.cs, src/DotVVM.Framework/Hosting/DotvvmRequestContextExtensions.cs, src/DotVVM.Framework/Resources/Scripts/DotVVM.d.ts, src/DotVVM.Framework/Resources/Scripts/DotVVM.ts, src/DotVVM.Framework/Routing/UrlHelper.cs, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/Redirect/RedirectViewModel.cs, src/DotVVM.Samples.Common/Views/ControlSamples/Repeater/RouteLinkQuery.dothtml, src/DotVVM.Samples.Common/Views/FeatureSamples/Redirect/Redirect.dothtml, src/DotVVM.Samples.Tests/Control/RepeaterTests.cs, src/DotVVM.Samples.Tests/Feature/RedirectTests.cs, src/DotVVM.Samples.Tests/SamplesRouteUrls.cs
Added option to specify query string parameters in `RedirectToRoute` method.
Added UI test for this feature.
Issue https://github.com/riganti/dotvvm/issues/405
=> Query string parameters to RedirectToRoute, Query-* property group in RouteLink

src/DotVVM.Framework/Configuration/DotvvmMarkupConfiguration.cs
MVC is able to translate virtual path within meta tag content attribute so I added this `HtmlTagAttributePair` to the `HtmlAttributeTransforms` dictionary in `DotvvmMarkupConfiguration`.
Issue https://github.com/riganti/dotvvm/issues/458
=> Registered meta tag content attribute so it can translate virtual paths

src/DotVVM.Framework.Hosting.Owin/Hosting/Middlewares/DotvvmMiddleware.cs, src/DotVVM.Framework.Tests.Owin/DefaultViewModelSerializerTests.cs, src/DotVVM.Framework/Diagnostics/DiagnosticsRequestTracer.cs, src/DotVVM.Framework/Hosting/IHttpRequest.cs, src/DotVVM.Framework/Hosting/Middlewares/DotvvmMiddlewareBase.cs, src/DotVVM.Framework/Hosting/Middlewares/DotvvmRoutingMiddleware.cs, src/DotVVM.Tracing.MiniProfiler.Owin/MiniProfilerActionFilter.cs
Made `IHttpRequest` properties `Path`, `Sheme` and `QueryString` obsolete.
Replaced `Path` with `Url.AbsolutePath`, `Scheme` with `Url.Scheme` and `QueryString` with `Url.Query`. I left the property `PathBase` because i did not know what to replace it with.
issue https://github.com/riganti/dotvvm/issues/432
=> Removing some IHttpRequest properties

src/DotVVM.Framework.Tests.Common/Binding/IntegrityCheckTests.cs, src/DotVVM.Framework/ResourceManagement/LinkResourceBase.cs
Seems that auto-computing the integrity hash, as is done now, wouldn't necessarily be the right thing, given that it would only ensure that the resource hasn't changed while the instance of Dotvvm is running.
If you restart your instance, and the resource has become malicious, then it will just hash the malicious resource and write that as the integrity SRI.
Most good CDNs provide the SRI, and it should never change. So if you have it, you should be able to use it.
This patch, as is, doesn't remove the auto-computing, it only adds the ability to add a manual hash, just to be conservative for now, if there was another use case I hadn't considered (development?).
But you may wish to remove the auto-compute entirely. Then you could remove the boolean VerifyResourceIntegrity property, as …
=> Allow manual integrity hash and add tests

src/DotVVM.Core/Controls/GridViewDataSet.cs
Fixes deadlocks that occur when GridView synchronously calls asynchronous code that accesses a database from OnLoad/OnPreRender.
How about we add async version of OnInit, OnLoad, etc.?
=> Temporarily fix GridViewDataSet sync deadlocks.

src/DotVVM.Framework.Hosting.AspNetCore/ApplicationBuilderExtensions.cs, src/DotVVM.Framework.Hosting.Owin/AppBuilderExtensions.cs, src/DotVVM.Framework/Hosting/DotvvmRequestContextExtensions.cs, src/DotVVM.Framework/Hosting/Middlewares/DotvvmFileUploadMiddleware.cs, src/DotVVM.Framework/Hosting/Middlewares/DotvvmReturnedFileMiddleware.cs
It has to be here to preserve backwards compatibility with DotVVM 1.x
Note that you can use https://github.com/riganti/dotvvm/pull/500/files?w=1 for diff without changed whitespace - I had to unindent the class to preserve sane formatting.
=> DotvvmRequestContextExtension are moved to global namespace.

src/DotVVM.Framework/Controls/ClaimView.cs, src/DotVVM.Framework/Controls/RoleView.cs
When HideForAnonymousUsers was set to false and user was anonymous (not authenticated) the User.IsInRole does not work as you may expect and throws exception "System.SystemException: The trust relationship between this workstation and the primary domain failed.". Solution I found to solve this issue was taken from SO: https://stackoverflow.com/a/22767760
=> Fixed RoleView.cs for anonymous users

src/DotVVM.Framework/Compilation/Styles/CompileTimeStyleBase.cs, src/DotVVM.Framework/Compilation/Styles/StyleBuilder.cs, src/DotVVM.Samples.Common/DotvvmStartup.cs, src/DotVVM.Samples.Common/Views/FeatureSamples/ServerSideStyles/ServerSideStyles.dothtml, src/DotVVM.Samples.Common/Views/FeatureSamples/ServerSideStyles/ServerSideStyles_MatchingViewModel.dothtml
This PR improves server-side style registration with multiple override options:
* `Append` - this options actually append value in a attribute/property
* `Overwrite` - behavior is the same as `append == true` before this PR (overwrites attribute value)
* `Ignore` - behavior is the same as `append == false` before this PR (ignores attribute with value)
The PR resolves #487
=> Added multiple override options to server-side style

src/DotVVM.Framework/Controls/HtmlGenericControl.cs, src/DotVVM.Framework/Controls/Infrastructure/BodyResourceLinks.cs, src/DotVVM.Framework/Controls/Infrastructure/HeadResourceLinks.cs, src/DotVVM.Framework/ResourceManagement/ResourceManager.cs, src/DotVVM.Framework/Runtime/DefaultOutputRenderer.cs, src/DotVVM.Samples.Common/Views/FeatureSamples/Resources/OnlineNonameResourceLoad.dothtml
You can now explicitly say "I want to have the resources rendered here" using <dot:HeadResourceLinks /> or <dot:BodyResourceLinks />. The resources are rendered on the first place where this control occurs.
HtmlGenericControl renders this control implicitly if the TagName is body or head (I have moved the logic from DefaultOutputRenderer, I think that it should improve performance)
ResourceManager now knows if the resources have been already rendered and it will throw an exception when a new one is added. This is potentially a runtime breaking change, but it should only throw on code that is actually incorrect.
=>  Redesigned resource link controls

src/DotVVM.Framework.Tests.Common/Runtime/ControlTree/DefaultControlTreeResolverTests.cs, src/DotVVM.Framework/Compilation/ControlTree/ControlTreeResolverBase.cs
InnerElement properties are not limited to elements only - now, it can also contain literals, ...
When the default property is empty or whitespace it's not assigned (so it's null). However, when the name is specified, the whitespace content is included (when valid in this context).
The content is filtered by the specified collection type (e.g. GridViewColumn), error is reported only when the element is not asignable to the specified type and when it's not empty. So it will not fail when GridView.Columns contains whitespace or comment, but will fail when you'd specify a dotvvm control or text content.
=> Inner element properties tweaks

src/DotVVM.Framework/Hosting/Middlewares/DotvvmReturnedFileMiddleware.cs
This fixes an issue with file names containing spaces in Firefox.
For example if file name is something like "aaa bbb ccc.txt", Firefox (without the double quotes) would try saving it as just "aaa".
=> Added double quotes around file name in Content-Disposition header.

src/DotVVM.Framework/DotVVM.Framework.csproj, src/DotVVM.Framework/Hosting/Middlewares/DotvvmReturnedFileMiddleware.cs
Added encoding of filename for Content-Disposition header.
Encoding is handled in `ContentDispositionHeaderValue` type which is in `System.Net.Http` assembly for .net framework or `Microsoft.Net.Http.Headers` package for .net standard. 
It is okay to add these dependencies? @exyi 
Relates to #589
=> Added ContentDisposition header encoding using *.Net.Http packages

src/DotVVM.Framework/Controls/DotvvmControl.cs, src/DotVVM.Framework/Controls/UpdateProgress.cs, src/DotVVM.Samples.Common/Views/ControlSamples/IncludeInPageProperty/IncludeInPage.dothtml
Resource binding inside `IncludeInPage` throws `NullReferenceException` in `Render` method.
When the binding is evaluated to false we shouldn't render the control at all.
=> Fixed IncludeInPage with resource binding

src/DotVVM.Framework/ViewModel/Validation/ViewModelPropertyValidationRule.cs, src/DotVVM.Framework/ViewModel/Validation/ViewModelValidationRuleTranslator.cs
This pull request adds ability to use DisplayAttribute to localize property name in client side validation.
`[Display(Name = nameof(Resources.Fields.City), ResourceType = typeof(Resources.Fields))]
[Required(ErrorMessageResourceName = nameof(Resources.ValidationMessages.Required), ErrorMessageResourceType = typeof(Resources.ValidationMessages))]
public string City { get; set; }`
=> use DisplayAttribute for PropertyName in ViewModelValidationRuleTranslator

src/DotVVM.Compiler/Resolving/DotvvmServiceConfiguratorResolver.cs
Current implementation does not allow OWIN based DotVVM not to have implementation of `IDotVVMServiceConfigurator`. This should fix unexpected compiler errors in such cases.
=> Fix locating service configurator

src/DotVVM.Framework/Routing/DotvvmRouteTable.cs
Fixed Route registration in RouteTableGroups where empty Route url could not be registered like this: 
```
config.RouteTable.AddGroup("Dashboard", "dashboard", "Views/Dashboard/", opt =>
{
opt.Add("default", "", "Default.dothtml");
opt.Add("Files", "files", "FileOption.dothtml");
opt.Add("Projects", "projects", "ProjectsList.dothtml");
});
```
=> Fixed empty url registration for Routes in RouteTableGroups

src/DotVVM.Framework.Tests.Common/Binding/JavascriptCompilationTests.cs, src/DotVVM.Framework.Tests.Common/Binding/StaticCommandCompilationTests.cs, src/DotVVM.Framework/Binding/BindingCollectionInfo.cs, src/DotVVM.Framework/Binding/BindingHelper.cs, src/DotVVM.Framework/Compilation/ControlTree/BindingExtensionParameter.cs, src/DotVVM.Framework/Compilation/Javascript/JavascriptTranslator.cs, src/DotVVM.Framework/Controls/DataItemContainer.cs, src/DotVVM.Framework/Controls/GridView.cs, src/DotVVM.Framework/Controls/Repeater.cs, src/DotVVM.Framework/Resources/Scripts/DotVVM.js, src/DotVVM.Framework/Resources/Scripts/DotVVM.ts, src/DotVVM.Framework/tsconfig.json, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/BindingContexts/CollectionContextViewModel.cs, src/DotVVM.Samples.Common/Views/FeatureSamples/BindingContexts/CollectionContext.dothtml, src/DotVVM.Samples.Tests/Feature/BindingContextsTests.cs
Removed JavascriptTranslator.CurrentIndex symbolic parameter, it's usage
is replaced with `$context.$index` (as we'd do with any other
non-special property of the knockout context). This fixes a bunch of
issues with data context shifting of the context.
Repeater and GridView in server rendering mode use dotvvm-SSR-foreach
and dotvvm-SSR-item binding handlers that:
1. Automatically assign `$index` in each template
2. Remove the DataSource expression from every item of the Repeated
Method BindingHelper.SetDataContextForItem was removed since it can't be
implemented without the CurrentIndexParameter in the ParametrizedCode.
This commit should fix issues with $index in server rendering, $index in
staticCommand and $index in somewhat deeply nested data contexts.
=> Redesigned how _index works

src/DotVVM.Framework.Tests.Common/Runtime/DefaultViewCompilerTests.cs, src/DotVVM.Framework/Compilation/DefaultViewCompilerCodeEmitter.cs, src/DotVVM.Framework/Compilation/ViewCompilingVisitor.cs
As pointed out in Gitter by @kamm85, the dependency injection into controls did not work with markup montrols, this change should fix it.
=> Fixed dependency injection into markup controls

src/DotVVM.Framework.Tests.Common/ViewModel/ViewModelValidatorTests.cs, src/DotVVM.Framework/ViewModel/Validation/ValidationErrorFactory.cs, src/DotVVM.Framework/ViewModel/Validation/ViewModelValidator.cs
This new overload doesn't require `DotvvmConfiguration` object or object which implements `IDotvvmViewModel`.
I would like to also add `IServiceProvider` to `ValidationContext` to support custom validation which requires additional services. How can I resolve `IServiceProvider`, that is properly scoped, in `ViewModelValidator` ? @exyi
=> Added overload to CreateValidationResult in ValidationErrorFactory

src/DotVVM.Framework/Compilation/ControlTree/DefaultControlResolver.cs
Call `AppDomain.CurrentDomain.GetAssemblies()` only returns currently loaded assemblies and thus not all assemblies with DotvvmControl could be loaded and so not all static constructors were invoked and registered.
Should DotVVM invoke static constructors on all controls in assemblies using assembly scanning? What if all assemblies with `DotvvmControl` would be registered in a list and only those would be scanned? I know it would requrie user to call a registration/extension method at `DotvvmStartup`, but it seems better approad to e.
=> Fixed assembly loading bug for net framework

src/DotVVM.Framework.Tests.Common/Binding/BindingCacheTests.cs, src/DotVVM.Framework.Tests.Common/Binding/BindingCompilationTests.cs, src/DotVVM.Framework.Tests.Common/Binding/CommandResolverTests.cs, src/DotVVM.Framework.Tests.Common/Binding/JavascriptCompilationTests.cs, src/DotVVM.Framework.Tests.Common/DotvvmTestHelper.cs, src/DotVVM.Framework.Tests.Common/Routing/DotvvmRouteTests.cs, src/DotVVM.Framework.Tests.Common/Runtime/DotvvmControlTestBase.cs, src/DotVVM.Framework/Binding/BindingCompilationService.cs, src/DotVVM.Framework/Binding/BindingProperties.cs, src/DotVVM.Framework/Binding/DotvvmBindingCacheHelper.cs, src/DotVVM.Framework/Binding/Expressions/BindingExpression.cs, src/DotVVM.Framework/Binding/Expressions/IBinding.cs, src/DotVVM.Framework/Binding/Expressions/ValueBindingExpression.cs, src/DotVVM.Framework/Testing/SimpleDictionaryCacheAdapter.cs
I have added an API to BindingCompilationService for easy creation of binding using the new `IDotvvmCacheAdapter`.
```C#
service.Cache.CachedCreate(
"Identifier of the operation",
//   ^ unique identifier to prevent collisions
new [] { dataContext, otherParameter },
//           ^ Array of keys that are only used to distinguish the cache entries
() => new ValueBindingExpression(...))
//        ^ the actual logic that create the binding in case it's not in the cache
```
And there is also a second overload that takes the binding properties instead of a factory function:
```C#
service.Cache.CachedCreate(
"Identifier of the operation",
new [] { dataContext, otherParameter },
new object[] { dataContext, new OriginalStringBindingProperty(...), ... })
```
I have also changed the …
=> Added an API for caching the created binding

src/DotVVM.CommandLine/DotVVM.CommandLine.csproj
I have upgraded `DotVVM.CommandLine` to .NET Core 2.1 and added a few property groups to support installation as a global tool.
=> DotVVM CLI supports installation as a global tool

src/DotVVM.Core/Controls/GridViewDataSet.cs
We'll need to wait until .NET Core 3.0 is released to be able to make `LoadFromQueryableAsync` method (as explained in #670) since `ToListAsync` and `CountAsync` are declared in EF Core assemblies and we didn't want DotVVM to depend on that.
However, to allow users making their own implementation of `LoadFromQueryableAsync` as an extension method, I have changed several methods on `GridViewDataSet` to be public. 
Making an extension method for `LoadFromQueryableAsync` can now be done like this:
```
public static async Task LoadFromQueryableAsync(this GridViewDataSet<T> dataSet, IQueryable<T> source)
{
source = dataSet.ApplyFilteringToQueryable(source);
dataSet.Items = await dataSet.ApplyOptionsToQueryable(source).ToListAsync();
dataSet.PagingOptions.TotalItemsCount = await …
```
=> Easier creation of LoadFromQueryableAsync extension method

src/DotVVM.Framework.Hosting.AspNetCore/Hosting/Middlewares/DotvvmErrorPageMiddleware.cs, src/DotVVM.Framework/Hosting/DotvvmRequestContextExtensions.cs, src/DotVVM.Framework/Hosting/HttpRedirectService.cs
With .NET Core 3, it sometimes throws an exception when you use that.
So, even in places where we need to use a synchronous write, I have
simply changed that to WriteAsync().GetAwaiter().GetResult()
=> Removed usages of synchronous AspNetCore API

src/DotVVM.Framework.Tests.Common/DotVVM.Framework.Tests.Common.csproj, src/DotVVM.Framework.Tests.Common/Runtime/RuntimeErrorTests.cs, src/DotVVM.Framework.Tests.Common/Runtime/testoutputs/RuntimeErrorTests.CantFindDataContextSpace.txt, src/DotVVM.Framework.Tests.Common/Runtime/testoutputs/RuntimeErrorTests.DataContextStack_ToString.txt, src/DotVVM.Framework.Tests.Common/Runtime/testoutputs/RuntimeErrorTests.InitResolverFailure.txt, src/DotVVM.Framework.Tests.Common/Runtime/testoutputs/RuntimeErrorTests.NonExistentBindingProperty.txt, src/DotVVM.Framework.Tests.Common/Runtime/testoutputs/RuntimeErrorTests.PropertyResolverFailure.txt, src/DotVVM.Framework/Binding/BindingCompilationService.cs, src/DotVVM.Framework/Binding/BindingHelper.cs, src/DotVVM.Framework/Binding/BindingPropertyException.cs, src/DotVVM.Framework/Binding/Expressions/BindingExpression.cs, src/DotVVM.Framework/Compilation/ControlTree/DataContextStack.cs, src/DotVVM.Framework/Compilation/DotvvmCompilationException.cs, src/DotVVM.Framework/Compilation/NamespaceImport.cs, src/DotVVM.Framework/Hosting/ErrorPages/ErrorFormatter.cs
Improved error messages of unresolvable binding properties, failures to
find data context stack and error page when error occurs in a binding.
Also added tests for that using CheckTestOutput, I'm sending it as a PR maily to test that is works with our CI and that it works on Windows.
=> Improved error handling of binding errors

src/DotVVM.Framework/Hosting/DotvvmRequestContextExtensions.cs, src/DotVVM.Framework/Hosting/Middlewares/DotvvmReturnedFileMiddleware.cs, src/DotVVM.Framework/Storage/ReturnedFileMetadata.cs, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/ReturnedFile/ReturnedFileSampleViewModel.cs, src/DotVVM.Samples.Common/Views/FeatureSamples/ReturnedFile/ReturnedFileSample.dothtml, src/DotVVM.Samples.Tests/Feature/ReturnedFileTests.cs
One of the customers asked us to support different `Content-Disposition` headers - he needs `inline` instead of `attachment` which was hard-coded.
=> Returned files support changing the Content-Disposition header type

src/DotVVM.Framework/Storage/FileSystemUploadedFileStorage.cs
I found out, that in FileSystemUploadedFileStorage in DeleteOldFiles method is missing condition on maxCreatedDate. So I copied method code from FileSystemReturnedFileStorage.
=> Fixed missing condition on file age in DeleteOldFiles

src/DotVVM.Framework.Tests.Common/Parser/Dothtml/DothtmlTokenizerElementsTests.cs, src/DotVVM.Framework/Compilation/Parser/Dothtml/Tokenizer/DothtmlTokenizer.cs, src/DotVVM.Samples.Common/Views/FeatureSamples/Attribute/SpecialCharacters.dothtml
I need to use [AMP Bind component](https://amp.dev/documentation/components/amp-bind/). So I have to allow brackets in attribute name
`<button [text]="'This is a attribute with special characters ' + (show ? 'true': 'false')">Show</button>`
=> Allow brackets in attributes name

src/DotVVM.Framework/Controls/RouteLink.cs
Render the HTML disabled attribute, when the value of the `EnabledProperty` is false on the server.
Should some visual flashing issues on page load.
=> Render disabled attribute of RouteLink on server

src/DotVVM.Framework/Compilation/DefaultControlBuilderFactory.cs, src/DotVVM.Framework/Utils/ReflectionUtils.cs
I have made performance profiling on one of our projects. The result was that ReflectionUtils.FindType was used many times. So I have added caching for this function.
=> Added caching of resolved types in ReflectionUtils

src/DotVVM.Framework/Controls/FileUpload.cs, src/DotVVM.Framework/Controls/LinkButton.cs
LinkButton and File now are using javascript:; instead of # inside the href attribute when no link is set.
This change solves the problem of # being added to the URL
=> LinkButton and FileUpload empty href

src/DotVVM.Framework/Controls/Infrastructure/BodyResourceLinks.cs, src/DotVVM.Framework/Controls/Infrastructure/HeadResourceLinks.cs, src/DotVVM.Framework/ResourceManagement/ResourcesRenderer.cs
This is a little enhancement for easier debugging of resources that were included in a page. In debug mode, it writes a comment before every rendered resource (before the <script>, <link> or other tag).
It includes name of the resource, it's type and types of it's locations.
=> Rendering debug info about resources

src/DotVVM.Framework.Tests.Common/Binding/StaticCommandCompilationTests.cs, src/DotVVM.Framework/Compilation/Binding/StaticCommandBindingCompiler.cs, src/DotVVM.Framework/Resources/Scripts/DotVVM.ts
Static commands return a promise that was however never rejected (and thus completed) when an error occurs. This PR fixes the behavior, puts the reject function into every asynchronous invocation present in the static command.
It was needed to slightly change the signature of the `dotvvm.staticCommandPostback` function as it must signal the error with only one argument.
cc @Mylan719, this should fix your issue
=> Static commands now reject the result promise

src/DotVVM.Framework/Controls/DotvvmBindableObject.cs
This simple change disables evaluation of bindings returned by binding.
This was supported for very long time, but never had any practical usage
(as far as I know). With DotVVM 2.0 is became quite impractical to have
a binding that would return another binding, since it should also
declare it's return type. The binding also should be translatable to JS
and in that case it can not return another binding at all.
This "feature" now only creates quite unpredictable runtime decision
about the result type and I think we can safely remove it.
Another problem arises when you store something that is actually not
evaluatable - an IBinding instance that is not ICommandBinding nor
IStaticValueBinding. In that case, it simply hang in an infinite loop,
which is clearly a bug. With this change, it will …
=> Disabled nested and unsupported bindings in GetValue

src/DotVVM.Framework/Compilation/ControlTree/DataContextStack.cs, src/DotVVM.Framework/Compilation/HandleAsImmutableObjectInDotvvmPropertyAttribute.cs, src/DotVVM.Framework/Compilation/RoslynValueEmitter.cs
The attribute convinces the dotvvm compiler, that it can only emit a
reference to this object as it can be safely shared accros all controls
in the application lifetime.
One application is to set a custom object by s server-side style.
Note that the attribute name is so ugly on purpose. I don't really want it to be well discoverable, as would just complain that the serializer cannot handle immutable object even though they are marked by dotvvm (compiler) attribute...
cc @MichalTichy, this should solve your issue
=> Added HandleAsImmutableObject attribute

src/DotVVM.Framework/Controls/HtmlGenericControl.cs
Before this change, all errors caused by control.GetValue(Style-something)
were suppressed. With this change, only error caused by value bindings
that can also be evaluated in JS are suppressed.
=> Removed suppression of errors in Styles unless value binding is rendered

src/DotVVM.Framework.Tests.Common/Routing/RouteTableGroupTests.cs, src/DotVVM.Framework/Routing/DotvvmRouteTable.cs, src/DotVVM.Framework/Routing/RouteTableGroup.cs
Closes #661.
Please note that I had to change the signature of `DotvvmRouteTable.Add(string routeName, string url, Func<IServiceProvider, IDotvvmPresenter> presenterFactory, object defaultValues = null)` to `DotvvmRouteTable.Add(string routeName, string url, Func<IServiceProvider, IDotvvmPresenter> presenterFactory = null, object defaultValues = null)` (presenterFactory is optional now) to make it work.
=> Support presenter factories on route groups

src/DotVVM.Framework/ResourceManagement/ResourceUtils.cs
The dependency cycle detection was detecting even cycles that were inside the tree. That caused false positive detection.
=> Fixed dependency cycle detection.

src/DotVVM.Framework.Tests.Common/DotvvmTestHelper.cs, src/DotVVM.Framework.Tests.Common/Routing/LocalizablePresenterTests.cs, src/DotVVM.Framework/Hosting/LocalizablePresenter.cs, src/DotVVM.Framework/Routing/RouteBase.cs
Currently, when LocalizableProvider is given an invalid language code the exception is thrown instead of redirecting to default language.
This is happening because the dictionary with route parameters is treated as an anonymous object during copying of values. This behaviour results in copying of dictionary properties (Count, Keys, Values) instead of key value pairs.
This pull request addresses this issue by adding support for Dictionarystring, object> to method RouteBase. AddOrUpdateParameterCollection.
=> Fixed redirect on invalid language code

src/DotVVM.Framework/Controls/RouteLinkHelpers.cs, src/DotVVM.Samples.BasicSamples.AspNetCore/Web.config, src/DotVVM.Samples.Common/DotVVM.Samples.Common.csproj, src/DotVVM.Samples.Common/ViewModels/ControlSamples/RouteLink/RouteLinkQueryParametersViewModel.cs, src/DotVVM.Samples.Common/Views/ControlSamples/RouteLink/RouteLinkQueryParameters.dothtml, src/DotVVM.Samples.Tests/Control/RouteLinkTests.cs, src/DotVVM.Testing.Abstractions/SamplesRouteUrls.designer.cs
=> RouteLink control: query parameters not updating bugfix 

src/DotVVM.Framework.Hosting.AspNetCore/AspNetCoreLoggerWarningSink.cs, src/DotVVM.Framework.Hosting.AspNetCore/ServiceCollectionExtensions.cs, src/DotVVM.Framework/Controls/DotvvmBindableObjectHelper.cs, src/DotVVM.Framework/Controls/DotvvmControl.cs, src/DotVVM.Framework/Controls/HtmlWriter.cs, src/DotVVM.Framework/Controls/IHtmlWriter.cs, src/DotVVM.Framework/Controls/Infrastructure/BodyResourceLinks.cs, src/DotVVM.Framework/DependencyInjection/DotVVMServiceCollectionExtensions.cs, src/DotVVM.Framework/DotVVM.Framework.csproj, src/DotVVM.Framework/Hosting/DotvvmPresenter.cs, src/DotVVM.Framework/Runtime/DotvvmRuntimeWarning.cs, src/DotVVM.Framework/Runtime/IDotvvmWarningSink.cs, src/DotVVM.Framework/Runtime/RuntimeWarningCollector.cs, src/DotVVM.Framework/ViewModel/Serialization/DefaultViewModelSerializer.cs, src/DotVVM.Framework/ViewModel/Serialization/IViewModelSerializer.cs, src/DotVVM.Samples.BasicSamples.AspNetCore/Startup.cs, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/Warnings/SelfClosingTagsViewModel.cs, src/DotVVM.Samples.Common/Views/FeatureSamples/Warnings/SelfClosingTags.dothtml
RuntimeWarningCollector is a service, where a new warning will can be
added using the `Warn` method. Warning is an instance of
DotvvmRuntimeWarning, contains a message and may contain a reference to
an exception and a bindable object.
By default, warnings are collected in Debug mode. They are displayed in
browser JS console and forwarded to Asp.Net Core logging.
IDotvvmWarningSink is extensibility point for people that want to
collect these warnings on their own.
As a demo, HtmlWriter reports warnings when elements that should be
always self-closing contain some content, as the browser will interpret
the content as sibling.
related to #745, but does not close it since this PR introduces only the infrastructure.
Also note that I had to move rendering of resources in postback after …
=> API for runtime warnings

src/DotVVM.Framework.Tests.Common/Parser/Dothtml/DothtmlParserTests.cs, src/DotVVM.Framework/Compilation/Parser/Dothtml/Parser/DothtmlParser.cs, src/DotVVM.Framework/Compilation/Parser/Dothtml/Tokenizer/DothtmlTokenizer.cs, src/DotVVM.Framework/ViewModel/Serialization/IViewModelSerializer.cs, src/DotVVM.Samples.Common/Views/Default.dothtml
Binding can be now written without quotes in attributes:
```
MyProperty={value: OtherProperty}
```
The quotes are basically redundant in the syntax, as the binding is
already "quoted" by the curly braces. IMHO, it makes more sense to write
them without quotes as it's just noise. And React (JSX) also has them without
quotes :)
=> Allowed bindings in attributes without quotes

src/DotVVM.Framework/Binding/BindingHelper.cs
The method should return the type expected in this property, but used to look at the binding assigned into it. That can have a different type if it is assigned from a different property or created manually.
=> Fixed GetDataContextType(DotvvmProperty)

src/DotVVM.Framework.Tests.Common/Parser/Dothtml/VSExtensionContractTests.cs, src/DotVVM.Framework/Compilation/Parser/TokenBase.cs
After discussion with @Mylan719 about migrating the entire parser and resolver to pure functional programming using very nice concepts such as zippers (also knows as Roslyn Red-Greed tree) and performance of this thing, we decided we have different plans for the next year so I added back the setters :)
=> Made TokenBase mutable as the VS Extension needs that

src/DotVVM.Framework/Utils/FunctionalExtensions.cs
The problem was in GetValueOrDefault method which was only added to netstandard20.
With this change, it is present in both builds. It's just not an extension method
in netstandard21
=> Fixed binary incompatibility of netstandard2(0/1) build

src/DotVVM.Framework/Resources/Scripts/DotVVM.d.ts, src/DotVVM.Framework/Resources/Scripts/DotVVM.js, src/DotVVM.Framework/Resources/Scripts/DotVVM.ts, src/DotVVM.Samples.Common/DotVVM.Samples.Common.csproj, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/PostbackConcurrency/RedirectPostbackQueueMasterViewModel.cs, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/PostbackConcurrency/RedirectPostbackQueueViewModel.cs, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/PostbackConcurrency/StressTestViewModel.cs, src/DotVVM.Samples.Common/Views/FeatureSamples/PostbackConcurrency/RedirectPostbackQueue.dothtml, src/DotVVM.Samples.Common/Views/FeatureSamples/PostbackConcurrency/RedirectPostbackQueueSpa.dothtml, src/DotVVM.Samples.Common/Views/FeatureSamples/PostbackConcurrency/RedirectPostbackQueueSpaMaster.dotmaster, src/DotVVM.Samples.Common/Views/FeatureSamples/PostbackConcurrency/StressTest.dothtml, src/DotVVM.Samples.Tests/Feature/PostbackConcurrencyTests.cs, src/DotVVM.Testing.Abstractions/SamplesRouteUrls.designer.cs
This PR fixes two issues:
* When there are multiple postbacks in a concurrency queue, more of them started executing simultaneously
* When the server responds with a redirect response, the next postbacks from queue were started (during the load of the new page)
=> Fixed race condition in queued postbacks

src/DotVVM.Framework/ResourceManagement/ResourceManager.cs
~~Added two methods to ResourceManager (similar methods are already present)
public void AddRequiredInlineScript(string name, string code, params string[] dependentResourceNames)~~
~~public void AddRequiredInlineStylesheet(string name, string code, params string[] dependentResourceNames)~~
After consultation with @exyi We've decided that it would be better to make AddRequiredResourceCore public (and rename it to AddRequiredResource)
=> private AddRequiredResourceCore => public AddRequiredResource

src/DotVVM.Framework.Hosting.AspNetCore/ServiceCollectionExtensions.cs, src/DotVVM.Framework/Compilation/CompilationState.cs, src/DotVVM.Framework/Compilation/DotHtmlFileInfo.cs, src/DotVVM.Framework/Compilation/DotvvmViewCompilationService.cs, src/DotVVM.Framework/Compilation/IDotvvmViewCompilationService.cs
Added service that allows users to compile DotHTML on demand. This feature was extracted from DotVVM status page.
This is possibly first of two pull requests. U would like to added way how to compile every view during startup (using this service) just by changing DotVVM configuration.
=> Dotvvm view compilation service

src/DotVVM.Framework.Hosting.AspNetCore/ApplicationBuilderExtensions.cs, src/DotVVM.Framework.Hosting.Owin/AppBuilderExtensions.cs, src/DotVVM.Framework.Tests.Common/Runtime/config-tests/ConfigurationSerializationTests.AuxOptions.json, src/DotVVM.Framework.Tests.Common/Runtime/config-tests/ConfigurationSerializationTests.ExperimentalFeatures.json, src/DotVVM.Framework.Tests.Common/Runtime/config-tests/ConfigurationSerializationTests.Markup.json, src/DotVVM.Framework.Tests.Common/Runtime/config-tests/ConfigurationSerializationTests.RestAPI.json, src/DotVVM.Framework.Tests.Common/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json, src/DotVVM.Framework.Tests.Common/Runtime/config-tests/ConfigurationSerializationTests.SerializeEmptyConfig.json, src/DotVVM.Framework.Tests.Common/Runtime/config-tests/ConfigurationSerializationTests.SerializeResources.json, src/DotVVM.Framework.Tests.Common/Runtime/config-tests/ConfigurationSerializationTests.SerializeRoutes.json, src/DotVVM.Framework/Compilation/DotvvmViewCompilationServiceExtensions.cs, src/DotVVM.Framework/Compilation/ViewCompilationMode.cs, src/DotVVM.Framework/Configuration/DotvvmMarkupConfiguration.cs, src/DotVVM.Framework/Configuration/ViewCompilationConfiguration.cs, src/DotVVM.Framework/Controls/UpdateProgress.cs
This PR adds configuration for view compilation modes.
```
/// Gets or sets the mode under which the view compilation (pages, controls, ... ) is done.
configuration.Markup.ViewCompilation.Mode = ViewCompilationMode.AfterStartup;
/// Gets or sets the delay before view compilation will be done. This compilation delay can be set only in precompilation modes.
configuration.Markup.ViewCompilation.BackgroundCompilationDelay = TimeSpan.FromMinutes(1);
```
Compilation modes are:
- Lazy 
Current mode of compilation.
- DuringApplicationStart
Compilation will run during application startup. Application will start after compilation is done.
- AfterApplicationStart
Compilation will run after application startup.
=> Added configuration for view precompilation.

src/DotVVM.Framework/Utils/TaskUtils.cs
This PR implements a fix for `NullReferenceException` as described in #828.
Code was failing for all subclasses of `System.Threading.Task` that did not have the `Result` property. Resolves #828.
=> Fixed NullReferenceException on postback when Task is returned

src/DotVVM.Framework.Tests.Common/ResourceManagement/ResourceRepositoryTests.cs, src/DotVVM.Framework/ResourceManagement/ResourceUtils.cs
When adding a resource with a dependancy cycle not directly containing the resource, result is an endless loop.
```
<dependancy-k+n>  <-
V           <dependancy-k+1>
<resource being added> -> <dependancy-1> -> ... -> <dependancy-k> ^
```
the n-long cycle does not get detected and results in an endless loop
=> Resource registration takes literally forever.

src/DotVVM.Framework.Tests.Common/ViewModel/SerializerTests.cs, src/DotVVM.Framework/Hosting/ErrorPages/ErrorFormatter.cs, src/DotVVM.Framework/ViewModel/Serialization/EncryptedValuesReader.cs, src/DotVVM.Framework/ViewModel/Serialization/EncryptedValuesWriter.cs, src/DotVVM.Framework/ViewModel/Serialization/ViewModelJsonConverter.cs, src/DotVVM.Framework/ViewModel/Serialization/ViewModelSerializationMap.cs
This PR supports nesting `ProtectMode.None`, `ProtectMode.Signed` and `ProtectMode.Encrypted`. Whenever a property is affected by multiple `ProtectMode`s, the most strict one is used. Resolves #866, #854
=> Support nested ProtectAttribute

src/DotVVM.Framework/Controls/GridView.cs, src/DotVVM.Framework/Controls/GridViewCheckBoxColumn.cs, src/DotVVM.Samples.Common/ViewModels/ControlSamples/GridView/GridViewSortChangedViewModel.cs, src/DotVVM.Samples.Common/Views/ControlSamples/GridView/GridViewSortChanged.dothtml, src/DotVVM.Samples.Tests/Control/GridViewTests.cs, src/DotVVM.Testing.Abstractions/SamplesRouteUrls.designer.cs
This allows users to override the default sorting logic.
Also, GridView is not senzitive to the real value in DataSource, the
sort command is determined by the DataSource result type.
TODO: test
=> GridView.SortChange has precedence over default sorting

src/DotVVM.Compiler/Resolving/DotNetCliInfoResolver.cs, src/DotVVM.Samples.Common/CommonConfiguration.cs, src/DotVVM.Samples.Common/ViewModels/ControlSamples/FileUpload/FileUploadViewModel.cs
Both Windows and Linux accepts forward slashes in path which backslashes are only accepted on Windows.
It is thus easier to use forward slashes everywhere.
=> Use forward slashes for paths

src/DotVVM.Framework/Resources/Scripts/spa/navigation.ts, src/DotVVM.Framework/Resources/Scripts/spa/spa.ts, src/DotVVM.Framework/Runtime/DefaultDotvvmViewBuilder.cs, src/DotVVM.Samples.Common/ViewModels/ControlSamples/SpaContentPlaceHolder_HistoryApi/MultiSpaDefaultViewModel.cs, src/DotVVM.Samples.Common/ViewModels/ControlSamples/SpaContentPlaceHolder_HistoryApi/MultiSpaMasterViewModel.cs, src/DotVVM.Samples.Common/ViewModels/ControlSamples/SpaContentPlaceHolder_HistoryApi/Spa1PageAViewModel.cs, src/DotVVM.Samples.Common/ViewModels/ControlSamples/SpaContentPlaceHolder_HistoryApi/Spa1PageBViewModel.cs, src/DotVVM.Samples.Common/ViewModels/ControlSamples/SpaContentPlaceHolder_HistoryApi/Spa1Spa2ViewModel.cs, src/DotVVM.Samples.Common/ViewModels/ControlSamples/SpaContentPlaceHolder_HistoryApi/Spa2PageAViewModel.cs, src/DotVVM.Samples.Common/ViewModels/ControlSamples/SpaContentPlaceHolder_HistoryApi/Spa2PageBViewModel.cs, src/DotVVM.Samples.Common/Views/ControlSamples/SpaContentPlaceHolder_HistoryApi/MultiSpaDefault.dothtml, src/DotVVM.Samples.Common/Views/ControlSamples/SpaContentPlaceHolder_HistoryApi/MultiSpaMaster.dotmaster, src/DotVVM.Samples.Common/Views/ControlSamples/SpaContentPlaceHolder_HistoryApi/Spa1PageA.dothtml, src/DotVVM.Samples.Common/Views/ControlSamples/SpaContentPlaceHolder_HistoryApi/Spa1PageB.dothtml, src/DotVVM.Samples.Common/Views/ControlSamples/SpaContentPlaceHolder_HistoryApi/Spa1Spa2Page.dothtml, src/DotVVM.Samples.Common/Views/ControlSamples/SpaContentPlaceHolder_HistoryApi/Spa2PageA.dothtml, src/DotVVM.Samples.Common/Views/ControlSamples/SpaContentPlaceHolder_HistoryApi/Spa2PageB.dothtml, src/DotVVM.Samples.Tests/Control/SpaContentPlaceHolderTests.cs, src/DotVVM.Testing.Abstractions/SamplesRouteUrls.designer.cs
This PR lifts the restriction on having only a single `SpaContentPlaceHolder` per page. Resolves #719
=> Added support for multiple SpaContentPlaceHolders per page

src/DotVVM.Framework.Tests.Common/Binding/NullPropagationTests.cs, src/DotVVM.Framework.Tests.Common/Routing/RouteSerializationTests.cs, src/DotVVM.Framework.Tests.Common/Runtime/DotvvmCompilationExceptionSerializationTests.cs, src/DotVVM.Framework.Tests.Common/Runtime/ResourceManagerTests.cs, src/DotVVM.Framework.Tests.Common/ViewModel/SerializerTests.cs, src/DotVVM.Framework/Compilation/Javascript/Ast/JsLiteral.cs, src/DotVVM.Framework/Compilation/Javascript/JavascriptCompilationHelper.cs, src/DotVVM.Framework/Configuration/DefaultSerializerSettingsProvider.cs, src/DotVVM.Framework/Configuration/DotvvmConfigurationException.cs, src/DotVVM.Framework/Controls/DotvvmMarkupControl.cs, src/DotVVM.Framework/Controls/FileUpload.cs, src/DotVVM.Framework/Controls/KnockoutBindingGroup.cs, src/DotVVM.Framework/Controls/KnockoutHelper.cs, src/DotVVM.Framework/Controls/RouteLinkHelpers.cs, src/DotVVM.Framework/Controls/Validator.cs, src/DotVVM.Framework/Diagnostics/DiagnosticsInformationSender.cs, src/DotVVM.Framework/Diagnostics/DotvvmDiagnosticsConfiguration.cs, src/DotVVM.Framework/Hosting/DotvvmPresenter.cs, src/DotVVM.Framework/Hosting/Middlewares/DotvvmFileUploadMiddleware.cs, src/DotVVM.Framework/Runtime/DefaultOutputRenderer.cs, src/DotVVM.Framework/Storage/FileSystemReturnedFileStorage.cs, src/DotVVM.Framework/ViewModel/Serialization/DefaultViewModelSerializer.cs
Resolves #875.
The issue, however, still remains in generated REST API Bindings. This is tracked as a new issue #889 and will be addressed in future releases. In the meantime, users will be notified to not change these settings when working with generated bindings.
=> Fixed DotVVM.Framework to not rely on the default Newtonsoft.Json settings

src/DotVVM.Framework/Hosting/DefaultMarkupFileLoader.cs, src/DotVVM.Framework/Routing/DefaultRouteStrategy.cs
This PR fixes a bug found by @martindybal regarding the inability to load markups from different directories. 
Current implementation depends on the `ApplicationPhysicalPath`. More specifically, every markup needs to be within one of the subfolders as determined by the "root" directory `ApplicationPhysicalPath`. Changes within this PR lifts the restriction and makes it possible to load markups also from different directories.
**Note**: I added a simple implementation of a method that generates relative paths between source directories and target files. While this method is already implemented in .NET (https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getrelativepath?view=net-5.0), it is not supported by all frameworks usable with DotVVM. In future, once DotVVM drops support of …
=> Allow markups from different projects

src/DotVVM.Framework/Resources/Scripts/DotVVM.d.ts, src/DotVVM.Framework/Resources/Scripts/DotVVM.js, src/DotVVM.Framework/Resources/Scripts/DotVVM.ts, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/PostbackSpaNavigation/DenyPostbacksOnSpaNavigationService.cs, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/PostbackSpaNavigation/PageAViewModel.cs, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/PostbackSpaNavigation/PageBViewModel.cs, src/DotVVM.Samples.Common/Views/FeatureSamples/PostbackConcurrency/RedirectPostbackQueue.dothtml, src/DotVVM.Samples.Common/Views/FeatureSamples/PostbackConcurrency/RedirectPostbackQueueSpa.dothtml, src/DotVVM.Samples.Common/Views/FeatureSamples/PostbackSpaNavigation/PageA.dothtml, src/DotVVM.Samples.Common/Views/FeatureSamples/PostbackSpaNavigation/PageB.dothtml, src/DotVVM.Samples.Tests/Feature/PostbackConcurrencyTests.cs, src/DotVVM.Samples.Tests/Feature/PostbackSpaNavigationTests.cs, src/DotVVM.Samples.Tests/Feature/ReturnedFileTests.cs
We didn't realize that returning files is commonly done via redirects, and we were disabling postbacks on redirects. 
This PR returns to the previous behavior. 
Also, I've found an issue that we should fix in 3.x branch - long running static commands can modify a viewmodel of another page if SPA navigation is triggered during the time static command is running.
=> Postbacks were incorrectly disabled on redirects

src/DotVVM.Framework/Controls/DataPager.cs
Adds overridable properties for active page item and disabled page item to DataPager. This can be for easily overriding DataPager and using their own CSS classes.
=> Add overridable Active and Disabled css classes for DataPager

src/DotVVM.Framework.Tests.Common/ControlTests/SimpleControlTests.cs, src/DotVVM.Framework.Tests.Common/ControlTests/testoutputs/SimpleControlTests.RouteLink.html, src/DotVVM.Framework.Tests.Common/Routing/DotvvmRouteTests.cs, src/DotVVM.Framework/Controls/RouteLinkHelpers.cs, src/DotVVM.Framework/Resources/Scripts/controls/routeLink.ts, src/DotVVM.Framework/Resources/Scripts/tests/route-url.test.ts, src/DotVVM.Framework/Routing/DotvvmRoute.cs, src/DotVVM.Framework/Routing/DotvvmRouteParser.cs, src/DotVVM.Framework/Routing/RouteBase.cs, src/DotVVM.Framework/Routing/RouteTableJsonConverter.cs
Route parameters are now automatically URL encoded and decoded, both client-side and server-side.
Fix client-side parameter placement - mutliple parameters in one path segment is now supported.
To fix this, I had to strip the template URL from parameters constraints, as they are hard to parse.
Also, now we use invariant culture to format parameters.
+ unit tests for server-side, client-side URL building and for RouteLink control
=> Routes: Parameters and queries are URL encoded + client-side fixes

src/DotVVM.Framework/Hosting/DotvvmPresenter.cs, src/DotVVM.Samples.Common/DotVVM.Samples.Common.csproj, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/CustomResponseProperties/SimpleExceptionFilterViewModel.cs, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/StaticCommand/CustomAwaitableViewModel.cs, src/DotVVM.Samples.Common/Views/FeatureSamples/CustomResponseProperties/SimpleExceptionFilter.dothtml, src/DotVVM.Samples.Common/Views/FeatureSamples/StaticCommand/CustomAwaitable.dothtml, src/DotVVM.Samples.Tests/Feature/CommandResultTests.cs, src/DotVVM.Samples.Tests/Feature/StaticCommandTests.cs, src/DotVVM.Testing.Abstractions/SamplesRouteUrls.designer.cs
There was en issue with executing async commands. In case en exception was thrown, the command result was set to the executing `Task` instead of null. This caused a seriqalization error.
Also now, if user tries to return custom awaitable, they will be warned that this is not supported. Before it would just fail quietly.
=> Issue with async command execution

src/DotVVM.Framework.Tests.Common/Binding/StaticCommandCompilationTests.cs, src/DotVVM.Framework.Tests.Common/ControlTests/ControlTestHelper.cs, src/DotVVM.Framework.Tests.Common/ControlTests/MarkupControlTests.cs, src/DotVVM.Framework.Tests.Common/ControlTests/testoutputs/MarkupControlTests.MarkupControl_PassingStaticCommand.html, src/DotVVM.Framework/Compilation/Binding/StaticCommandBindingCompiler.cs, src/DotVVM.Framework/Compilation/Javascript/InvocationRewriterExpressionVisitor.cs, src/DotVVM.Framework/Compilation/Javascript/JavascriptTranslatableMethodCollection.cs, src/DotVVM.Framework/Compilation/Javascript/JavascriptTranslator.cs, src/DotVVM.Framework/Compilation/Javascript/JsViewModelPropertyAdjuster.cs, src/DotVVM.Framework/Controls/DotvvmMarkupControl.cs, src/DotVVM.Framework/Resources/Scripts/binding-handlers/introduce-alias.ts, src/DotVVM.Samples.Common/DotVVM.Samples.Common.csproj, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/MarkupControl/CommadPropertiesInMarkupControlViewModel.cs, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/MarkupControl/FakeDb.cs, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/MarkupControl/StaticCommandInMarkupControlCallingRegularCommandViewModel.cs, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/MarkupControl/StaticCommandInMarkupControlViewModel.cs, src/DotVVM.Samples.Common/Views/FeatureSamples/MarkupControl/CommandPropertiesInMarkupControl.dothtml, src/DotVVM.Samples.Common/Views/FeatureSamples/MarkupControl/Device.cs, src/DotVVM.Samples.Common/Views/FeatureSamples/MarkupControl/Device.dotcontrol, src/DotVVM.Samples.Common/Views/FeatureSamples/MarkupControl/Dialog.cs, src/DotVVM.Samples.Common/Views/FeatureSamples/MarkupControl/Dialog.dotcontrol, src/DotVVM.Samples.Common/Views/FeatureSamples/MarkupControl/StaticCommandInMarkupControl.dothtml, src/DotVVM.Samples.Common/Views/FeatureSamples/MarkupControl/StaticCommandInMarkupControlCallingRegularCommand.dothtml, src/DotVVM.Samples.Tests/Feature/MarkupControlTests.cs, src/DotVVM.Testing.Abstractions/SamplesRouteUrls.designer.cs
I try to use static command as much as possible to make my pages faster. However I ren into a severe limitation. It is impossible to bind `Command` property to static command binding in the markup control.
Example:
Let's assume I have `DeviceDetail` markup control used in the page like so:
```html
<cc:DeviceDetail Save={staticCommand: _root.Detail = service.Save(Detail); _alert.Show('Item saved')} />
``` 
I wanted to implement the `DeviceDetail` control as follows:
```html
@viewModel MyProject.DeviceViewModel
@baseType MyProject.Device 
<div>
<!-- ... --/>
<dot:Button Click={staticCommand: _control.Save()} Text="Save"/>
</div>
```
Code behind:
```csharp
public class Device : DotvvmMarkupControl {
public Command Save
{
get { return (Command)GetValue(SaveProperty); }
set { …
```
=> Static Commands in MarkupControl

src/DotVVM.Framework.Tests.Common/Binding/ExpressionHelperTests.cs, src/DotVVM.Framework/Compilation/Binding/ExpressionHelper.cs
This PR fixes a bug that failed method overloads search, for example in the following case:
- Suppose user created a method with given signature: `T Method<T>(Enumerable<T> arg)`
- User called the method by passing an array `T[]` as the first and the only argument
- DotVVM tries to resolve generic argument `T` based on `typeof(T[]).GetGenericArguments()` which fails for arrays
=> Fix generics resolving in method overloads search

src/DotVVM.Framework.Tests.Common/Runtime/config-tests/ConfigurationSerializationTests.SerializeResources.json, src/DotVVM.Framework/Configuration/DotvvmConfiguration.cs, src/DotVVM.Framework/Configuration/RestApiRegistrationHelpers.cs, src/DotVVM.Framework/ResourceManagement/ClientGlobalize/JQueryGlobalizeResourceRepository.cs, src/DotVVM.Framework/ResourceManagement/ResourcesRenderer.cs, src/DotVVM.Framework/ResourceManagement/ScriptResource.cs, src/DotVVM.Samples.Common/CommonConfiguration.cs
This is technically a breaking change, but it should have a lower impact than without this change.
Before this change, the dotvvm resource was defered (as it was a module), which caused a lot of issues.
=> ScriptResource is `defer`ed by default

src/DotVVM.Framework/Resources/Scripts/postback/internal-handlers.ts
The problem was that the static command commit was always rejected,
because it was not started as postback
=> Fix concurrency handler for staticCommands

src/DotVVM.Samples.Tests/Control/AuthenticatedViewTests.cs, src/DotVVM.Samples.Tests/Control/ContentPlaceHolderTests.cs, src/DotVVM.Samples.Tests/Control/DataPagerTests.cs, src/DotVVM.Samples.Tests/Control/EnabledPropertyTests.cs, src/DotVVM.Samples.Tests/Control/EnvironmentViewTests.cs, src/DotVVM.Samples.Tests/Control/HtmlLiteralTests.cs, src/DotVVM.Samples.Tests/Control/IncludeInPagePropertyTests.cs, src/DotVVM.Samples.Tests/Control/LinkButtonTests.cs, src/DotVVM.Samples.Tests/Control/RadioButtonTests.cs, src/DotVVM.Samples.Tests/Control/RouteLinkTests.cs, src/DotVVM.Samples.Tests/Control/SpaContentPlaceHolderTests.cs, src/DotVVM.Samples.Tests/Control/TextBoxTests.cs, src/DotVVM.Samples.Tests/Control/UpdateProgressTests.cs, src/DotVVM.Samples.Tests/Control/ValidationSummaryTests.cs, src/DotVVM.Samples.Tests/DotVVM.Samples.Tests.csproj, src/DotVVM.Samples.Tests/ErrorsTests.cs, src/DotVVM.Samples.Tests/Feature/DependencyInjectionTests.cs, src/DotVVM.Samples.Tests/Feature/LocalizationTests.cs, src/DotVVM.Samples.Tests/Feature/PostBackTests.cs, src/DotVVM.Samples.Tests/Feature/ReturnedFileTests.cs, src/DotVVM.Samples.Tests/Feature/ValidationTests.cs, src/DotVVM.Samples.Tests/Feature/ViewModelProtectionTests.cs
The new version of Riganti.Selenium has changed the behavior of all `AssertUI` functions. 
These functions have a `WaitFor` block inside of them now. So it's not required to write WaitFor block around every `AssertUI.Something()`.
=> Upgraded RIGANTI Selenium testing framework for UI tests 

src/DotVVM.Framework.Tests.Common/Binding/ExpressionHelperTests.cs, src/DotVVM.Framework/Compilation/Binding/MemberExpressionFactory.cs
While fixing a merge-conflict I noticed some issues introduced by a merge commit that is already in the `main` branch. This PR fixes the issues
=> Adjusted MemberExpressionFactory and uncommenting unit tests

src/DotVVM.Framework.Tests.Common/Binding/BindingCompilationTests.cs, src/DotVVM.Framework.Tests.Common/Binding/JavascriptCompilationTests.cs, src/DotVVM.Framework.Tests.Common/Binding/StaticCommandCompilationTests.cs, src/DotVVM.Framework.Tests.Common/ControlTests/testoutputs/ViewModulesServerSideTests.IncludeViewModule.html, src/DotVVM.Framework.Tests.Common/ControlTests/testoutputs/ViewModulesServerSideTests.IncludeViewModuleInControl.html, src/DotVVM.Framework.Tests.Common/DotVVM.Framework.Tests.Common.csproj, src/DotVVM.Framework.Tests.Common/Parser/Binding/BindingParserTests.cs, src/DotVVM.Framework/Compilation/Binding/ExpressionBuildingVisitor.cs, src/DotVVM.Framework/Compilation/Binding/StaticCommandBindingCompiler.cs, src/DotVVM.Framework/Compilation/Binding/VariableHoistingVisitor.cs, src/DotVVM.Framework/Compilation/Javascript/JsTemporaryVariableResolver.cs, src/DotVVM.Framework/Compilation/Parser/Binding/Parser/BindingParser.cs, src/DotVVM.Framework/Compilation/Parser/Binding/Parser/BlockBindingParserNode.cs, src/DotVVM.Framework/Controls/Infrastructure/BodyResourceLinks.cs
The syntax is `val variableName = value; nextExpression`.
The variable is not assignable again - it is always immutable.
Variable may shadow property names and variables defined ahead of it.
The variable may be accessed only in the `nextExpression`.
This version does not support automatic unwrapping Tasks.
We wanted to switch to using await in DotVVM 3 anyway, right?
see #776
=> Add support for variables in value bindings

src/DotVVM.Framework.Tests.Common/Runtime/config-tests/ConfigurationSerializationTests.RestAPI.json, src/DotVVM.Framework.Tests.Common/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json, src/DotVVM.Framework.Tests.Common/Runtime/config-tests/ConfigurationSerializationTests.SerializeResources.json, src/DotVVM.Framework/Configuration/DotvvmConfiguration.cs, src/DotVVM.Framework/DotVVM.Framework.csproj, src/DotVVM.Framework/ResourceManagement/EmbeddedResourceLocation.cs, src/DotVVM.Framework/ResourceManagement/FileResourceLocation.cs, src/DotVVM.Framework/ResourceManagement/UrlResourceLocation.cs, src/DotVVM.Framework/package.json, src/DotVVM.Framework/rollup.config.js, src/DotVVM.Samples.Common/CommonConfiguration.cs
This PR uses non-minified versions of DotVVM and Knockout when `configuration.Debug` is `true`.
=> Non-minified version of DotVVM in debug mode

src/DotVVM.Framework.Tests.Common/ControlTests/testoutputs/MarkupControlTests.MarkupControl_PassingStaticCommand.html, src/DotVVM.Framework.Tests.Common/ControlTests/testoutputs/ViewModulesServerSideTests.IncludeViewModuleInControl.html, src/DotVVM.Framework/Controls/Infrastructure/BodyResourceLinks.cs, src/DotVVM.Framework/Controls/KnockoutHelper.cs, src/DotVVM.Framework/Resources/Scripts/DotVVM.Debug.js, src/DotVVM.Framework/Resources/Scripts/api/api.ts, src/DotVVM.Framework/Resources/Scripts/binding-handlers/SSR-foreach.ts, src/DotVVM.Framework/Resources/Scripts/binding-handlers/introduce-alias.ts, src/DotVVM.Framework/Resources/Scripts/dotvvm-root.ts, src/DotVVM.Framework/Resources/Scripts/postback/http.ts, src/DotVVM.Framework/Resources/Scripts/postback/postback.ts, src/DotVVM.Framework/Resources/Scripts/postback/resourceLoader.ts, src/DotVVM.Framework/Resources/Scripts/postback/updater.ts, src/DotVVM.Framework/Resources/Scripts/serialization/date.ts, src/DotVVM.Framework/Resources/Scripts/spa/spa.ts, src/DotVVM.Framework/Resources/Scripts/state-manager.ts, src/DotVVM.Framework/Resources/Scripts/tests/helper.ts, src/DotVVM.Framework/Resources/Scripts/utils/evaluator.ts, src/DotVVM.Framework/Resources/Scripts/utils/logging.ts, src/DotVVM.Framework/Resources/Scripts/validation/validation.ts
This PR adds allows to turn on verbose logging on the client (by setting the `dotvvm-loglevel=verbose` in local storage).
I've changed all calls to `console.log/warn/error...` in the TypeScript code to call our custom logging functions (exposed publicly in `dotvvm.log...`).
We can make some extensibility points in the future if we want to send the errors to some other external service.
I've also added the "area" flag to these functions - it should help in understanding from which part of DotVVM the error message comes from. Also, in the future, I can imagine that it may be used to filter out unwanted messages.
=> Verbose logging on the client

src/DotVVM.Framework/Resources/Scripts/postback/redirect.ts
This was fixed in 2.5, but we haven't merged it correctly into `main`.
=> Postbacks were not disabled on classic non-SPA redirects

src/DotVVM.Framework/Resources/Scripts/state-manager.ts
This is only a small optimization, but it is fairly important as we are
misusing the updater to read state.
=> State udpater should skip the update when the new value is equal

src/DotVVM.Framework/Compilation/ControlTree/ControlTreeResolverBase.cs
This PR fixes weird DotVVM error reported by @martindybal. If user makes a mistake while specifying viewmodel (by referencing a non-existing class) for their master page, they receive a somewhat confusing error message.
The problem:
- DotVVM finds out that the specified viewmodel could not be found https://github.com/riganti/dotvvm/blob/7dc7e9d0cda757f953545f1f47e85ce0fb883662/src/DotVVM.Framework/Compilation/ControlTree/Resolved/ResolvedTreeBuilder.cs#L149
- However this information gets stripped and is not propagated further https://github.com/riganti/dotvvm/blob/7dc7e9d0cda757f953545f1f47e85ce0fb883662/src/DotVVM.Framework/Compilation/ControlTree/Resolved/ResolvedTreeRoot.cs#L29
If we were to add those errors there, I am not sure whether it could break something. In the meantime, I …
=> Improved error reporting for corrupted master page

src/DotVVM.Framework.Tests.Common/Parser/Binding/BindingParserTests.cs, src/DotVVM.Framework/Compilation/Binding/ExpressionBuildingVisitor.cs, src/DotVVM.Framework/Compilation/ControlTree/Resolved/ResolvedTreeBuilder.cs, src/DotVVM.Framework/Compilation/Parser/Binding/Parser/BindingParser.cs
This PR fixes small issues with parsing and subsequent validation of assembly qualified names.
DotVVM incorrectly interprets assembly name as generic, unless it is a `SimpleNameBindingParserNode`. Therefore, all instances of `MemberAccessBindingParserNode` are considered to be generics. Moreover, assigned node errors are later ignored completely.
* `@viewModel DotVVM.TestApp.ViewModels.DefaultViewModel, DotVVM.TestApp`
* DotVVM creates a node error indicating that the `DotVVM.TestApp` is a generic identifier
* `@viewModel DotVVM.TestApp.ViewModels.DefaultViewModel, DotVVM.TestApp<int>`
* Fails with an error: Unable to resolve type ...
DotVVM interprets assembly names as generic iff `MemberAccessBindingParserNode` contains a `GenericNameBindingParserNode`. Furthermore, all errors (not only …
=> Parsing assembly qualified names and propagating errors

src/DotVVM.Framework.Tests.Common/Binding/BindingCompilationTests.cs, src/DotVVM.Framework.Tests.Common/Binding/JavascriptCompilationTests.cs, src/DotVVM.Framework.Tests.Common/Parser/Binding/BindingParserTests.cs, src/DotVVM.Framework.Tests.Common/Parser/Binding/BindingTokenizerTests.cs, src/DotVVM.Framework/Compilation/Binding/ExpressionBuildingVisitor.cs, src/DotVVM.Framework/Compilation/Parser/Binding/Parser/BindingParser.cs, src/DotVVM.Framework/Compilation/Parser/Binding/Parser/BindingParserNodeVisitor.cs, src/DotVVM.Framework/Compilation/Parser/Binding/Parser/FormattedBindingParserNode.cs, src/DotVVM.Framework/Compilation/Parser/Binding/Parser/InterpolatedStringBindingParserNode.cs, src/DotVVM.Framework/Compilation/Parser/Binding/Tokenizer/BindingTokenType.cs, src/DotVVM.Framework/Compilation/Parser/Binding/Tokenizer/BindingTokenizer.cs
Resolves #362. This PR adds support for string interpolation in bindings.
Interpolated strings are always translated into C# `String.Format(...)` calls, unless a constant string is provided with no interpolation expressions. When compiling `String.Format(...)` calls to JavaScript, the function `dotvvm.globalize.format(...)` is used.
Implementation progress:
=> Added support for string interpolation in bindings

src/DotVVM.Framework.Tests.Common/Binding/JavascriptCompilationTests.cs, src/DotVVM.Framework/Configuration/RestApiRegistrationHelpers.cs, src/DotVVM.Framework/Resources/Scripts/DotVVM.Globalize.ts, src/DotVVM.Framework/Resources/Scripts/binding-handlers/textbox-text.ts
We renamed `dotvvm.globalization.parseDotvvmDate` in the public API, and forgot to add an alias. 
Since it has probably broken several libraries, so this PR adds the alias back (and changes references to the new name in the code).
=> Added alias parseDotvvmDate to preserve back-compatibility

src/DotVVM.Framework/Resources/Scripts/metadata/coercer.ts, src/DotVVM.Framework/Resources/Scripts/tests/coercer.test.ts, src/DotVVM.Samples.Common/DotVVM.Samples.Common.csproj, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/Serialization/EnumSerializationCoercionViewModel.cs, src/DotVVM.Samples.Common/Views/FeatureSamples/Serialization/EnumSerializationCoercion.dothtml, src/DotVVM.Samples.Tests/Feature/SerializationTests.cs, src/DotVVM.Testing.Abstractions/SamplesRouteUrls.designer.cs
In .NET, you can assign any numeric value to an enum, even if there is no member assigned for the number value. 
For example, a property of type `public enum MyEnum { One = 1, Two = 2}` can still have `0` as a value.
The coercer was not allowing such values, which is now fixed by this PR. 
In order for the value to be serialized/deserialized correctly, the coercer uses `string` for members defined in the enum, and `number` for any other values.
=> Enum coercion was too strict

src/DotVVM.Framework.Tests.Common/Binding/JavascriptCompilationTests.cs, src/DotVVM.Framework/Compilation/Javascript/GenericMethodCompiler.cs, src/DotVVM.Framework/Compilation/Javascript/JavascriptTranslatableMethodCollection.cs, src/DotVVM.Framework/Resources/Scripts/collections/sortingHelper.ts, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/LambdaExpressions/StaticCommandsViewModel.cs
It was possible to simplify current implementation of `OrderBy` and `OrderByDescending`. This also resolved some previously discovered issues regarding comparing by value vs by reference.
=> Fixed issues with OrderBy(Descending) and simplified their translations

src/DotVVM.Framework/Resources/Scripts/dotvvm-root.ts, src/DotVVM.Framework/Resources/Scripts/metadata/metadataHelper.ts
DotVVM previously lacked better support for accessing type metadata. To resolve this issue, this PR introduces some helper functions into `dotvvm.metadata.*`
=> Added helper functions for working with type metadata

src/DotVVM.Framework/Resources/Scripts/state-manager.ts, src/DotVVM.Framework/Resources/Scripts/tests/stateManagement.test.ts
This was previously updating the array element with undefined value,
which causes pretty weird problems in cases when staticCommand affecting
the array element updates it after it was removed from the viewmodel
=> state manager: Updating non-existed array element does nothing

src/DotVVM.Framework/Controls/HtmlGenericControl.cs, src/DotVVM.Samples.Common/Controls/AttributeToStringConversionControl.cs, src/DotVVM.Samples.Common/DotVVM.Samples.Common.csproj, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/Attribute/ToStringConversionViewModel.cs, src/DotVVM.Samples.Common/Views/FeatureSamples/Attribute/ToStringConversion.dothtml, src/DotVVM.Samples.Tests/Feature/AttributeTests.cs, src/DotVVM.Testing.Abstractions/SamplesRouteUrls.designer.cs
When playing with Web Components, I've found out that binding non-string values in attributes work for value bindings, but not for resource bindings - an exception about unsupported attribute type was thrown.
I've added support for:
* numeric types
* `bool`, the attribute is omitted when it's `false`
* enums and `Guid` (I am just calling `ToString`)
I haven't added a special case for `DateTime` as it is not clear whether the user wants to bind just the date (for example into `input[type=date]`), or both date and time, and in what format.
=> HtmlGenericControl supports numeric and boolean values for attributes

src/DotVVM.Framework.Tests/Binding/JavascriptCompilationTests.cs, src/DotVVM.Framework/Compilation/Javascript/JavascriptTranslatableMethodCollection.cs, src/DotVVM.Framework/Resources/Scripts/dotvvm-root.ts
This PR introduces following changes:
- `arrayHelper`, `dictionaryHelper` and `stringHelper` were moved into `dotvvm.translations` and no longer pollute dotvvm root
- Registrations that previously required complex logic to select `MethodInfo` were rewritten using parameterFilter lambdas
#1009 should be merged first.
=> Refactored JavaScript translations

src/DotVVM.CommandLine/Names.cs, src/DotVVM.CommandLine/OpenApi/ApiClientUtils.cs, src/DotVVM.Framework.Tests/Binding/JavascriptCompilationTests.cs, src/DotVVM.Framework/Compilation/Javascript/JavascriptTranslatableMethodCollection.cs, src/DotVVM.Framework/Compilation/Parser/Binding/Parser/BindingParser.cs, src/DotVVM.Framework/Controls/KnockoutHelper.cs, src/DotVVM.Framework/Controls/RouteLink.cs, src/DotVVM.Framework/Controls/RouteLinkHelpers.cs, src/DotVVM.Framework/Controls/ValidationSummary.cs, src/DotVVM.Framework/Hosting/MarkupFile.cs, src/DotVVM.Framework/ResourceManagement/ClientGlobalize/JQueryGlobalizeScriptCreator.cs, src/DotVVM.Samples.BasicSamples.Api.AspNetCore/ViewModels/GeneratorViewModel.cs, src/DotVVM.Samples.Tests/ErrorsTests.cs, src/DotVVM.Samples.Tests/Feature/ViewModelProtectionTests.cs
Resolves #950. This PR changes all occurrences of `.ToUpper()` and `.ToLower()` to their culture-invariant alternatives. I also fixed JS translations and introduced two new:
**Changed translations**:
- `string.ToLower()` maps to `String.prototype.toLocaleLowerCase()`
- `string.ToUpper()` maps to `String.prototype.toLocaleUpperCase()`
**New translations**:
- `string.ToLowerInvariant()` maps to `String.prototype.toLowerCase()`
- `string.ToUpperInvariant()` maps to `String.prototype.toUpperCase()`
=> Removed usage of culture-sensitive string operations

src/DotVVM.Framework.Tests/Binding/CustomExtensionMethodTests.cs, src/DotVVM.Framework/Compilation/Binding/MemberExpressionFactory.cs
This PR fixes two issues that can be observed when compiling extension method calls. These issues were found while testing #1057.
1. Repeated importing of the same namespace ends with `"Found ambiguous overloads of method ..."`.
- This is due to the fact that individual methods are enumerated multiple times (once for each import)
2. Extension methods with default parameter values fail when the default value should have been used
- Default values were not added to the argument list
- This caused the invocation of `Expression.Call(...)` to throw as the arguments count did not match parameters count
=> Fixed issues with extension methods

src/DotVVM.Framework.Tests/Binding/BindingCompilationTests.cs, src/DotVVM.Framework.Tests/Binding/JavascriptCompilationTests.cs, src/DotVVM.Framework/Compilation/CompiledAssemblyCache.cs, src/DotVVM.Framework/Compilation/Javascript/JavascriptTranslatableMethodCollection.cs, src/DotVVM.Samples.Common/DotVVM.Samples.Common.csproj, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/JavascriptTranslation/DateTimeTranslationsViewModel.cs, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/JavascriptTranslation/WebUtilityTranslationsViewModel.cs, src/DotVVM.Samples.Common/Views/FeatureSamples/JavascriptTranslation/DateTimeTranslations.dothtml, src/DotVVM.Samples.Common/Views/FeatureSamples/JavascriptTranslation/WebUtilityTranslations.dothtml, src/DotVVM.Samples.Tests/Feature/DateTimeTranslationTests.cs, src/DotVVM.Samples.Tests/Feature/WebUtilityTranslationTests.cs, src/DotVVM.Testing.Abstractions/SamplesRouteUrls.designer.cs
Resolves #831. This PR adds the following JS translations:
* `Year`
* `Month`
* `Day`
* `Hour`
* `Minute`
* `Second`
* `Millisecond`
Use these together with `@import System.Net`
* `UrlEncode(str)` mapped to `encodeURIComponent(str)`
* `UrlDecode(str)` mapped to `decodeURIComponent(str)`
=> Added JavaScript translations for `DateTime` and `WebUtility`

src/DotVVM.Framework.Tests/Binding/BindingCompilationTests.cs, src/DotVVM.Framework.Tests/Binding/JavascriptCompilationTests.cs, src/DotVVM.Framework/Compilation/Binding/ExpressionBuildingVisitor.cs, src/DotVVM.Framework/Compilation/Javascript/JavascriptTranslatableMethodCollection.cs, src/DotVVM.Framework/Resources/Scripts/collections/arrayHelper.ts, src/DotVVM.Samples.Common/DotVVM.Samples.Common.csproj, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/JavascriptTranslation/ArrayTranslationViewModel.cs, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/JavascriptTranslation/ListIndexerTranslationViewModel.cs, src/DotVVM.Samples.Common/Views/FeatureSamples/JavascriptTranslation/ArrayTranslation.dothtml, src/DotVVM.Samples.Common/Views/FeatureSamples/JavascriptTranslation/ListIndexerTranslation.dothtml, src/DotVVM.Samples.Tests/Feature/ArrayTranslationTests.cs, src/DotVVM.Samples.Tests/Feature/ListTranslationTests.cs, src/DotVVM.Testing.Abstractions/SamplesRouteUrls.designer.cs
Resolves #977. This PR fixes issues that occurred in staticCommands when assigning into lists and arrays.
**Changes**:
- **Lists**: Registered JS translation for set_Indexer on Lists and provided its implementation that updates observables
- **Arrays**: Assignments to array elements are compiled using an explicit call to `Array.SetValue(value, index)`. This step made it possible to register a JS translation for array element assignments. The typescript implementation is the shared with lists.
=> Fixed issue with assigning to arrays and lists

src/DotVVM.Framework.Tests/Binding/BindingCompilationTests.cs, src/DotVVM.Framework/Compilation/Parser/Binding/Parser/FormattedBindingParserNode.cs, src/DotVVM.Framework/Compilation/Parser/Binding/Parser/InterpolatedStringBindingParserNode.cs, src/DotVVM.Framework/Compilation/Parser/Binding/Parser/LambdaBindingParserNode.cs, src/DotVVM.Framework/Compilation/Parser/Binding/Parser/TypeOrFunctionReferenceBindingParserNode.cs, src/DotVVM.Framework/Compilation/Parser/Binding/Parser/TypeReferenceBindingParserNode.cs
This PR fixes implementations of `GetNodes` and `GetChildNodes` on recently added binding parser nodes. Alongside this change I removed a single unit test that was identified as faulty once node enumerables were fixed.
This change is necessary in order to add support for new data-binding constructs in DotVVM VS Extension
=> Fixed implementations of `GetNodes` and `GetChildNodes`

src/DotVVM.Framework.Tests/Binding/BindingCompilationTests.cs, src/DotVVM.Framework/Compilation/Binding/ExpressionNullPropagationVisitor.cs
=> Fixed issue with assigning values to nullable types

src/DotVVM.Framework/Controls/DotvvmMarkupControl.cs
This caused weird bugs when this constructor was used and
the markup control contained @js directive, since the resource was not loaded
=> fix OnPreInit invocation on dotvvm markup control

src/DotVVM.Framework.Tests/Binding/JavascriptCompilationTests.cs, src/DotVVM.Framework.Tests/Parser/Binding/BindingTokenizerTests.cs, src/DotVVM.Framework/Compilation/Javascript/JavascriptTranslatableMethodCollection.cs, src/DotVVM.Framework/Compilation/Parser/Binding/Parser/BindingParser.cs, src/DotVVM.Framework/Compilation/Parser/Binding/Tokenizer/BindingTokenizer.cs, src/DotVVM.Framework/Resources/Scripts/utils/stringHelper.ts, src/DotVVM.Samples.BasicSamples.Owin/package-lock.json, src/DotVVM.Samples.Common/DotVVM.Samples.Common.csproj, src/DotVVM.Samples.Common/ViewModels/FeatureSamples/StringInterpolation/StringInterpolationViewModel.cs, src/DotVVM.Samples.Common/Views/FeatureSamples/StringInterpolation/StringInterpolation.dothtml, src/DotVVM.Samples.Tests/Feature/StringInterpolationTests.cs, src/DotVVM.Testing.Abstractions/SamplesRouteUrls.designer.cs
This PR fixes a few issues that were found during testing string interpolation feature.
1. `dotvvm.globalization.format` function was incorrectly called. This could have caused rendering of `undefined value`s when user specified multiple interpolated expressions
2. `dotvvm.globalization.format` incorrectly interpretted formatting options. This caused that many formatting options were unrecognized by the globalization library
3. `BindingTokenizer` could have read one character past the string boundary. This was only observable when a string ends with `{{` or `}}` sequence. Rendered strings had additional character (always the ending quotation mark).
4. `BindingParser` was not skipping whitespaces after parsing interpolated string. This caused parsing exceptions in some cases.
Together with …
=> Fixed issues with string interpolation

src/DotVVM.Framework.Tests/ControlTests/testoutputs/SimpleControlTests.RouteLink.html, src/DotVVM.Framework/Controls/RouteLink.cs, src/DotVVM.Framework/Controls/RouteLinkHelpers.cs
Both the binding and server-side rendered value should be included in both
Server and Client Mode. Links are essential part of web and should be
server-side rendered whenever possible.
resolves  #781
=> Always render everything in RouteLink

src/DotVVM.Framework.Tests/Binding/BindingCompilationTests.cs, src/DotVVM.Framework.Tests/Binding/JavascriptCompilationTests.cs, src/DotVVM.Framework/Compilation/Inference/TypeInferer.cs
This PR fixes an issue with type inferer. Unification of two exactly same types is valid and must always succeed. Previously, type inferer did not handle this edge-case well, which caused issues with infering lambda parameters on more complex methods, such as on `ListExtensions.AddOrUpdate(...)` method.
=> Fixed issue in type inferer when unifying same types

src/DotVVM.Framework.Tests/Binding/JavascriptCompilationTests.cs, src/DotVVM.Framework/Binding/HelperNamespace/NetFrameworkExtensions.cs, src/DotVVM.Framework/Compilation/Javascript/JavascriptTranslatableMethodCollection.cs, src/DotVVM.Framework/Resources/Scripts/tests/stringHelper.test.ts, src/DotVVM.Framework/Resources/Scripts/utils/stringHelper.ts, src/DotVVM.Samples.Common/Views/FeatureSamples/JavascriptTranslation/StringMethodTranslations.dothtml, src/DotVVM.Samples.Tests/Feature/StaticCommandStringMethodTests .cs
This PR adds another batch of JS translations for string methods:
- `string.Contains(string value, StringComparison options)`
- `string.EndsWith(string value, StringComparison options)`
- `string.IndexOf(string value, StringComparison options)`
- `string.IndexOf(string value, int startIndex, StringComparison options)`
- `string.LastIndexOf(string value, StringComparison options)`
- `string.LastIndexOf(string value, int startIndex, StringComparison options)`
- `string.StartsWith(string value, StringComparison options)`
The only truly recognized values from `StringComparison` enums are `InvariantCulture` and `InvariantCultureIgnoreCase` with the `InvariantCulture` being the default. Once this feature gets merged I will update relevant documentation pages accordingly.
=> Added JS translations for string method overloads with `StringComparison`

src/DotVVM.CommandLine/DotVVM.CommandLine.csproj, src/DotVVM.Compiler/AppDomainCompilerExecutor.cs, src/DotVVM.Compiler/CompilerArgs.cs, src/DotVVM.Compiler/DefaultCompilerExecutor.cs, src/DotVVM.Compiler/DependencyContextCompilerExecutor.cs, src/DotVVM.Compiler/DotVVM.Compiler.csproj, src/DotVVM.Compiler/ICompilerExecutor.cs, src/DotVVM.Compiler/IsExternalInit.cs, src/DotVVM.Compiler/Program.cs, src/DotVVM.Compiler/ProjectLoader.cs, src/DotVVM.Framework/Compilation/Static/ConfigurationInitializer.cs
Adds a `--list-props` switch to the `DotVVM.Compiler` that loads an assembly and lists all `DotvvmProperties` declared inside it. It's meant for internal usage, can break in the future, and thus cannot be invoked through `DotVVM.CommandLine`.
Besides that, this PR makes a few refactorings to facilitate the switch and adds a proper help text.
If you want to try the switch out, build the `DotVVM.Compiler` project, `cd` to `src/DotVVM.Compiler`, and:
* If your DotVVM project targets .NET Core 3.1:
```bash
dotnet run -f netcoreapp3.1 -- --list-props "<path to your project's dll>" "<path to your project's dir>"
```
* If your DotVVM project targets .NET 5:
```bash
dotnet run -f net5.0 -- --list-props "<path to your project's dll>" "<path to your project's dir>"
```
* If your DotVVM project …
=> Add a switch that lists dotprops to the compiler

src/DotVVM.Framework.Testing/BindingTestHelper.cs, src/DotVVM.Framework.Tests/Binding/BindingCompilationTests.cs, src/DotVVM.Framework.Tests/Binding/JavascriptCompilationTests.cs, src/DotVVM.Framework/Binding/BindingHelper.cs, src/DotVVM.Framework/Compilation/Binding/ExpressionBuildingVisitor.cs, src/DotVVM.Framework/Compilation/BindingCompiler.cs, src/DotVVM.Samples.Common/DotVVM.Samples.Common.csproj, src/DotVVM.Samples.Common/ViewModels/ControlSamples/Repeater/IndexInNestedRepeaterViewModel.cs, src/DotVVM.Samples.Common/ViewModels/ControlSamples/Repeater/NestedRepeaterEntry.cs, src/DotVVM.Samples.Common/Views/ControlSamples/Repeater/IndexInNestedRepeater.dothtml, src/DotVVM.Samples.Tests/Control/NestedRepeaterTests.cs, src/DotVVM.Samples.Tests/Feature/StringInterpolationTests.cs, src/DotVVM.Testing.Abstractions/SamplesRouteUrls.designer.cs
The syntax is _parent._index, _root._index and so on. _this._index can also
be used, athough it's of little practical use. Only difference between
_index and _this._index is that the _this will disallow access to
parameters which are inherited from above. For example, _this._page will only
work in the root data context while _page works essentialy everywhere.
resolves #392
=> Enable access to parent extension parameters

src/DotVVM.Framework/Resources/Scripts/global-declarations.ts, src/DotVVM.Framework/Resources/Scripts/postback/postback.ts, src/DotVVM.Framework/Resources/Scripts/postback/redirect.ts, src/DotVVM.Framework/Resources/Scripts/postback/staticCommand.ts
Fixes problems with redirecting staticCommand in SPA
- the redirect worked, but since no exception was thrown, rest of the command continued to run, which caused problems on the new page
- now it throws an exception, which cancels rest of the binding
- also, the exception may be similarly thrown by a user function if it would want to make a redirect
=> Fix redirection in staticCommand & SPA

src/DotVVM.Framework/Compilation/Javascript/JavascriptTranslatableMethodCollection.cs
Unfortunately, netcoreapp2.0 does not contain the same overloads of string.Contains as the greater versions. So I split the registration of `string.Contains()` to be able to check whether the overload of `string.Contains(string, StringComparison)` exists.
=> Split registration of string.Split and String.Contains methods

src/DotVVM.Framework/Resources/Scripts/serialization/deserialize.ts
The previous version assigned the new value into state manager,
but it then immediately did the old deserialize logic.
The deserialization forces creation of all observables in the tree, even
if they are not used in the view, which is what makes it so slow
=> Actually use setState in deserialize function

src/DotVVM.Framework/Controls/InlineScript.cs, src/DotVVM.Framework/ResourceManagement/ResourceManager.cs
This means that each script will be only included once, but
it will start working in Repeaters and other kinds of client-side
templates.
Additionally, when bound to a value using resource binding,
one InlineScript will be able to generate multiple resources if the resource
bidning differs for collection rows, for example
=> Inline script will use hash ID to identify

src/DotVVM.Framework/DotVVM.Framework.csproj, src/DotVVM.Framework/rollup.config.js
In case yarn is not installed, npm is used.
Yarn is preferred, because it takes less time to run it, so it's
less annoying.
The Target only runs when any typescript file is changed,
otherwise it's skipped by MSBuild
In case there are some JS error, the build should continue normally,
so hopefully it won't cause some build issues
This should solve the problem that we forget to build the JS and
then something does not work. And when someone clones the repo,
it just won't compile because the JS files are missing
=> Add a MSBuild task for running `yarn build`

ci/linux/run.sh, ci/windows/run.ps1
It only induces instability into the pipeline and it's handled by the
Github Action
=> Remove JS unit tests from Azure CI

src/Framework/Framework/Controls/HtmlWriter.cs, src/Framework/Framework/Controls/KnockoutHelper.cs, src/Framework/Framework/DotVVM.Framework.csproj, src/Framework/Framework/Hosting/ErrorPages/DotvvmErrorPageRenderer.cs, src/Tests/ControlTests/testoutputs/CompositeControlTests.WrappedRepeaterControl.html, src/Tests/ControlTests/testoutputs/ServerSideStyleTests.PostbackHandlers.html, src/Tests/ControlTests/testoutputs/SimpleControlTests.RouteLink.html, src/Tests/ControlTests/testoutputs/ViewModulesServerSideTests.IncludeViewModule.html, src/Tests/ControlTests/testoutputs/ViewModulesServerSideTests.IncludeViewModuleInControl.html, src/Tests/Runtime/DotvvmControlRenderedHtmlTests.cs, src/Tests/Runtime/HtmlWriterTests.cs, src/Tests/Runtime/ScriptEndingTests.cs
Implemented custom HtmlEncoding that takes into account if
we are writing attribute and if quotes or apostrophes are used.
We can also assume that we use UTF-8 encoding.
That allows us to encode less characters which improves readability
of the generated code and performance (I will prepare results from benchmarking before we merge this)
=> Reduce redundant noise in generated HTML

src/Framework/Framework/Hosting/DotvvmRequestContextExtensions.cs, src/Framework/Framework/ResourceManagement/LinkResourceBase.cs, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeResources.json
* when possible (a local fallback script is available), we'll render
the integrity hash automatically
* Otherwise a debug warning will be shown that recommends the users to
either server the resource locally or specify the IntegrityHash property. The warning can be also silenced by setting VerifyResourceIntegrity to false.
=> Recommend users to use integrity hashes on scripts

src/Framework/Framework/Binding/DotvvmCapabilityProperty.Helpers.cs, src/Framework/Framework/Binding/DotvvmCapabilityProperty.cs, src/Framework/Framework/Utils/ReflectionUtils.cs, src/Tests/Runtime/CapabilityPropertyTests.cs
Before, all properties were declared new, and a conflict exception
was raised. Now it's allowed if the type matches, which allow
adding capabilities to existing controls.
This PR depends on #1129
=> Capabilities may use existing properties

src/Framework/Framework/Binding/DotvvmCapabilityProperty.cs, src/Framework/Framework/Compilation/ControlTree/DefaultControlResolver.cs, src/Framework/Framework/Controls/ButtonBase.cs, src/Framework/Framework/Controls/CheckableControlBase.cs, src/Framework/Framework/Controls/HtmlGenericControl.cs, src/Framework/Framework/Controls/RouteLink.cs, src/Tests/Runtime/CapabilityPropertyTests.cs
More specifically `prefix + capabilityType.Name` is used as a default name for
these DotvvmProperties. When declared using RegisterCapability method,
name other can be specified. However, properties declared implicitly
through GetContents arguments or through other capabilities
will ignore the argument/property name and use the
capability name instead
=> Capability properties will implicitly use capability name as property name

src/Framework/Framework/Binding/DotvvmProperty.cs, src/Framework/Framework/Compilation/ControlTree/DefaultControlResolver.cs, src/Framework/Framework/Compilation/ControlTree/DotvvmPropertyGroup.cs, src/Framework/Framework/Hosting/DotvvmPropertySerializableList.cs, src/Framework/Framework/Hosting/ErrorPages/ErrorPageTemplate.cs, src/Framework/Framework/Hosting/VisualStudioHelper.cs, src/Framework/Framework/NullableAttributes.cs, src/Framework/Framework/ResourceManagement/ReflectionAssemblyJsonConverter.cs, src/Framework/Framework/Utils/FunctionalExtensions.cs, src/Tests/Runtime/ConfigurationSerializationTests.cs, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.AuxOptions.json, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.ExperimentalFeatures.json, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.Markup.json, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.RestAPI.json, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeEmptyConfig.json, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeResources.json, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeRoutes.json
This should help the VS extension with all the new ways to register
dotvvm properties. Could also help humans to debug why some property
does not exist.
=> Serialize all properties into the dotvvm_serialized_config.json.tmp

src/Framework/Framework/Controls/DotvvmBindableObjectHelper.cs, src/Framework/Framework/Controls/DotvvmControl.cs, src/Framework/Framework/Controls/HtmlGenericControl.cs, src/Framework/Framework/Controls/IControlWithHtmlAttributes.cs, src/Tests/ControlTests/CompositeControlTests.cs
AddAttribute, AddCssClass, and similar. These helpers are slightly
modified version of those in BusinessPack, which should demonstrate that
they are useful
=> Add helper functions for working with html controls

src/Framework/Framework/Resources/Scripts/state-manager.ts
The problem is that we used to set isViewModelUpdating to false before
we invoked ko.delaySync.resume(). This lead to actually updating the controls
after when isViewModelUpdating was already false.
I also moved invocation of the newState event into this isViewModelUpdating=true
block, since it's also used for updating controls
=> Fix isViewModelUpdating with ko.delaySync

src/Framework/Framework/Compilation/Binding/MemberExpressionFactory.cs, src/Framework/Framework/Compilation/Javascript/JavascriptTranslatableMethodCollection.cs, src/Tests/Binding/BindingCompilationTests.cs, src/Tests/Binding/JavascriptCompilationTests.cs
This is useful for invoking a specific overload of a method (for example Math.Round),
only conversions which do basically nothing are implemented.
We don't support casting syntax, and this is easier to implement :sweat_smile:
=> Add translations for Convert.ToX for numeric types

src/Framework/Framework/Compilation/Javascript/JavascriptTranslator.cs, src/Framework/Framework/Controls/Button.cs, src/Framework/Framework/Controls/KnockoutHelper.cs, src/Framework/Framework/Controls/TextOrContentCapability.cs, src/Framework/Testing/ControlTestHelper.cs, src/Samples/Common/Views/ControlSamples/TemplateHost/CompositeListControlWithTemplate.cs, src/Tests/ControlTests/CompositeControlTests.cs, src/Tests/ControlTests/testoutputs/CompositeControlTests.CommandDataContextChange.html, src/Tests/ControlTests/testoutputs/CompositeControlTests.WrappedRepeaterControl.html, src/Tests/ControlTests/testoutputs/ServerSideStyleTests.PostbackHandlers.html
I promised to add this test for staticCommands after merging one of my PRs.
staticCommands seem to work well, commands needed slight adjustion in JavascriptTranslator
=> Add test for runtime change of data context of commands

src/Framework/Framework/Compilation/Binding/ExpressionNullPropagationVisitor.cs, src/Tests/Binding/NullPropagationTests.cs
We don't do null propagation on method arguments, but extension method's
first argument is essentially a target, so we'll do null propagation on that
resolves  #1185
=> Fixed null propagation for extension methods

src/Framework/Framework/Resources/Scripts/controls/fileUpload.ts
We instead replace the collection with the new file. If you don't like
it and want to allow users upload multiple files, then please
enable the `AllowMultipleFiles` option - it will also allow multiselect
in the dialog.
resolves #985
=> file upload: Don't put multiple files in collection when AllowMultipleFiles = false

src/Framework/Framework/Compilation/DotvvmViewCompilationServiceExtensions.cs, src/Framework/Framework/Configuration/ViewCompilationConfiguration.cs
This helps the healthcheck to make more sense by default. Should also help with user facing latency after the app is restarted
=> Make view precompilation the default in production mode

src/Tools/HotReload/AspNetCore/Configuration/DotvvmServiceCollectionExtensions.cs, src/Tools/HotReload/AspNetCore/Scripts/dotvvm.hotreload.js, src/Tools/HotReload/Common/HotReloadErrorPageExtension.cs, src/Tools/HotReload/Common/HotReloadMarkupFileLoader.cs, src/Tools/HotReload/Owin/Configuration/DotvvmServiceCollectionExtensions.cs, src/Tools/HotReload/Owin/Scripts/dotvvm.hotreload.js
When testing on a real project, I discovered a few issues - especially there was a problem with Visual Studio which doesn't modify the file but performs a series of operations including rename.
=> Hot reload fixes - disabled when debug=false

src/Framework/Framework/Binding/DotvvmCapabilityProperty.cs, src/Framework/Framework/Binding/DotvvmPropertyUtils.cs, src/Framework/Framework/Compilation/ControlTree/DotvvmPropertyGroup.cs, src/Framework/Framework/Compilation/Styles/StyleBuilderMethods.cs, src/Framework/Framework/Compilation/Styles/StyleMatchContextMethods.cs, src/Framework/Framework/Controls/DotvvmBindableObjectHelper.cs, src/Framework/Framework/Utils/ReflectionUtils.cs, src/Tests/ControlTests/ServerSideStyleTests.cs, src/Tests/ControlTests/testoutputs/ServerSideStyleTests.CapabilitySetting.html
Just basic support to be able to at least get/set properties
only available through capabilities. The API is fairly simple -
it's just an extension of the existing parser from Linq.Expression:
`GetProperty(c => c.Prop)`. Now it allows more complex expressions:
* c => c.Capability.Property
* c => c.PropertyGroup["constant"]
* c => c.PropertyGroup[localVariable]
* c => c.Capability.PropertyGroup["x"]
Note that the same parser is used for the control.SetProperty(..., ...) which
available at runtime, so I tried to not make it very slow.
It might be convenient to use it there as well, but it's not
recommended in performance sensitive scenarios (like in dotvvm controls)
=> Add basic support for capabilities in server-side styles

src/Framework/Framework/Configuration/DotvvmConfiguration.cs, src/Framework/Framework/Controls/GridViewTextColumn.cs, src/Framework/Framework/Controls/Literal.cs, src/Framework/Framework/Controls/SelectorBase.cs, src/Framework/Framework/Controls/TextBox.cs, src/Framework/Framework/ResourceManagement/FileResourceLocation.cs, src/Framework/Framework/ResourceManagement/UrlResourceLocation.cs, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json
Most of these are obsolete for many years now (from DotVVM 2).
Selector.*Member did not work at all,
TextBox.ValueType will basically work even when removed.
=> Remove obsolete control properties

src/Framework/Framework/Compilation/ControlTree/UsedPropertiesFindingVisitor.cs, src/Framework/Framework/Compilation/Parser/Dothtml/Parser/DothtmlParser.cs, src/Framework/Framework/Controls/DotvvmMarkupControl.cs, src/Framework/Framework/Controls/Internal.cs, src/Framework/Framework/DependencyInjection/DotVVMServiceCollectionExtensions.cs, src/Tests/ControlTests/MarkupControlTests.cs, src/Tests/ControlTests/testoutputs/MarkupControlTests.MarkupControl_PassingStaticCommand.html, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json
Another crack at reducing the amount of bullshit HTML we produce...
Just added a visitor which goes through all client-side bindings
and checks which properties are actually used.
Then, when rendering a markup control, only those will be included.
It also reduces the possibility of invoking arbitrary commands bound to
the markup control.
And it will stop exposing objects which may not be intended for the user.
It is technically a breaking change for people accessing the $control field
manually, but I hope there is not that many of them.
=> markup controls: Don't render unused properties

src/Framework/Framework/Resources/Scripts/collections/dictionaryHelper.ts
We generally return unwrapped objects from the translations,
but here it was missing. The translated JS assumed that it was
not observable, so it led to bugs.
resolves #1221
=> Dictionary[X] translation should not return observable

src/Framework/Framework/Configuration/DotvvmCompilationPageConfiguration.cs, src/Framework/Framework/Configuration/DotvvmConfigurationSerializationResolver.cs, src/Framework/Framework/Configuration/DotvvmExperimentalFeaturesConfiguration.cs, src/Framework/Framework/Configuration/DotvvmFeatureFlag.cs, src/Framework/Framework/Configuration/DotvvmGlobalFeatureFlag.cs, src/Framework/Framework/Configuration/DotvvmSecurityConfiguration.cs, src/Framework/Framework/Diagnostics/CompilationPageViewModel.cs, src/Framework/Framework/Hosting/DotvvmPresenter.cs, src/Framework/Framework/Hosting/DotvvmRequestContextExtensions.cs, src/Framework/Framework/Hosting/InterruptReason.cs, src/Framework/Framework/Hosting/Middlewares/DotvvmReturnedFileMiddleware.cs, src/Framework/Framework/Hosting/Middlewares/DotvvmRoutingMiddleware.cs, src/Framework/Hosting.AspNetCore/Security/DefaultCsrfProtector.cs, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.AuxOptions.json, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.ExperimentalFeatures.json, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.Markup.json, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.RestAPI.json, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeEmptyConfig.json, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeResources.json, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeRoutes.json
Switches were added to DotvvmSecurityConfiguration, so the behavior
can be configured.
* X-Frame-Options: DENY is used by default. It should pose no problem,
since DotVVM did not work with iframes anyway due to cookie
SameSite policy. When CrossSite frames are enabled, the cookie will
have SameSite=None
* we also check Sec-Fetch-Dest - if it's an iframe, we validate on server that iframes are allowed.
This mostly allows us to print a nicer error message, but may also in theory prevent some iframe timing attacks
* X-XSS-Protection: 1; mode=block
probably not super useful, but also not harmful
* X-Content-Type-Options: nosniff
- disable inference of content-type based on content, this could prevent some XSS attacks.
probably also not super useful, but very unlikely to cause any problems.
* …
=> Use http security headers by default

src/Framework/Framework/Binding/DotvvmCapabilityProperty.cs, src/Framework/Framework/Compilation/ControlTree/Resolved/ResolvedControl.cs, src/Framework/Framework/Compilation/ControlTree/Resolved/ResolvedPropertyCapability.cs, src/Framework/Framework/Compilation/ControlTree/ResolvedTreeHelpers.cs, src/Framework/Framework/Compilation/Styles/StyleMatchContextMethods.cs, src/Framework/Framework/Utils/ReflectionUtils.cs, src/Tests/ControlTests/ServerSideStyleTests.cs, src/Tests/ControlTests/testoutputs/ServerSideStyleTests.CapabilityReads.html
For example, this makes it possible to write a common function for a style
and for a control.
Potentially, this infrastucture could be used to execute
entire composite controls at compile-time. This makes is a bit more
limiting, since it's only executed once, but if you wish
to create data bindings in the control, it's the only option
that will not make the page super slow just by putting
the control in a Repeater
=> Make it possible to access entire capability in server-side styles

.github/workflows/main.yml, src/Directory.Build.props, src/Framework/Core/DotVVM.Core.csproj, src/Framework/Framework/Binding/DotvvmProperty.cs, src/Framework/Framework/Binding/ValueOrBinding.cs, src/Framework/Framework/Compilation/ControlTree/LifecycleRequirementsAssigningVisitor.cs, src/Framework/Framework/Compilation/ExtensionMethodsCache.cs, src/Framework/Framework/Compilation/Styles/StyleMatcher.cs, src/Framework/Framework/Compilation/Validation/DefaultControlUsageValidator.cs, src/Framework/Framework/Configuration/UserColumnMappingCache.cs, src/Framework/Framework/Controls/CompositeControl.cs, src/Framework/Framework/Controls/DotvvmBindableObjectHelper.cs, src/Framework/Framework/DotVVM.Framework.csproj, src/Framework/Framework/NullableAttributes.cs, src/Framework/Framework/Runtime/AttributeViewModelParameterBinder.cs, src/Framework/Framework/Runtime/Filters/ActionFilterHelper.cs, src/Framework/Framework/Runtime/HotReloadMetadataUpdateHandler.cs, src/Framework/Framework/Utils/ReflectionUtils.cs, src/Framework/Framework/ViewModel/ChildViewModelsCache.cs, src/Framework/Framework/ViewModel/Serialization/DefaultViewModelLoader.cs, src/Framework/Framework/ViewModel/Serialization/ViewModelSerializationMap.cs, src/Framework/Framework/ViewModel/Serialization/ViewModelSerializationMapper.cs, src/Framework/Framework/ViewModel/Serialization/ViewModelTypeMetadataSerializer.cs, src/Samples/Common/Views/ControlSamples/TemplateHost/CompositeControlWithTemplate.cs, src/Tests/Runtime/CapabilityPropertyTests.cs
It's by no means bullet-proof, but it's most likely going to fail in .NET
sooner than in DotVVM, so we are fine.
It enables adding properties to viewmodel and then using them in
a dothtml page. Everything else I tried lead to .NET saying "rude edit"
=> Add net6.0 target and hot reload handler that flushes various caches

src/Framework/Framework/Controls/DotvvmControlCollection.cs
Before the message was only "Unhandled exception occurred while executing page lifecycle event"
Now it includes which event, which control, what exception and the message of the base exception.
=> Improve error reporting on lifecycle event exceptions.

src/Analyzers/Analyzers.Tests/Serializability/ViewModelSerializabilityTest.cs, src/Analyzers/Analyzers/AnalyzerReleases.Unshipped.md, src/Analyzers/Analyzers/DotvvmDiagnosticIds.cs, src/Analyzers/Analyzers/Resources.Designer.cs, src/Analyzers/Analyzers/Resources.resx, src/Analyzers/Analyzers/Serializability/TypeSymbolExtensions.cs, src/Analyzers/Analyzers/Serializability/ViewModelSerializabilityAnalyzer.cs
This PR introduces a couple of fixes and improvements to serializability analyzers.
- Fixed **bug**: nullables were sometimes incorrectly marked as not serializable.
- Fixed **bug**: certain supported types were incorrectly marked as not serializable (`GridViewDataSet<T>`, `UploadedFilesCollection` and `BusinessPackDataSet<T>`). They do not follow our general rules, however their serialization is well-defined and should not issue warnings.
- Fixed **bug**: that caused that some user-defined generic reference types were incorrectly marked as not serializable
- New **improvement**: symbols obtained from a specific `Compilation` within a specific `SemanticModel` are no longer cached indefinitely. Instead, we now construct cache for each `Compilation`. These caches are held using weak …
=> Fixed and improved serializability analyzers

src/Framework/Framework/Compilation/Styles/StyleBuilder.cs, src/Framework/Framework/Compilation/Styles/StyleRepository.cs
A problem occured when Register(typeof(HtmlGenericControl)).SetAttribute("x", "y"),
because the generic type argument is DotvvmBindableObject and not
HtmlGenericControl
=> Fix style registration with variable control type

src/Framework/Hosting.AspNetCore/Security/DefaultCsrfProtector.cs
The Domain flag is not allowed for __Host- cookies, because it
specifies that the cookie should be sent to subdomains.
=> Fix cookies on https: remove the Domain field

src/Framework/Framework/Controls/DotvvmBindableObjectHelper.cs, src/Framework/Framework/Hosting/ErrorPages/ErrorFormatter.cs, src/Framework/Framework/Hosting/ErrorPages/ExceptionAdditionalInfo.cs, src/Framework/Framework/Hosting/ErrorPages/ExceptionSectionFormatter.cs, src/Framework/Framework/Resources/Styles/DotVVM.Internal.css, src/Samples/Common/Controls/ExceptionThrower.cs, src/Samples/Common/DotVVM.Samples.Common.csproj, src/Samples/Common/ViewModels/Errors/ExceptionInLifecycleViewModel.cs, src/Samples/Common/ViewModels/Errors/ExceptionInRenderViewModel.cs, src/Samples/Common/Views/Errors/ExceptionInLifecycle.dothtml, src/Samples/Common/Views/Errors/ExceptionInRender.dothtml, src/Samples/Tests/Abstractions/SamplesRouteUrls.designer.cs, src/Samples/Tests/Tests/ErrorsTests.cs
This comes in quite useful when debugging complex control
hierarchies created in code. This implementation
looks a bit crude, but it works...
=> Put entire control hierarchy into the error page

src/Framework/Framework/Compilation/Parser/Binding/Parser/BindingParser.cs, src/Framework/Framework/Compilation/Parser/Binding/Tokenizer/BindingTokenizer.cs, src/Framework/Framework/Compilation/Parser/Dothtml/Parser/ParserBase.cs, src/Tests/Parser/Binding/BindingParserTests.cs
This PR fixes an issue that breaks the WIP string interpolation feature in VS Extension. 
Whenever an interpolated expression is parsed, we create a new instance of `BindingTokenizer` and `BindingParser`. However, we should also set an appropriate start indices for these expressions.
This is the behaviour I want to achieve:
However, right now it can desynchronize into something like this:
(Note that all interpolations are starting on the first index - which is the data currently generated by framework)
=> Fixed issue with incorrect token `StartPosition` for interpolated expressions

src/Framework/Framework/Compilation/ControlTree/UsedPropertiesFindingVisitor.cs, src/Tests/ControlTests/MarkupControlTests.cs, src/Tests/ControlTests/testoutputs/MarkupControlTests.MarkupControl_PropertyUsedManyTimes.html
Since we introduced the UsedPropertiesFindingVisitor,
it would include a property multiple times if it was used
more than once.
=> Fix a bug in MarkupControl when property is used multiple times

src/Framework/Framework/Binding/HelperNamespace/JsBindingApi.cs, src/Framework/Framework/Resources/Scripts/viewModules/viewModuleManager.ts, src/Tests/ControlTests/SimpleControlTests.cs, src/Tests/ControlTests/testoutputs/SimpleControlTests.NamedCommand.html, src/Tests/ControlTests/testoutputs/ViewModulesServerSideTests.IncludeViewModuleInControl.html
Before it was used as Invoke<Task<X>>, which is pretty ugly.
This patch also adds a check that synchronously invoked command
does not return a promise, otherwise it would probably fail with
some undefined access error.
Checking that an async command actually return a promise is unnecessary,
since await in JS is a no-op
for synchronously evaluated values.
=> Add _js.InvokeAsync method

src/Framework/Framework/Hosting/ErrorPages/ErrorFormatter.cs
This PR adds information about loaded assemblies participating in the execution at the time when an Error Page is generated. I believe that this information can be helpful when diagnosing exceptions from users, such as the following:
* **Missing package**: i.e. trying to use `HotReload` without referencing the proper packages and using framework < 4.0
* **Binary incompatibility**: i.e. `MissingMethodException` when user has incompatible framework and business pack versions
* **Culture issues**: i.e. using a concrete language (culture) that can potentially break some stuff when invoking culture-sensitive operations
=> Added loaded assemblies tab into the Error Page

src/Framework/Framework/Resources/Scripts/utils/evaluator.ts, src/Framework/Framework/Resources/Scripts/validation/error.ts, src/Framework/Framework/Resources/Scripts/validation/validation.ts
This PR adds property paths into `ValidationError` type. It can be easily inspected in console to quickly determine which part of viewModel is being violated. Property path format is consistent with validation changes introduced in 4.0 (absolute paths from root vm and uses slashes instead of knockout expression syntax). See an example:
=> Added property paths to JS validation errors

src/Framework/Framework/Compilation/Binding/TypeConversions.cs, src/Tests/Binding/StaticCommandCompilationTests.cs
This is a regression in staticCommands, it was allowed previously
(I don't really understand why), It occurs only when the
command is declared of type Task<T> instead of Func<Task<T>>,
but people used to do this (in BP TreeView), so this adds the
support back.
=> Fix type conversion from value to Task<Value>.

src/Framework/Framework/Compilation/Parser/Binding/Parser/BindingParser.cs, src/Tests/Parser/Binding/BindingParserTests.cs
This PR adds information about leading whitespace token for interpolated expressions. This information is usually thrown away using `SkipWhiteSpace()` method call. However, for VS Extension this information is important - otherwise having interpolations with leading whitespaces can break syntax highlighting.
=> Do not throw away leading whitespaces when parsing interpolations

src/Framework/Framework/Binding/DotvvmProperty.cs, src/Framework/Framework/Compilation/ControlTree/ControlResolverMetadata.cs, src/Framework/Framework/Compilation/ControlTree/DotvvmPropertyGroup.cs, src/Framework/Framework/Compilation/Styles/ResolvedControlHelper.cs, src/Framework/Framework/ViewModel/IDotvvmViewModel.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolverTests.cs
It's an indication that the deprecated method
of declaring property groups has been used,
so it's better to throw an error informing the user what to do
than just silently ignore the property.
=> Throw an error when an orphaned property group is present

src/Framework/Framework/Controls/ConfigurableHtmlControl.cs, src/Framework/Framework/Controls/HtmlLiteral.cs, src/Tests/ControlTests/DotvvmErrorTests.cs, src/Tests/ControlTests/SimpleControlTests.cs, src/Tests/ControlTests/testoutputs/DotvvmErrorTests.AuthView_InvalidWrapperTagUsage.txt, src/Tests/ControlTests/testoutputs/DotvvmErrorTests.HtmlLiteral_InvalidWrapperTagUsage.txt, src/Tests/ControlTests/testoutputs/DotvvmErrorTests.HtmlLiteral_InvalidWrapperTagUsage2.txt, src/Tests/ControlTests/testoutputs/SimpleControlTests.HtmlLiteral.html, src/Tests/Runtime/RuntimeErrorTests.cs
We added too strict control validator to ConfigurableHtmlControl,
this commit only allows parts of it if it's certain
that the markup will produce a runtime error.
=> Remove breaking change in HtmlLiteral

src/Framework/Framework/Binding/BindingProperties.cs, src/Framework/Framework/Binding/Expressions/StaticCommandBindingExpression.cs, src/Framework/Framework/Compilation/Binding/GeneralBindingPropertyResolvers.cs
it's no longer used, we use StaticCommandOptionsLambdaJavascriptProperty
everywhere now and it's existence is only confusing
some users (@quigamdev)
=> Deprecate StaticCommandJavascriptProperty

src/Directory.Build.props
This PR changes the way we bundle nuget packages by including pdb files. This should enhance debugging experience and also show some more information on error pages.
=> Added pdb files to nuget packages

src/Framework/Framework/Binding/ValueOrBinding.cs, src/Framework/Framework/Binding/ValueOrBindingExtensions.cs, src/Framework/Framework/Binding/VirtualPropertyGroupDictionary.cs, src/Framework/Framework/Compilation/Styles/StyleBuilderMethods.Helpers.cs, src/Framework/Framework/Compilation/Styles/StyleBuilderMethods.cs, src/Framework/Framework/Compilation/Styles/StyleRepository.cs, src/Framework/Framework/Controls/Button.cs, src/Framework/Framework/Controls/ConfirmPostBackHandler.cs, src/Framework/Framework/Controls/DotvvmBindableObjectHelper.cs, src/Framework/Framework/Controls/HtmlGenericControl.cs, src/Framework/Framework/Controls/TextOrContentCapability.cs, src/Tests/ControlTests/CompositeControlTests.cs, src/Tests/ControlTests/ServerSideStyleTests.cs, src/Tests/Runtime/CapabilityPropertyTests.cs
We have decided that it causes more problems than good (ambiguous overloads, ...)
and since C# 9 it's just a matter of putting there `new(X)`
=> remove implicit conversion to ValueOrBinding<T>

src/Framework/Framework/Compilation/ControlTree/ControlResolverMetadataBase.cs
Content from ControlMarkupOptionsAttribute is retrieved before Content and ContentTemplate
=> ControlMarkupOptionsAttribute content retrieval order changed

src/Framework/Framework/Compilation/Javascript/Ast/JsAstHelpers.cs, src/Framework/Framework/Compilation/Javascript/JavascriptTranslationVisitor.cs, src/Framework/Framework/Compilation/Javascript/JsParensFixingVisitor.cs, src/Framework/Framework/Compilation/Javascript/PrimitiveToStringTranslator.cs, src/Tests/Binding/JavascriptCompilationTests.cs, src/Tests/Binding/StaticCommandCompilationTests.cs, src/Tests/ControlTests/SimpleControlTests.cs, src/Tests/ControlTests/testoutputs/CompositeControlTests.WrappedRepeaterControl.html, src/Tests/ControlTests/testoutputs/ServerSideStyleTests.StyleBindingMapping.html, src/Tests/ControlTests/testoutputs/SimpleControlTests.Literal_ClientServerRendering.html, src/Tests/Runtime/ControlTree/ServerSideStyleTests.cs, src/Tests/Runtime/JavascriptCompilation/JsNullChecksTests.cs, src/Tests/Runtime/JavascriptCompilation/JsParensInsersionTests.cs
This results in the null value being replaced by null in .NET
and users expect that to be the case in bindings
translated to JS.
=> js translation: Fix X + Y when X or Y is null

src/Analyzers/Analyzers.Tests/Serializability/ViewModelSerializabilityTest.cs, src/Analyzers/Analyzers/Serializability/ViewModelSerializabilityAnalyzer.cs
This PR introduces some further changes / improvements to DotVVM analyzers.
1. Generic type parameters of viewmodels have been excluded from serializability analysis. It gets a bit more complicated when users define generic viewmodels. It can be implemented in future, but I doubt it is commonly used. Therefore, for now we assume that these are serializable
2. Serializability analysis is not longer run on incomplete type members (nodes with attached compilation errors). Otherwise this could get a bit annoying, for example in the following situation:
- User tries to add a new property to viewmodel and types the following: `public int MyProperty`
- We immediately issue a warning that user should not use fields for storing viewmodel state (notice that field definition is not completed - there …
=> Serializability analysis fix for generics and suppress on compilation errors

src/Framework/Framework/Binding/ValueOrBindingExtensions.cs
Added ValueEquals extension method for ValueOrBinding to
simplify conditions based on the static value.
Also added ValueIsNull and ValueIsNullOrEmpty.
=> ValueOrBinding ValueEquals helper

src/Framework/Framework/Controls/DotvvmBindableObjectHelper.cs
C# compiler preferred the overload with `object?`
parameter to the `ValueOrBinding<T>` overload...
I also added a ValueOrBinding unwrap to the AddAttribute(object),
to handle the cases when the boxed argument is
ValueOrBinding anyway.
=> Fix AddAttribute when used with non-nullable ValueOrBinding

src/Framework/Framework/Compilation/Styles/ResolvedControlHelper.cs, src/Framework/Framework/Compilation/Styles/StyleBuilderMethods.Helpers.cs, src/Framework/Framework/Compilation/Styles/StyleMatchContextMethods.cs
* type signatures of styles.Append, Replace, Prepend with the lambda function was broken and essentially could not be used
* Replace didn't work on controls which don't allow children. We call SetContent with an empty array there, so I added a check that if the array is empty we do nothing
* Added overload of `StyleMatchContext.Property(x => x.Prop)` for cases when Prop is `IValueBinding`. Then it does not make sense to wrap it in the ValueOrBinding and returning the IValueBinding directly is better
=> styles: Fix some gitches

src/Framework/Framework/Compilation/ControlTree/DataContextStack.cs, src/Framework/Framework/Compilation/ControlTree/Resolved/ResolvedBinding.cs
The SelectMany call seems to cause null reference exception
on .NET Framework. I have no idea why, but this could fix it.
=> Probably fix magic null reference exception

src/Framework/Framework/Controls/HtmlWriter.cs, src/Tests/Runtime/HtmlWriterTests.cs
We write out self-closing tags only partially to avoid having <img></img>
which is invalid in HTML. However, there was a missing check
that the begin tag is fully written out when we are starting another
tag
=> HtmlWriter: Fix self closing tags which actually have children

src/Framework/Framework/Controls/Infrastructure/MarkupControlContainer.cs
This control cannot be used from markup, by moving it to the
DotVVM.Framework.Controls.Infrastructure namespace.
=> Move MarkupControlContainer to Infrastructure namespace

src/Framework/Framework/Compilation/HtmlAttributeValueMerger.cs
When you have a long chain of .AddAttribute(...),
the stacktrace won't tell you much, so we'll just include the name of the
attribute in the error message.
=> Improve error message in html attribute merging

src/Framework/Framework/Compilation/Binding/MethodGroupExpression.cs, src/Framework/Framework/Compilation/Binding/StaticClassIdentifier.cs, src/Framework/Framework/Compilation/Binding/UnknownStaticClassIdentifierExpression.cs, src/Tests/Binding/StaticCommandCompilationTests.cs
It used to produce something like "must be reducible node",
which is really unhelpful. Now it will be something like
"Method X was not found"
=> Fix error message when a method in binding does not exist

src/Framework/Framework/Binding/VirtualPropertyGroupDictionary.cs
It was removing properties while it was iterating through
the dictionary :|
=> Fix VirtualPropertyGroupDictionary.Clear

src/Framework/Framework/Binding/ActiveDotvvmProperty.cs
In case click was null, `control.SetProperty(Events.ClickProperty, click);` resulted in Exception, but rather property should not be set.
=> ActiveDotvvmProperty support for null command binding added

src/Framework/Framework/Compilation/CompiledAssemblyCache.cs
We were getting "The invoked member is not supported in a dynamic assembly." exception.
=> Dynamic assemblies excluded from traversing on OWIN

ci/scripts/publish.ps1, src/Directory.Build.props, src/Tests/DotVVM.Framework.Tests.csproj
Sets up Source link based on instructions from https://github.com/dotnet/sourcelink.
Also embeds the PDBs in the symbol package (including all C# sources) instead of the main package. (Visual Studio IMO just ignored them anyway because of the missing SourceLink package.) This makes the main package smaller by ~800 KB.
I tested it locally but I'll test it on our internal feed as well.
=> Set up source link

src/Tools/CommandLine/DotVVM.CommandLine.csproj, src/Tools/CommandLine/DotVVM.CommandLine.nuspec, src/Tools/Compiler/DotVVM.Compiler.csproj
Turns out that the `DotVVM.CommandLine` package did not contain the `DotVVVM.Compiler` dlls, which are required for the `dotvvm lint` command to work. (Honestly, I'm not even able to find a version that ever contained them.) Anyway, this PR addresses this bug.
=> Fix DotVVM.CommandLine packaging

src/Analyzers/Analyzers.Package/DotVVM.Analyzers.Package.csproj, src/Framework/Framework/DotVVM.Framework.csproj
Adds a Analyzers.Package project reference to Framework with `ReferenceOutputAssembly=false`. This causes Analyzers.Package to be transitively built instead of it being assumed that it is has already been built.
=> Fix Analyzers.Package build

src/Framework/Framework/Compilation/DefaultControlBuilderFactory.cs, src/Framework/Framework/Compilation/DotvvmViewCompilationService.cs, src/Framework/Framework/Compilation/IDotvvmViewCompilationService.cs, src/Framework/Hosting.AspNetCore/DotVVM.Framework.Hosting.AspNetCore.csproj, src/Framework/Hosting.AspNetCore/Hosting/DotvvmHealthCheck.cs, src/Framework/Hosting.AspNetCore/ServiceCollectionExtensions.cs, src/Samples/AspNetCoreLatest/Startup.cs
The healthcheck just checks if dotvvm pages can be compiled.
resolves #1205
=> Add IHeathCheck implementation to Asp.Net Core hosting

src/Framework/Framework/Binding/DotvvmCapabilityProperty.cs
CompositeControl automatically infers if a property
should be mapped to an attribute or to a inner element
from the property type. It used to check if the type is
assignable to DotvvmBindableObject, which didn't work
with control interfaces.
=> Allow control interfaces in composite control properties

src/Framework/Framework/Compilation/HtmlAttributeValueMerger.cs, src/Framework/Framework/Compilation/Javascript/JsParensFixingVisitor.cs, src/Framework/Framework/Compilation/Javascript/ParametrizedCode.cs, src/Framework/Framework/Controls/DotvvmControl.cs, src/Framework/Framework/Controls/HtmlGenericControl.cs, src/Tests/Binding/JavascriptCompilationTests.cs, src/Tests/ControlTests/CompositeControlTests.cs, src/Tests/ControlTests/testoutputs/CompositeControlTests.ControlWithMultipleEnumClasses.html, src/Tests/Runtime/JavascriptCompilation/JsParensInsersionTests.cs
Since it's nearly impossible to concatenate two bindings or
a binding and a constant value, this patch adds support for a list
of binding or values directly to HtmlGenericControl.AddAttributesToRender
I added AttributeList, a special linked list for this use case. The reason is
that we need to append efficiently in the MergePlainValues method
(or prepend, that doesn't matter). It's also far more efficient to typecheck
for sealed class than an generic interface like `IEnumerable<T>`
(the typecheck will be done for each value in HtmlGenericControl)
In order to generate reasonable code, I needed to fix some bugs in
OperatorPrecdence:
* distinguish between no parens needed ever (0) and sequence expression (1)
- for this reason, all values were shifted by one. And I made constants
* some …
=> Allow multiple AddClass() even when some contain binding

src/Framework/Framework/Compilation/Parser/Dothtml/Tokenizer/DothtmlTokenizer.cs, src/Tests/ControlTests/MarkupControlTests.cs, src/Tests/Parser/Dothtml/DothtmlParserTests.cs
This PR fixes and issue with parsing interpolated strings. Right now the behaviour is broken in the following way:
* Consider an expression `$'Hello {$'Innner {'Another interpolation'}'}'`
* It would be parsed similar to the following:
* `$'Hello {$'Innner {'Another interpolation'`
* `}'}'`
This can be observed using Visual Studio Extension - artifacts will be completely broken
=> Fixed an issue with parsing interpolated strings using dothtml tokenizer

src/Framework/JsComponent.React/dotvvm-react.tsx, src/Samples/Common/Scripts/react/react-app.tsx, src/Samples/Common/Scripts/svelte/KnockoutTemplateSvelteComponent.svelte, src/Samples/Common/Scripts/svelte/TemplateSelector.svelte, src/Samples/Common/Scripts/svelte/svelte-app.ts, src/Samples/Common/Views/FeatureSamples/JsComponentIntegration/SvelteComponentIntegration.dothtml
The implementation and API of KnockoutTemplateSvelteComponent
is mostly similar to the corresponding React component.
=> Svelte bridge: support hosting knockout templates

src/Framework/Framework/Hosting/Middlewares/DotvvmFileUploadMiddleware.cs, src/Framework/Framework/Utils/ExpressionUtils.cs, src/Framework/Framework/Utils/FunctionalExtensions.cs, src/Framework/Framework/ViewModel/Serialization/ViewModelJsonConverter.cs, src/Framework/Framework/ViewModel/Serialization/ViewModelPropertyMap.cs, src/Framework/Framework/ViewModel/Serialization/ViewModelSerializationMap.cs, src/Framework/Framework/ViewModel/Serialization/ViewModelSerializationMapper.cs, src/Framework/Testing/DotvvmTestHelper.cs, src/Tests/ViewModel/SerializerTests.cs
the serializer now supports injecting parameters into the constructor.
Instead of writing data directly into the properties, we
now first deserialize all properties into local variables
and then either call setters or use them as constructor parameters.
=> Serialize records correctly

src/Framework/Framework/Compilation/Parser/Binding/Tokenizer/BindingTokenizer.cs, src/Tests/Binding/BindingCompilationTests.cs, src/Tests/Parser/Binding/BindingParserTests.cs, src/Tests/Parser/Binding/BindingTokenizerTests.cs
This PR fixes a small bug due to which it was unable to compile expressions such as the following: `MyBoolProperty=!OtherBoolProperty`. Users received an error that the operator `=!` does not exist / is not supported.
=> Fixed unary operator parsing precedence

src/Framework/Framework/Resources/Scripts/tests/observableHierarchies.ts, src/Framework/Framework/Resources/Scripts/tests/serialization.test.ts, src/Framework/Framework/Resources/Scripts/tests/validation.test.ts, src/Framework/Framework/Resources/Scripts/utils/evaluator.ts, src/Framework/Framework/Resources/Scripts/validation/error.ts, src/Framework/Framework/Resources/Scripts/validation/validation.ts
The new API has 2 new functions:
* `dotvvm.validation.addErrors([{ errorMessage: "Test", propertyPath: "/X/Y/Z" }])`
* `dotvvm.validation.removeErrors("/FirstName", "/LastName")`
=> Add JS API for modifying the client-side error collection

src/Framework/Framework/Binding/DotvvmCapabilityProperty.cs
When a capability with `level:` prefix is registered, we will look
for a field `Level_TheCapability` instead of `level_TheCapability`
=> Capability backing field is expected to be in pascal case

src/Framework/Framework/ViewModel/Serialization/ViewModelSerializationMap.cs
This PR fixes failing tests on CI. It seems like the following is not supported on .NET Framework:
* Calling `Zip` using an empty collection
* This issue occurred when generating serialization maps for viewmodels that do not define any properties
* Creating an empty `Expression.Block`
This issue affects only 4.1 and is not present in 4.0.3
=> Fixed codegen for serialization maps on .NET Framework

src/Framework/Framework/Binding/DotvvmBindingCacheHelper.cs, src/Framework/Framework/Binding/Expressions/StaticCommandBindingExpression.cs
Note that I'm not adding helpers for compiling new
command and resource bindings,
because they are better created from Func<...>, since they
are only evaluated compile-time.
=> Add helpers for compiling custom `value` and `staticCommand` bindings

src/Framework/Framework/Compilation/Javascript/JavascriptTranslatableMethodCollection.cs, src/Framework/Framework/Utils/ReflectionUtils.cs
Problem was that we removed the ToEnumString(T?) overload,
this adds it back
(it's not extension method on purpose to avoid ambiguity)
It should fix the failing tests in main
=> Fix implicit ToEnumString on nullable enum

src/Framework/Framework/ViewModel/Serialization/EncryptedValuesReader.cs, src/Framework/Framework/ViewModel/Serialization/EncryptedValuesWriter.cs, src/Tests/ViewModel/SerializerTests.cs
This caused a problem when Dictionary<,> was serialized,
since Newtonsoft.Json serializes it as object by default, but we excepted
it to be the Key/Value array when deserializing.
Resolves  #1379
=> Encrypted values serialization should use our default settings

src/Analyzers/Analyzers.Tests/DotVVM.Analyzers.Tests.csproj, src/Tests/DotVVM.Framework.Tests.csproj
Now that we merged the new `GitHubActionsTestLogger` test results reporting is failing. This PR updates NuGet packages versions for unit testing projects
=> Fixed tests on CI

src/Framework/Framework/Controls/DotvvmControlCollection.cs, src/Framework/Framework/Controls/HierarchyRepeater.cs, src/Framework/Framework/Controls/Repeater.cs, src/Tests/ControlTests/CompositeControlTests.cs, src/Tests/ControlTests/testoutputs/CompositeControlTests.WrappedHierarchyRepeaterControlWithGeneratedIds.html, src/Tests/ControlTests/testoutputs/CompositeControlTests.WrappedRepeaterControlWithGeneratedIds.html
Usually it's not super important if the container control is rooted or not,
but when the DelegateTemplate contains some user code which calls
GetDotvvmUniqueId (or similar), it will fail in weird ways (the ids will be
generated but won't be unique). For components used only from markup,
this really does not matter, but Repeater is being used as a base component
for many composite controls.
Similar change is made in HierarchyRepeater, where few fixes were needed to make the ids actually unique.
Plus one slight change was made to make repeater generate the same ids client-side and server-side.
=> Repeater calls templates with rooted parent

src/Framework/Framework/Compilation/ControlTree/Resolved/ResolvedControl.cs, src/Framework/Framework/Compilation/Styles/StyleBuilderMethods.Helpers.cs, src/Framework/Framework/Compilation/Styles/StyleTreeShufflingVisitor.cs, src/Framework/Framework/Controls/Styles.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/DefaultControlTreeResolverTests.cs, src/Tests/Runtime/ControlTree/ServerSideStyleTests.cs, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json
=> Make it possible to remove controls using server-side styles

src/Framework/Framework/Binding/HelperNamespace/Enums.cs, src/Framework/Framework/Compilation/Binding/TypeConversions.cs, src/Framework/Framework/Compilation/Javascript/JavascriptTranslatableMethodCollection.cs, src/Framework/Framework/Utils/ReflectionUtils.cs
This PR moves the `ToEnumString` JS translation into the common binding helper namespace
=> Moved `ToEnumString` JS translation into binding helper namespace

src/Framework/Framework/Compilation/ControlTree/DotvvmPropertyGroup.cs, src/Framework/Framework/Controls/HtmlGenericControl.cs, src/Tests/ControlTests/CompositeControlTests.cs, src/Tests/ControlTests/testoutputs/CompositeControlTests.AttributeComparisonsAreCaseInsensitive.html
Use OrdinalIgnoreCase comparer for all PropertyGroups - in general most things
in dothtml is case insensitive, all of our uses for property groups are
case insensitive. I think it's not worth it to add another config option.
resolves #1395
=> Use case insensitive comparisons for attributes

src/Framework/Framework/Controls/DotvvmControlCollection.cs
The error now includes both of the related controls in properties,
and both control types are also mentioned in the error message.
=> Improve the Control used in another parent error

src/Framework/Framework/Configuration/DefaultSerializerSettingsProvider.cs
This PR adds `MaxDepth` both to global Newtonsoft settings and also to DotVVM's `DefaultSerializerSettingsProvider`. We are using the same default as Newtonsoft. See: https://github.com/JamesNK/Newtonsoft.Json/blob/94ff24f815a777269920f5a7b13f60db50c5eeb7/Src/Newtonsoft.Json/JsonReader.cs#L332
=> Added `MaxDepth` to default serialization settings

src/Framework/Framework/Resources/Scripts/DotVVM.Debug.js
When error occured in postback, we used to set the html into
innerHtml, which does not run the javascript that powers the Save&Share
button and the Cookies tab.
I changed it to use iframe src={blob URL} which
actually allows Javascript.
=> error page: Fix JS when in the DotVVM.Debug iframe

src/Framework/Framework/Diagnostics/DiagnosticsStartupTracer.cs, src/Framework/Framework/Diagnostics/Models/DiagnosticsInformation.cs, src/Framework/Framework/Diagnostics/Models/EventTiming.cs, src/Framework/Framework/Hosting/StartupTracingConstants.cs, src/Framework/Framework/Utils/ConcurrencyUtils.cs
hopefully without adding new ones...
the main point is the replacement of List with ImmutableList,
which is safe to read even when some other thread
is still reporting events
=> Fix race conditions in startup tracer

src/Framework/Testing/DotVVM.Framework.Testing.csproj, src/Tests/Binding/ExpressionHelperTests.cs, src/Tests/DotVVM.Framework.Tests.csproj, src/Tests/ViewModel/SerializerTests.cs
This PR adds the possibility to run tests also on .NET Framework. Over the past few months, there have been a couple of issues manifesting only on .NET Framework. Therefore, we should always run unit tests also on .NET Framework as it seems to have discovered multiple issues (see the tests report).
- This change should not affect people on Linux/Mac as we are using conditional `TargetFrameworks`
- It also works on CI (`windows-2022` run has two reporting platforms - `net6` and `net472`)
Failing tests on .NET Framework will be fixed within a separate PR
=> Added support for running unit tests on .NET Framework

src/Framework/Framework/Compilation/Styles/StyleTreeShufflingVisitor.cs, src/Framework/Framework/DotVVM.Framework.csproj, src/Framework/Framework/Hosting/VisualStudioHelper.cs, src/Framework/Framework/Utils/ReflectionUtils.cs, src/Framework/Testing/TestEnvironmentHelper.cs, src/Tests/Binding/ExpressionHelperTests.cs, src/Tests/Binding/JavascriptCompilationTests.cs, src/Tests/Binding/NullPropagationTests.cs, src/Tests/DotVVM.Framework.Tests.csproj, src/Tests/Runtime/ConfigurationSerializationTests.cs, src/Tests/Runtime/LruCacheTests.cs, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.Markup.json, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json, src/Tests/ViewModel/ViewModelTypeMetadataSerializerTests.cs
This PR fixes bugs uncovered by running our unit tests also on .NET Framework.
#1424 should be merged first
=> Fixed a couple of bugs for `net472` framework build

src/Framework/Framework/Utils/JsonUtils.cs, src/Tests/CultureUtils.cs, src/Tests/Routing/DotvvmRouteTests.cs, src/Tests/ViewModel/ViewModelTypeMetadataSerializerTests.cs
Some tests were crashing when executed from Visual Studio as they were changing the culture and not changing it back.
Another test was crashing if the `JsonConvert.DefaultSettings` were set before the test is run - I don't know why but I've fixed error handling there.
=> Fixed culture issues and random crashes in unit tests

src/Framework/Framework/Compilation/Parser/Dothtml/Parser/DothtmlLiteralNode.cs, src/Framework/Framework/Compilation/Parser/Dothtml/Parser/DothtmlParser.cs, src/Tests/ControlTests/SimpleControlTests.cs, src/Tests/ControlTests/testoutputs/SimpleControlTests.CurlyBraceEscaping.raw.html, src/Tests/ControlTests/testoutputs/SimpleControlTests.CurlyBraceEscaping.reparsed.html, src/Tests/Parser/Dothtml/DothtmlParserTests.cs
We used to both include the `<![CDATA[` string and
encode the literal. Now it removes the CDATA prefix and suffix,
and HTML encodes the string in between.
=> parser: fix CDATA parsing

src/Framework/Framework/Compilation/ControlTree/UsedPropertiesFindingVisitor.cs, src/Framework/Framework/Compilation/Javascript/JavascriptTranslatableMethodCollection.cs, src/Framework/Framework/Controls/DotvvmMarkupControl.cs, src/Tests/ControlTests/MarkupControlTests.cs, src/Tests/ControlTests/testoutputs/MarkupControlTests.MarkupControl_InternalProperty.html, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json
If the property group is used in the markup,
it will be serialized among the other control properties as a dictionary.
This approach should allow any operations on the dictionary.
The main use case is for passing all the properties into a JS function
=> markup control: Basic support for property groups

src/Framework/Framework/Binding/DotvvmCapabilityProperty.cs, src/Framework/Framework/Binding/DotvvmProperty.cs, src/Framework/Framework/Binding/GroupedDotvvmProperty.cs, src/Framework/Framework/Compilation/ControlTree/ControlTreeResolverBase.cs, src/Framework/Framework/Compilation/ControlTree/DotvvmPropertyGroup.cs, src/Framework/Framework/Compilation/ControlTree/IControlResolverMetadata.cs, src/Framework/Framework/Compilation/ControlTree/IPropertyDescriptor.cs, src/Framework/Framework/Compilation/ControlTree/ITypeDescriptor.cs, src/Framework/Framework/Compilation/ControlTree/Resolved/ResolvedTypeDescriptor.cs, src/Framework/Framework/Compilation/IControlAttributeDescriptor.cs, src/Framework/Framework/Utils/StringSimilarity.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/DefaultControlTreeResolverTests.cs, src/Tests/Runtime/DotvvmControlErrorsTests.cs, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json
We have this warning at runtime, so people can see it in the dev console,
or in ASP.NET Core logs. With this change, the error should be also
displayed in VS Extension (we currently don't display warnings with DotVVM itself)
=> Compile time warning for uppercase atrributes (i.e. mistyped properties)

src/Framework/Framework/Hosting/Middlewares/DotvvmReturnedFileMiddleware.cs
I have no idea why, but seems that Chrome sends site = none in some cases.
The point here was to disallow cross-origin usage of the
returned files, which you hopefully can't do
without sending `Sec-Fetch-Site: cross-site`.
The spec says the following about Sec-Fetch-Site: none
> This request is a user-originated operation. For example: entering a URL into the address bar, opening a bookmark, or dragging-and-dropping a file into the browser window.
I doubt anyone did enter the URL manually, so this just a workaround for
a Chrome bug.
I don't think it allows any potential attacks,
and anyway, we can allow users copying the file URL into a different browser
=> Allow Sec-Fetch-Site=none in returned files

src/Framework/Framework/Resources/Scripts/serialization/date.ts, src/Framework/Framework/Resources/Scripts/tests/date.test.ts, src/Framework/Framework/tsconfig.json
This solves #1438.
Previously when user was in the middle of filling in a date the resulting date was very unpredictable.
This was because `Date` object created `dateParse` auto-corrected to some date values in unexpected ways.
Having `Date` object limitations in mind this PR aims to make resulting date object more predictable in these corner cases.
=> More predictable dateParse

src/Framework/Framework/Compilation/CompiledAssemblyCache.cs, src/Framework/Framework/Compilation/ControlTree/ControlResolverBase.cs, src/Framework/Framework/Compilation/ControlTree/ControlResolverMetadataBase.cs, src/Framework/Framework/Compilation/ControlTree/DefaultControlResolver.cs, src/Framework/Framework/Compilation/Directives/BaseTypeDirectiveCompiler.cs, src/Framework/Framework/Controls/ControlMarkupOptionsAttribute.cs, src/Framework/Framework/Controls/ControlPrecompilationMode.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/ControlWithOverriddenRules.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/DefaultControlTreeResolverTests.cs
I've added an option to specify aliases for controls in markup. 
We'll need this in the AutoUI package where we want the control in markup would be named `auto:Editor`, but the underlying class name would be `AutoEditor`.
I've added the `PrimaryName` property in the `ControlMarkupOptions` - this will be important for the VS extension as this should be the name that the extension will suggest in IntelliSense. If this property is not specified, the primary name would be the name of the control class (current behavior).
Also, I've added the `AlternativeName` collection which allows specifying other aliases. This can be used for renaming controls.
=> Added support for primary names and alternative names for controls

src/Framework/Framework/Resources/Scripts/binding-handlers/SSR-foreach.ts, src/Samples/Common/DotVVM.Samples.Common.csproj, src/Samples/Common/ViewModels/FeatureSamples/RenderSettingsModeServer/RepeaterCollectionSetToNullViewModel.cs, src/Samples/Common/Views/FeatureSamples/RenderSettingsModeServer/RepeaterCollectionExchange.dothtml, src/Samples/Common/Views/FeatureSamples/RenderSettingsModeServer/RepeaterCollectionSetToNull.dothtml, src/Samples/Tests/Abstractions/SamplesRouteUrls.designer.cs, src/Samples/Tests/Tests/Feature/RenderSettingsModeServerTest.cs
When a collection in the viewmodel was set to null, and there was a server-side rendered control bound to it, it was throwing an error in the `dotvvm-SSR-foreach` binding handler.
I've added a check for this situation and also added UI tests.
=> Fixed bug in RenderSettings.Mode=Server when a collection is set to null value

src/Framework/Framework/Binding/ControlPropertyBindingDataContextChangeAttribute.cs, src/Framework/Framework/Compilation/ControlTree/ControlTreeHelper.cs, src/Framework/Framework/Compilation/ControlTree/ControlTreeResolverBase.cs, src/Framework/Framework/Compilation/ControlTree/ITypeDescriptor.cs, src/Framework/Framework/Compilation/ControlTree/Resolved/ResolvedTypeDescriptor.cs, src/Framework/Framework/Compilation/Validation/DefaultControlUsageValidator.cs, src/Framework/Framework/Compilation/ViewCompiler/DefaultViewCompilerCodeEmitter.cs, src/Framework/Framework/Controls/CloneTemplate.cs, src/Framework/Framework/Controls/TextOrContentCapability.cs, src/Tests/ControlTests/CompositeControlTests.cs, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.Markup.json, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.RestAPI.json
Also improves the error messages when property type is not suported + a test that it works automatically (without MarkupOption) in CompositeControl.
=> Add support for IEnumerable<T> in control properties

src/Framework/Framework/Binding/DotvvmCapabilityProperty.cs, src/Framework/Framework/Binding/ValueOrBinding.cs, src/Framework/Framework/Binding/VirtualPropertyGroupDictionary.cs, src/Framework/Framework/Controls/DotvvmBindableObjectHelper.CapabilityCache.cs, src/Framework/Framework/Controls/DotvvmBindableObjectHelper.cs, src/Framework/Framework/Controls/HtmlGenericControl.cs, src/Framework/Framework/Controls/IControlWithHtmlAttributes.cs, src/Tests/ControlTests/CompositeControlTests.cs, src/Tests/ControlTests/testoutputs/CompositeControlTests.ClassBindingControl.html
Some not very nice code has to be used in Fluent UI and BS5 for this,
so it would be nice to have this helper.
In order for AddCssClass to work with any html control, not only
HtmlGenericControl, generic mechanism for handling property
groups from capabilies was introduced
- see DotvvmCapabilityProperty.FindProperty
- and see DotvvmBindableObjectHelper.CapabilityCache.cs
the FindProperty can lookup any property from a specified capability.
The CapabilityCache makes it reasonably fast specifically for
HtmlCapability
=> Add AddCssClass and AddCssStyle extension methods for ValueOrBinding

src/Tools/CommandLine/DotVVM.CommandLine.csproj, src/Tools/CommandLine/DotVVM.CommandLine.nuspec
This PR fixes releasing of CommandLine. The fix is already present in recent builds of `release/4.0` but was missing in `main` and `release/4.1`.
=> Fixed CommandLine publishing on CI

src/Framework/Framework/Hosting/DotvvmRequestContext.cs, src/Framework/Framework/Hosting/HostingConstants.cs, src/Framework/Hosting.AspNetCore/Hosting/AspNetCoreDotvvmRequestContextExtensions.cs, src/Framework/Hosting.AspNetCore/Hosting/Middlewares/DotvvmMiddleware.cs, src/Framework/Hosting.Owin/Hosting/Middlewares/DotvvmMiddleware.cs, src/Framework/Hosting.Owin/Hosting/OwinDotvvmRequestContextExtensions.cs
We already had this method implemented for OWIN but not for ASP.NET Core.
Also, I have removed the word `Owin` from the `DotvvmRequestContextOwinKey` as it was used in ASP.NET Core version too.
=> Added missing GetDotvvmContext method for ASP.NET Core

src/Framework/Framework/Compilation/Javascript/JavascriptTranslator.cs, src/Framework/Framework/Compilation/Javascript/JsViewModelPropertyAdjuster.cs, src/Framework/Framework/Compilation/Javascript/KnockoutObservableHandlingVisitor.cs, src/Framework/Framework/Controls/HierarchyRepeater.cs, src/Tests/Binding/JavascriptCompilationTests.cs, src/Tests/ControlTests/HierarchyRepeaterTests.cs, src/Tests/ControlTests/testoutputs/HierarchyRepeaterTests.UsageWithThisInBindings.html, src/Tests/ControlTests/testoutputs/MarkupControlTests.MarkupControl_PassingStaticCommand.html
Lack of this feature caused problems in BP, where {value: _this} translated to something using $context, instead
of using the ViewModelSymbolicParameter,
which is easier to process
=> Add support for $rawData to ViewModelSymbolicParameter

src/Framework/Framework/Binding/DotvvmCapabilityProperty.cs, src/Framework/Framework/Controls/HtmlGenericControl.cs, src/Framework/Framework/Controls/TextOrContentCapability.cs, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json
I've added XML comments to builtin capabilities so they show up in the docs.
Also, I have updated the default mapping mode for properties of type control, collection of controls, or template. The user can override the default by placing his own `MarkupOptionsAttribute`.
=> Improvements of control property metadata for docs

src/Tools/HotReload/AspNetCore/Scripts/dotvvm.hotreload.js, src/Tools/HotReload/Owin/Scripts/dotvvm.hotreload.js
We can't use dotvvm.log there, because dotvvm might not be loaded.
=> Fix console.log in hot reaload

src/Framework/JsComponent.React/dotvvm-react.tsx, src/Framework/JsComponent.React/package-lock.json, src/Framework/JsComponent.React/package.json, src/Framework/JsComponent.React/tsconfig.json
Since React does not have any standard way of writing values back, it does not make sense to attempt any automagic solution. This simply allows developers to handle the changes themselves
If a property called `setProps` is used, it has precedence, so then it's not possible to update it
=> Pass setProps function to React components

src/Framework/Framework/Resources/Scripts/utils/logging.ts
The methods console.log/warn/error already have appropriate coloring in browser's console and doesn't need overriding. Current implementation creates log entries such as this:
=> Remove colors handed to console.log as arguments

src/Framework/Framework/Resources/Scripts/tests/validation.test.ts, src/Framework/Framework/Resources/Scripts/validation/validation.ts
This PR is cherry-picking important bugfix from #1498. Right now, when attaching errors on an non-existing object, the function throws. Therefore, we never trigger the `validationErrorsChanged` event. At the end even valid errors are not displayed.
Users can encounter this issue in the following ways:
* Manually specifying incorrect property paths using our string notation
* Providing correct expression or correct property path but the viewmodel changes (i.e. the property where we need to attach errors is no longer reachable from root viewmodel)
=> Fixed issue with not attaching errors when propertyPaths could not be resolved

src/Framework/Framework/Routing/UrlHelper.cs, src/Tests/Routing/UrlHelperTests.cs
This PR brings in bugfix first introduced by #1498. I did following changes:
* Parameters with `null` values are skipped
* Parameters with values equal to `string.Empty` are rendered without the `=` sign
=> Fixed building query parameters in URL suffixes

src/Framework/Framework/ViewModel/Serialization/ViewModelSerializationMap.cs
Turns out people register viewmodels as services into DI, so our heuristic for "better" error handling breaks code.
=> Fix deserialization when a viewmodel is also a service

src/Framework/Framework/Binding/ControlPropertyBindingDataContextChangeAttribute.cs
This PR improves error message when user does something weird with data contexts. Example:
```csharp
public class CollectionIndexViewModel : DotvvmViewModelBase
{
public List<int> Collection { get; set; } = Enumerable.Range(0, 4).ToList();
public SomeOtherType Property { get; set; }
}
```
```html
<div class="container" DataContext="{value: Property}">
<dot:Repeater DataSource="{value: Collection}" RenderSettings.Mode="Client">
...
</dot:Repeater>
</div>
```
>Could not compute the type of DataContext: System.Exception: The 'DataSource' property contains invalid data-binding
>Could not compute the type of DataContext: System.Exception: The 'DataSource' property contains invalid data-binding. Binding '{value: Collection}' could not be constructed on DataContext 'TestNamespace.SomeOtherType'
=> Improved error message on DataContext mismatch

src/Framework/Framework/Hosting/DotvvmPresenter.cs, src/Framework/Framework/ViewModel/Serialization/DefaultViewModelSerializer.cs, src/Framework/Framework/ViewModel/Serialization/IViewModelSerializer.cs, src/Framework/Framework/ViewModel/Serialization/IViewModelTypeMetadataSerializer.cs, src/Framework/Framework/ViewModel/Serialization/ViewModelTypeMetadataSerializer.cs
We ignored the knownTypeMetadata field sent
by the client and always sent back all the types.
=> Fix handling of known type metadata in static commands

src/Framework/Framework/Controls/CheckBox.cs, src/Samples/Common/Views/ControlSamples/CheckBox/Indeterminate.dothtml, src/Samples/Tests/Tests/Control/CheckBoxTests.cs, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json
resolves #862
The syntax is `<dot;CheckBox DisableIndeterminate`, the property is only valid when the checkbox is used in boolean mode, not collection mode. It's not AllowIndeterminate, because then you'd
have to type the `=false`, since we don't want to
make it a default option.
=> Option to disable checkbox indeterminate mode

src/Framework/Framework/Compilation/ControlTree/Resolved/ResolvedTypeDescriptor.cs, src/Framework/Framework/Controls/Styles.cs, src/Framework/Framework/Hosting/AssemblySerializableList.cs, src/Framework/Framework/Hosting/DotvvmPresenter.cs, src/Framework/Framework/Hosting/DotvvmPropertySerializableList.cs, src/Framework/Framework/Hosting/ErrorPages/ErrorPageTemplate.cs, src/Framework/Framework/Hosting/VisualStudioHelper.cs, src/Framework/Framework/ResourceManagement/ReflectionAssemblyJsonConverter.cs, src/Tests/Runtime/ConfigurationSerializationTests.cs, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.Markup.json, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.RestAPI.json, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json
I was considering moving the list of properties into each control,
but that would exclude attached properties from the list
resolves #1431
=> Include a list of controls in the serialized config

src/Framework/Framework/Runtime/CommandTaskSequenceHelper.cs, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json
CommandTaskSequenceHelper is used when you use `;` operator in a command binding. We used to chain the tasks using ContinueWith which (counterintuitively) continues even exception occurs. So when you called a `method1(); ...` it would silence exceptions from method1.
=> Fix CommandTaskSequenceChaner when exception occurs

src/Framework/Framework/Resources/Scripts/DotVVM.Globalize.ts, src/Framework/Framework/Resources/Scripts/binding-handlers/textbox-text.ts, src/Framework/Framework/Resources/Scripts/metadata/primitiveTypes.ts, src/Framework/Framework/Resources/Scripts/serialization/date.ts, src/Framework/Framework/Resources/Scripts/serialization/deserialize.ts, src/Framework/Framework/Resources/Scripts/tests/date.test.ts, src/Framework/Framework/Resources/Scripts/tests/serialization.fastcheck.test.ts, src/Framework/Framework/Resources/Scripts/tests/serialization.test.ts, src/Framework/Framework/Resources/Scripts/typings/globalize/globalize.d.ts, src/Framework/Framework/package.json, src/Samples/Common/Views/FeatureSamples/JavascriptTranslation/DateTimeTranslations.dothtml
This avoids some known problems:
* setting year after setting setting day leads to problems on lap years
* datetimeoffset parsing didn't use setFullYear, so year<100 was parsed as year 19__
Using Date.parse shouldn't bring new issues,
we had an assert that it behaves same in the fastcheck test for some time.
Maybe the hack with Sweden is questionable  (:
=> Use JS standard library for date parsing and formatting

src/Framework/Framework/Compilation/Binding/MemberExpressionFactory.cs, src/Tests/Binding/ExpressionHelperTests.cs, src/Tests/Binding/StaticCommandCompilationTests.cs
We didn't pass bindingFlags to the GetAllMembers method :|
This bug was probably introduced in 4.0, but the fix will break any code depending on the behavior. However, I think it's quite unlikely many people would use private properties, since the serializer would ignore them.
=> MemberExpressionFactory filters out private members

src/Samples/Common/Views/ControlSamples/ListBox/ListBox.dothtml, src/Samples/Common/Views/FeatureSamples/Api/ApiRefresh.dothtml, src/Samples/Tests/Tests/Control/ListBoxTests.cs
Firefox cannot scroll in the ListBox, so I increased its size.
It doesn't set focus to input when it tabs out from the page.
=> Fixed UI tests in Firefox

src/Framework/Framework/Binding/DotvvmCapabilityProperty.cs, src/Framework/Framework/Controls/MarkupOptionsAttribute.cs, src/Tests/Runtime/CompositeControlPropertyRegistrationTests.cs
Added internal nullable field to each MarkupOptions property, so
we can distinguish if the user used the property explicitly or
it only contains the default value.
=> CompositeControl: merge MarkupOption attribute with implicit metadata

src/Framework/Framework/Resources/Scripts/global-declarations.ts, src/Framework/Framework/Resources/Scripts/postback/postbackCore.ts, src/Framework/Framework/Resources/Scripts/serialization/deserialize.ts, src/Framework/Framework/Resources/Scripts/tests/postback.test.ts, src/Framework/Framework/ViewModel/Serialization/ViewModelTypeMetadataSerializer.cs, src/Samples/Common/ViewModels/FeatureSamples/PostbackConcurrency/PostbackConcurrencyViewModel.cs, src/Samples/Common/ViewModels/FeatureSamples/Serialization/ViewModelTransferredOnlyInPath.cs, src/Samples/Common/Views/FeatureSamples/PostbackConcurrency/PostbackConcurrencyMode.dothtml, src/Samples/Common/Views/FeatureSamples/Serialization/TransferredOnlyInPath.dothtml, src/Samples/Tests/Abstractions/SamplesRouteUrls.designer.cs, src/Samples/Tests/Tests/Feature/PostbackConcurrencyTests.cs, src/Samples/Tests/Tests/Feature/SerializationTests.cs, src/Tests/ViewModel/testoutputs/ViewModelTypeMetadataSerializerTests.ViewModelTypeMetadata_TypeMetadata.json
Properties not tranferred server->client shouldn't be updated after a
postback. Doing this lead to unnecesary reverts of client-side
changed value and broke ClientToServerInPostbackPath bind direction.
Resolves https://github.com/riganti/dotvvm/issues/1534
=> Don't update properties with update: "no" 

src/Samples/Common/DotVVM.Samples.Common.csproj, src/Samples/Common/ViewModels/FeatureSamples/Api/CollectionOddEvenWithRestApiViewModel.cs, src/Samples/Common/Views/FeatureSamples/Api/CollectionOddEvenWithRestApi.dothtml, src/Samples/Tests/Abstractions/SamplesRouteUrls.designer.cs, src/Samples/Tests/Tests/Feature/ApiTests.cs
I've added a test for a scenario where REST API binding is on a `Repeater` and it uses the `_collection` binding inside. 
A customer reported that it didn't work in `4.1-preview14-final` but it works in the current `main`.
I've added the test to ensure that we don't break the functionality in the future.
=> Added UI test for REST API bindings with _collection variable

src/Framework/Framework/Hosting/DotvvmPresenter.cs, src/Framework/Framework/Hosting/Middlewares/DotvvmReturnedFileMiddleware.cs
This should simplify using service workers with dotvvm, since the worker often replaces all requests with
Sec-Fetch-Dest: empty. I don't think there is any
problem with allowing the JS requests if people
want them - this rule is mostly to prevent returned files being used for XSS (for example, by being a script)
=> Allow Sec-Fetch-Dest: empty in returned files

src/Framework/Hosting.AspNetCore/Hosting/DotvvmHeaderCollection.cs
This PR adds implementation for a method internally used by VS when debugging. Otherwise, inspecting the collection throws `NotImplementedException`.
=> Added `CopyTo` implementation for HTTP headers collection to improve debugging

src/Framework/Framework/Compilation/Directives/MarkupDirectiveCompilerPipeline.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/ViewModelDirectiveTest.cs
This PR fixes a bug that forces users to specify directives with exact casing (for example, `@viewModel` is valid and `@viewmodel` is not). The breaking change was introduced in one of the preview builds (4.0 - 4.1-preview)
=> Fixed directives to be case-insensitive again

src/Analyzers/Analyzers.Tests/Serializability/ViewModelSerializabilityTest.cs, src/Analyzers/Analyzers.Tests/Verifiers/CSharpAnalyzerVerifier`1.cs, src/Analyzers/Analyzers/Serializability/TypeSymbolExtensions.cs
This PR extends supported types in serializability analysis. Support for the types was added in #1471.
=> Added support for `DateOnly`, `TimeOnly` in VM serializability analysis

src/Framework/Framework/Controls/Validator.cs
This PR fixes a breaking change that was introduced in PR #1385.
I added there a condition that was supposed to throw an exception if the `Validator.Value` can not be resolved to a valid value binding. A customer found out that it is in fact possible to enter this branch when using BP and its `FormItem` control. BP automatically sets validator properties and I am guessing that in some cases it sets there something a little weird.
This change should revert to the previous behaviour while keeping the improved one if the binding can be actually resolved.
=> Fixed issue in `Validator` in connection with BP

src/Framework/Framework/Hosting/MarkupFile.cs
I believe the constructor is safe enough and can provide useful extensibility point if anyone needs to build DotHTML markup dynamically.
=> MarkupFile constructor allows creating the file with specified content

src/Directory.Build.props
This should go to version 4.1, and we should update it in `main` to `4.2`.
If someone references DotVVM from the source code and uses some NuGet package (e. g. commercial controls), the compiler complains that the package needs DotVVM 4.1, but it sees the version built from the source code as 4.0.
=> Version updated to 4.1.0

src/AutoUI/Core/Controls/AutoFormBase.cs, src/AutoUI/Core/Controls/AutoGridViewColumn.cs, src/AutoUI/Core/Controls/BulmaForm.cs, src/AutoUI/Core/Metadata/LocalizableString.cs, src/AutoUI/Core/PropertyHandlers/FormEditors/CheckBoxEditorProvider.cs, src/AutoUI/Core/PropertyHandlers/FormEditors/EnumComboBoxFormEditorProvider.cs, src/AutoUI/Core/PropertyHandlers/FormEditors/TextBoxEditorProvider.cs
I noticed that the `LocalizableString` class depends on the `AutoUIContext` but it only needs `BindingCompilationService`. 
I've refactored this, and I think we should put it in 4.1 to avoid breaking API in the future.
=> LocalizableString needs only BindingCompilationService, not the entire context

.github/setup/action.yml, .github/uitest/action.yml, .github/uitest/uitest.ps1, src/Framework/Framework/Resources/Scripts/api/api.ts, src/Samples/Api.AspNetCore/web.config, src/Samples/Common/DotVVM.Samples.Common.csproj, src/Samples/Common/ViewModels/FeatureSamples/Api/IncludedInPageViewModel.cs, src/Samples/Common/Views/FeatureSamples/Api/IncludedInPage.dothtml, src/Samples/Tests/Abstractions/SamplesRouteUrls.designer.cs, src/Samples/Tests/Tests/Feature/ApiTests.cs
I fixed another problem in REST API bindings reported by a customer.
When the binding is used in an element with `IncludeInPage` set to `false`, the binding is not evaluated - that is correct.
When the element appears on the page, the binding is evaluated at that moment - that is also correct.
However, when the element disappears and re-appears on the page, the binding wasn't refreshed.
The problem was that the reference counting wasn't working well as the binding often evaluates multiple times on the same element so it was incremented multiple times, but decremented only once. I changed that to an array of elements so it is easier to recognize whether the binding was already counted or not.
=> REST API binding - IncludedInPage behavior fixed

src/Analyzers/Analyzers.Tests/ApiUsage/UnsupportedCallSiteAttributeTests.cs, src/Analyzers/Analyzers/AnalyzerReleases.Unshipped.md, src/Analyzers/Analyzers/ApiUsage/UnsupportedCallSiteAttributeAnalyzer.cs, src/Analyzers/Analyzers/DiagnosticCategory.cs, src/Analyzers/Analyzers/DotvvmDiagnosticIds.cs, src/Analyzers/Analyzers/Resources.Designer.cs, src/Analyzers/Analyzers/Resources.resx, src/Framework/Core/CodeAnalysis/CallSiteType.cs, src/Framework/Core/CodeAnalysis/UnsupportedCallSiteAttribute.cs, src/Framework/Core/DotVVM.Core.csproj, src/Framework/Framework/Binding/HelperNamespace/DateTimeExtensions.cs, src/Framework/Framework/Compilation/ControlTree/UnsupportedCallSiteCheckingVisitor.cs, src/Framework/Framework/DependencyInjection/DotVVMServiceCollectionExtensions.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/DefaultControlTreeResolverTests.cs
This PR adds `UnsupportedCallSiteAttribute` that can be placed on a method to signalize that a specific invocation (either from server-side or client-side) is not supported. Moreover, there is also a Roslyn Analyzer that reports violation whenever someone tries to invoke a method marked as only client-side.
Our previous solution was to annotate the method with the `ObsoleteAttribute`. IMO there are the following advantages to the proposed solution for this problem:
* The API no longer looks like it is obsoleted
* VSExtension can not easily filter compiler warnings. Right now it issues false-positives whenever someone uses these methods (for example, `ToBrowserLocalTime`). It is easier to ignore analyzer.
* Users can also use the `UnsupportedCallSiteAttribute` if they wish to make for …
=> Added `UnsupportedCallSiteAttribute` and an analyzer

src/Framework/Framework/Resources/Scripts/dotvvm-root.ts
Adds an extension point for the `window.dotvvm` global object. This is would benefit BusinessPack, which could then use `window.dotvvm.bp`.
=> Add the DotvvmGlobalExtensions interface

src/Analyzers/Analyzers/ApiUsage/UnsupportedCallSiteAttributeAnalyzer.cs
This PR removes the false-positive when building analyzers
See: https://github.com/dotnet/roslyn-analyzers/issues/5828 for more info
=> Fixed warning when building analyzers

src/Framework/Framework/Resources/Scripts/global-declarations.ts, src/Framework/Framework/Resources/Scripts/viewModules/viewModuleManager.ts
It is already referred to from documentation, but the TS type was missing. I made the namedCommands field public, since it's already being used by pretty much everyone.
=> Document DotvvmModuleContext

src/Samples/Common/DotVVM.Samples.Common.csproj, src/Samples/Common/ViewModels/FeatureSamples/Validation/ValidationTargetIsCollectionViewModel.cs, src/Samples/Common/Views/FeatureSamples/Validation/ValidationTargetIsCollection.dothtml, src/Samples/Tests/Abstractions/SamplesRouteUrls.designer.cs, src/Samples/Tests/Tests/Feature/ValidationTests.cs
Resolves #508. This feature was probably fixed/implemented within the big validation rewrite. However, it was not covered by any tests.
=> Added test for collection as Validation.Target

src/Framework/Framework/Configuration/DotvvmMarkupConfiguration.cs, src/Framework/Hosting.AspNetCore/ApplicationBuilderExtensions.cs, src/Framework/Hosting.Owin/AppBuilderExtensions.cs
This simplifies usage with explicit assembly loading
=> Automatically add starting assembly to config.Markup.Assemblies

src/Framework/Framework/Compilation/CompiledAssemblyCache.cs
This PR fixes a weird breaking change where `DotVVM.Framework`, `DotVVM.Framework.Hosting` and `DotVVM.Framework.Testing` were returned twice. I am not sure whether something changed in our configuration but the only change that I was able to observe is GitHub Actions started using 7.0.200 instead of 7.0.102 SDKs
=> Fixed issue where duplicities were returned after upgrading to SDK 7.0.200

src/Framework/Framework/ViewModel/ChildViewModelsCache.cs
This PR fixes a generic exception `An item with the same key has already been added` when trying to reuse instances of viewmodels. Even though this is still not supported, users will at least receive a message that tells what went wrong and possibly how to fix it.
Relevant to: #1576
=> Added a better error when someone tries to reuse viewmodels

src/Framework/JsComponent.React/package-lock.json, src/Framework/JsComponent.React/package.json, src/Samples/Common/yarn.lock
We used to assert that React 17 is used. We don't use any advanced React feature, so this constraint is irrelevant. I set it to 16, since that was the first open source release (with the patents)
=> Relax the constraint on React version

src/Framework/Framework/Resources/Scripts/postback/postbackCore.ts, src/Framework/Framework/Resources/Scripts/postback/updater.ts, src/Framework/Framework/Resources/Scripts/spa/navigation.ts
If the control touched viewmodel in the dispose logic, it would fail with "Cannot find type metadata..." error.
cc @martindybal
=> Replace typeMetadata after cleaning controls in SPA navigate

src/Framework/Framework/Controls/DotvvmMarkupControl.cs, src/Framework/Framework/Resources/Scripts/binding-handlers/markup-controls.ts, src/Framework/Framework/Resources/Scripts/viewModules/viewModuleManager.ts, src/Samples/Common/Scripts/testViewModule.js, src/Samples/Common/Views/FeatureSamples/ViewModules/ModuleControl.dotcontrol, src/Samples/Common/Views/FeatureSamples/ViewModules/ModuleInMarkupControlTwice.dothtml
`ko.contextFor(element)` will return the parent context, only elements inside the control have the `$control` in their context. No such element is guaranteed to exist, so I added a parameter to the `initViewModule` function
=> Fix context.properties in markup control modules

src/Framework/Framework/Compilation/Inference/TypeInferer.cs, src/Tests/Binding/BindingCompilationTests.cs, src/Tests/Runtime/ControlTree/ValueConversionTests.cs
The tempInstantiations was leaking between different candidate
overloads, which lead to an exception being thrown from
Dictionary.Add method
=> type inferrer: Fix unification with mutliple candidates

src/Framework/Framework/Compilation/AttributeValueMergerBase.cs, src/Framework/Framework/Compilation/DefaultAttributeValueMerger.cs, src/Framework/Framework/Compilation/HtmlAttributeValueMerger.cs, src/Framework/Framework/Compilation/Styles/StyleBuilderMethods.Helpers.cs, src/Framework/Testing/ControlTestHelper.cs, src/Tests/ControlTests/ServerSideStyleTests.cs
when called multiple times, it would try to append to the string[] property Styles.RequiredResources, which wasn't supported by the default attribute merger.
I have split the DefaultAttributeMerger into abstract base class which only implements the lookups and the Default which now implements collection concatenation (for server values, not for bindings)
=> Fix Styles.AddRequiredResource method

src/AutoUI/Core/Controls/AutoGridViewColumn.cs
Suppose I implement `GridViewColumnProvider` for some specific property type. In that case, I still cannot use it in `GridView` until I also make the `FormEditorProvider`. The control tries to generate `EditTemplate` which may not be necessary. 
When the property is marked with `[Editable(false)]`, this PR doesn't create the edit template.
=> Removed creation of EditorTemplate when Editable(false)

src/Framework/Framework/Hosting/MarkupFile.cs
I've found that I need to be able to set a last change date to `MarkupFile` to be able to provide a "hot-reload" experience for generated markup files.
=> Markup file - added last change date parameter to the constructor

src/Framework/Framework/ResourceManagement/InlineScriptResource.cs
It is useful when inheriting from the InlineScriptResource
cc @martindybal
=> Add InlineScriptResource.RenderScript helper method

src/Framework/Framework/Binding/BindingCollectionInfo.cs, src/Framework/Framework/Binding/BindingPageInfo.cs, src/Framework/Framework/Binding/HelperNamespace/BindingApi.cs, src/Framework/Framework/Binding/HelperNamespace/Enums.cs, src/Framework/Framework/Compilation/Inference/TypeInferer.cs, src/Framework/Framework/Compilation/Javascript/Ast/JsAstHelpers.cs, src/Framework/Framework/Compilation/Javascript/JavascriptTranslatableMethodCollection.cs, src/Framework/Framework/Compilation/Javascript/JavascriptTranslationVisitor.cs, src/Framework/Framework/Compilation/Javascript/MemberInfoHelper.cs, src/Framework/Framework/Utils/ReflectionUtils.cs, src/Samples/Common/CommonConfiguration.cs, src/Tests/Runtime/testoutputs/RuntimeErrorTests.InitResolverFailure.txt, src/Tests/Runtime/testoutputs/RuntimeErrorTests.PropertyResolverFailure.txt
Added a new Linq.Expressions based API for identifying MethodInfo in JS translation registration and migrated most current translations to it.  This should bring stability across different .NET versions, since the method overloads are fixed on build. New overload in .NET might break the build of DotVVM.Framework, but existing nupkg will not crash on startup
Translations which were not migrated were mostly relying on the `allowMultipleMethods: true` feature. Using that should be stable already and I didn't want to rewrite the code by explicitly listing all overloads
=> Migrate most translations to Linq.Expressions based API

src/AutoUI/Core/AutoUIExtensions.cs
Until now, we couldn't configure Auto UI in any other place than in the `AddAutoUI` method, which is not great for libraries that want to extend Auto UI.
Similar to `DotvvmConfiguration`, this PR allows doing this:
```
services.Configure<AutoUIConfiguration>(config => { ... });
```
=> Added an option to configure AutoUIConfiguration

src/Framework/Framework/Binding/ViewModuleReferenceInfo.cs, src/Framework/Framework/Compilation/ControlTree/BindingExtensionParameter.cs, src/Framework/Framework/Compilation/ControlTree/ControlTreeResolverBase.cs, src/Framework/Framework/Compilation/ControlTree/DefaultControlTreeResolver.cs, src/Framework/Framework/Compilation/Directives/MarkupDirectiveCompilerPipeline.cs, src/Framework/Framework/Compilation/Directives/MarkupPageMetadata.cs, src/Framework/Framework/Compilation/Directives/MasterPageDirectiveCompiler.cs, src/Framework/Framework/Compilation/Directives/ViewModuleDirectiveCompiler.cs, src/Framework/Framework/Controls/Content.cs, src/Framework/Framework/Controls/ViewModuleHelpers.cs
This PR fixes a couple of problems introduced to the compiler pipeline's internal API in version 4.1. These fixes make it significantly easier to adopt DotVVM 4.1 for VS Extension.
**What was not ideal**:
* `IMarkupDirectiveCompilerPipeline` required `IControlBuilderFactory` whose implementation directly depends on runtime information (`CompiledAssemblyCache` and others)
* The runtime information was needed to achieve three things:
* Master page is being resolved almost immediately
* Resolved master page is used to validate its viewmodel
* Resolved master page is used to assign view modul IDs (if any modules are present)
**Changes in this PR**:
* Master page is being resolved by `DefaultControlTreeResolver`, which is called by `ControlTreeResolverBase.ResolveTree(...)`
* Master page is …
=> Remove runtime dependency from compiler pipeline

src/Framework/Framework/ViewModel/Serialization/ViewModelSerializationMap.cs, src/Tests/ViewModel/ViewModelSerializationMapperTests.cs
This PR adds a routine that checks for member shadowing. Even though users get the following warning from Roslyn: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0108, I have already seen a couple of reports that crash during runtime on something similar to this:
While it is still not supported, this change should throw a more descriptive exception that points directly to the source of this issue and also does the check a bit sooner.
=> Add member shadowing detection routine

src/AutoUI/Core/Metadata/LocalizableString.cs, src/Framework/Framework/Binding/BindingHelper.cs, src/Framework/Framework/Binding/BindingPropertyException.cs, src/Framework/Framework/Binding/Expressions/BindingDelegates.cs, src/Framework/Framework/Binding/Expressions/CommandBindingExpression.cs, src/Framework/Framework/Binding/Expressions/ValueBindingExpression.cs, src/Framework/Framework/Binding/ValueOrBindingExtensions.cs, src/Framework/Framework/Compilation/Binding/ExpressionNullPropagationVisitor.cs, src/Framework/Framework/Compilation/Binding/GeneralBindingPropertyResolvers.cs, src/Framework/Framework/Compilation/BindingCompiler.cs, src/Framework/Framework/Controls/DotvvmBindableObject.cs, src/Framework/Framework/Controls/PropertyImmutableHashtable.cs, src/Framework/Framework/ResourceManagement/LinkResourceBase.cs, src/Framework/Framework/Utils/ExpressionUtils.cs, src/Samples/Common/Views/ControlSamples/TemplateHost/CompositeListControlWithTemplate.cs, src/Samples/Common/Views/ControlSamples/TemplateHost/TemplatedListControl.cs, src/Tests/Binding/BindingCompilationTests.cs, src/Tests/Binding/testoutputs/BindingCompilationTests.Error_DifferentDataContext.txt, src/Tests/Binding/testoutputs/BindingCompilationTests.Error_MissingDataContext.txt, src/Tests/ControlTests/MarkupControlTests.cs, src/Tests/ControlTests/RepeaterTests.cs, src/Tests/ControlTests/testoutputs/MarkupControlTests.DataContextChange.html, src/Tests/ControlTests/testoutputs/RepeaterTests.RepeatedTextBox.html
Resolving of binding data contexts is moved to the compiled binding delegate.
Instead creating a data context array, we emit a sequence of `GetContextControl` and `GetContextAndControl<T>` calls,
which efficiently walks the control hierarchy while evaluating the needed data context.
Note that it evaluates only data contexts referenced in the binding. DataContext is also evaluated, if the it's is only referenced, but not needed due to conditional evaluation (`_this.MyProperty == 0 ? _parent.X : "xx"` always evaluates `_parent`). It's not that common and would be significantly more complex to implement.
This should improve error reporting when binding is being evaluated in unexpected data context. In a way, this is overengineered version of #1286  
* Data context is missing, the hierarchy …
=> Move data context resolving into the compiled BindingDelegate

src/Framework/Framework/Compilation/DefaultControlBuilderFactory.cs, src/Framework/Framework/Hosting/MarkupFile.cs
MarkupFileLoader did check the LastWriteTimeUtc on each request and would recompile the page if the page changed. While we have worse performance issues, this is quite unnecesary. IMHO it's more likely to break production server when new source code is copied there.
Moreover, the loader would allocate new IControlBuilder, but didn't unreference the old one, leaking some memory. I didn't test that this commit fixes it, though.
=> MarkupFileLoader will not reload in Release and not leak in Debug

src/Framework/Framework/Resources/Scripts/postback/redirect.ts, src/Framework/Framework/Resources/Scripts/spa/navigation.ts, src/Framework/Framework/Resources/Scripts/tests/eventArgs.test.ts, src/Samples/Common/DotvvmStartup.cs, src/Samples/Common/Views/ComplexSamples/SPA/default.dothtml, src/Samples/Common/Views/ComplexSamples/SPA/site.dotmaster, src/Samples/Common/Views/ComplexSamples/SPA/test.dothtml, src/Samples/Tests/Tests/Complex/SPATests.cs
Otherwise, two pages are placed into the history during navigation, making it impossible (or at least hard) to navigate back.
=> Always replace in history on redirect in SPA navigation

src/AutoUI/Core/Controls/AutoFormBase.cs
It would be nice to access `GetPropertiesToDisplay` in all derived classes when building new custom form. I am building form that is based on grid, so I do not want to inherit from `AutoForm`.
=> AutoUi GetPropertiesToDisplay no longer internal

src/AutoUI/Core/AutoUIExtensions.cs, src/AutoUI/Core/Controls/AutoFormBase.cs, src/AutoUI/Core/PropertyHandlers/FormEditors/MultiSelectorCheckBoxFormEditorProvider.cs, src/AutoUI/Core/PropertyHandlers/FormEditors/SelectorComboBoxFormEditorProvider.cs, src/AutoUI/Core/PropertyHandlers/ISelectorDiscoveryService.cs, src/AutoUI/Core/PropertyHandlers/SelectorDiscoveryService.cs
The `SelectorHelper` is recursively browsing the viewmodel and looks for properties `ISelectionViewModel<TSelectionItem>`.
By default, it looks only into the child objects which implement `IDotvvmViewModel` but I need to be able to extend this behavior to look also into `Tuple` or other tuple-like structures.
=> Refactoring of SelectorHelper into SelectorDiscoveryService

src/Framework/Framework/Binding/ExtractGenericArgumentDataContextChangeAttribute.cs, src/Framework/Framework/Compilation/ControlTree/ITypeDescriptor.cs, src/Framework/Framework/Compilation/ControlTree/Resolved/ResolvedTypeDescriptor.cs, src/Framework/Framework/Utils/ReflectionUtils.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/ControlWithOverriddenRules.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/DefaultControlTreeResolverTests.cs
This PR adds a new `ExtractGenericArgumentDataContextChangeAttribute`, which looks at base types or implemented interfaces of the current data context type (e. g. `IGroupingDataSet<T>`) and extracts the type argument on a specified index.
=> Extract generic type data context change attribute

src/Framework/Hosting.AspNetCore/ApplicationBuilderExtensions.cs, src/Framework/Hosting.AspNetCore/WebApplicationBuilderExtensions.cs
Added extension methods which support configuration of the app in one file without `DotvvmStartup`.
```
var builder = WebApplication.CreateBuilder(args);
builder.AddDotVVM(options =>
{
// register DotVVM services
options.AddAutoUI();
...
});
var app = builder.Build();
app.UseDotVVM(..., config => 
{
// fine-tune DotvvmConfiguration 
});
app.UseStaticFiles();
app.Run();
```
=> Initialization of DotVVM in a single file

src/Directory.Build.props, src/Framework/Framework/Configuration/DotvvmExperimentalFeaturesConfiguration.cs, src/Framework/Framework/Configuration/DotvvmFeatureFlag.cs, src/Framework/Framework/Configuration/DotvvmGlobalFeatureFlag.cs, src/Framework/Framework/Configuration/DotvvmSecurityConfiguration.cs, src/Framework/Framework/Hosting/DotvvmPresenter.cs, src/Framework/Framework/Routing/DotvvmRouteTable.cs, src/Framework/Framework/Routing/RouteHelper.cs, src/Tests/DotVVM.Framework.Tests.csproj, src/Tests/GlobalUsings.cs, src/Tests/Runtime/ConfigurationValidationTests.cs, src/Tests/Runtime/config-tests/ConfigurationValidationTests.ValidateMissingRoutes.txt
The API was originally designed for features which are disabled by default,
but it's now being used for features enabled by default (mainly security headers).
For this reason I'm adding the DisableForAllRoutes method. DisableForRoutes is not neccesary,
EnableForAllRoutesExcept has exactly this semantic. The name might be a bit confusing in
this context, but I'm not sure adding a synonym will help.
Instead I'm adding methods for incrementaly including/excluding additional routes:
* IncludeRoute(string) / IncludeRoutes(string[])
* ExcludeRoute(string) / ExcludeRoutes(string[])
These new methods can be used in fluent style to save some keystrokes, for example
```
config.Security.FrameOptionsCrossOrigin
.DisableForAllRoutes()
.IncludeRoute("route1")
.IncludeRoute("route2");
```
=> Extend DotvvmFeatureFlag API, improve validation

src/Directory.Build.props, src/Framework/Framework/Controls/Infrastructure/MarkupControlContainer.cs, src/Tests/ControlTests/CompositeControlTests.cs, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json
When MarkupControlContainer was used multiple times, the commands inside the markup control would fail on `DotVVM.Framework.Controls.DotvvmControlException: Multiple controls with the same UniqueID 'c16_c0' were found`
The bug was reported by Jan Berger at [gitter](https://matrix.to/#/!WrfMXMmXzbYrOMCMCo:gitter.im/$dj6mrwJ15DgEzJk2jnIVXqSoXt34JZS3_iubYr1_HJ4?via=gitter.im&via=matrix.org)
=> Fix non-unique markup control ID in MarkupControlContainer

src/Framework/Framework/Controls/DotvvmBindableObjectHelper.cs, src/Framework/Framework/Controls/HtmlGenericControl.cs, src/Framework/Testing/ControlTestHelper.cs, src/Tests/ControlTests/HtmlGenericControlTests.cs, src/Tests/ControlTests/RepeaterTests.cs, src/Tests/ControlTests/testoutputs/CompositeControlTests.BasicWrappedHtmlControl.html, src/Tests/ControlTests/testoutputs/ServerSideStyleTests.CapabilityReads.html, src/Tests/ControlTests/testoutputs/ServerSideStyleTests.PostbackHandlers.html, src/Tests/ControlTests/testoutputs/ServerSideStyleTests.StyleBindingMapping.html, src/Tests/ControlTests/testoutputs/SimpleControlTests.HtmlControl.html
Unifies how client/server rendering mode behaves in all HtmlGenericControl properties to "always render both".
* Applies to Visible, Attributes, CssClasses, CssStyles
* When property contains value binding, knockout binding is added
* The property is always rendered server-side
* When value binding evaluation fails on server, the exception is suppressed.
The behavior is unchanged in `CssClasses` and `CssStyles`, I have added the try catch to Visible and Attributes are now rendered in server-side mode. Technically, this is a **breaking change**, so we should definitely announce it, but the impact should be small - In most cases, what is rendered server-side is irrelevant to normal page behavior, it only affect indexers and page load performance.
I have also changed how returning `null` …
=> Unify client/server evaluation in HtmlGenericControl

src/AutoUI/Core/AutoUIContext.cs, src/AutoUI/Core/PropertyHandlers/FormEditors/MultiSelectorCheckBoxFormEditorProvider.cs, src/AutoUI/Core/PropertyHandlers/FormEditors/SelectorComboBoxFormEditorProvider.cs
We had slight mismatches in the data context types of selector bindings - the control context normally includes _index and _collection extension parameters, but the bindings created by AutoUI did not. This didn't cause any issues, since ComboBox doesn't check it and
the multi selector contained a DataContextType override.
However, if the same logic was used as is in other places (BP), it was crashing with data context type mismatch exception.
=> AutoUI: nested contexts should contain _index and _collection

src/Framework/Framework/Utils/TaskUtils.cs
For some reason, I was getting "Property Result does not exist" error in the dynamic invocation. I couldn't replicate it in the framework - we already have a number of tests for async static commands.
However, we were already accessing Result property using reflection, so this change should make anything noticably slower
=> Fix weird glitch in async static command invocation

src/Framework/Framework/Compilation/Parser/Dothtml/Parser/DothtmlNode.cs, src/Framework/Framework/Compilation/ViewCompiler/DefaultViewCompiler.cs
Currently, warnings from the compilation stage are only shown in VS Extension. This makes them also visible the Asp.Net Core log.
=> Log compilation warnings to ILogger

src/Framework/Framework/Configuration/DotvvmConfiguration.cs, src/Framework/Framework/Routing/DotvvmRoute.cs, src/Tests/Routing/DotvvmRouteTests.cs
There is a bug in route matching for optional parameters with constraints.
If the optional parameter is not present in the URL, the `IsMatch` method sometimes returns it in the `parameters` collection as an empty string, but sometimes it is not present in the collection at all (even when it specifies the default value). 
Additionally, in cases where it returns an empty string, it doesn't satisfy the constraint, and thus the route is not matched.
```
// original behavior
var routeA = new DotvvmRoute("{Id?}", ...);
var result1 = routeA.IsMatch("", out var parameters);         // result1 = true, parameters1 = [ "" ]
var result2 = routeA.IsMatch("/", out var parameters);        // result2 = true, parameters2 = [ ]
var routeB = new DotvvmRoute("{Id?:int}", ...);
var result3 = …
```
=> Route not matched when it has optional parameter with constraint

src/Framework/Framework/Hosting/StaticCommandExecutor.cs, src/Framework/Framework/Hosting/StaticCommandModelState.cs, src/Framework/Framework/Utils/ExpressionUtils.cs, src/Tests/Binding/StaticCommandExecutorTests.cs
The AddArgumentError method would not work if more complex expression than single identifier was used. This patch replaces a simple MemberExpression matching with a visitor which replaces display class members with ExpressionExpression. Then the standard JsTranslator can handle the expression and produce a validation path
=> StaticCommand validation: Fix lambda expression based API

src/Framework/Framework/Controls/DotvvmControl.cs, src/Tests/ControlTests/SimpleControlTests.cs, src/Tests/ControlTests/testoutputs/SimpleControlTests.IncludeInPage.html
This happens easily due to the automatic null propagation. When null is returned, we stick to the default value and do include control
=> Fix NRE when IncludeInPage={resource: null}

src/Framework/Core/ViewModel/CustomPrimitiveTypeAttribute.cs, src/Framework/Core/ViewModel/IDotvvmPrimitiveType.cs, src/Framework/Framework/Configuration/CustomPrimitiveTypeRegistration.cs, src/Framework/Framework/Controls/HtmlGenericControl.cs, src/Framework/Framework/Utils/ReflectionUtils.cs, src/Framework/Framework/ViewModel/Validation/ViewModelValidator.cs, src/Samples/Common/Controls/ControlWithCustomPrimitiveTypeProperties.cs, src/Samples/Common/ViewModels/FeatureSamples/CustomPrimitiveTypes/SampleId.cs, src/Tests/Binding/BindingCompilationTests.cs
This allows for efficient checks if a value is primitive without the need for cache hashtable containing all types we encounter
=> Switch custom primitive types to a marker interface

src/Framework/Framework/Controls/DotvvmControl.cs, src/Framework/Framework/Controls/HtmlGenericControl.cs, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json
…
It only produced a warning, but still,
hardcoded values and resource bindings are already supported in both properties.
=> Allow hardcoded values and resource bindings in IncludeInPage, Visible properties

src/Framework/Framework/ResourceManagement/ViewModuleInitResource.cs, src/Tests/ControlTests/testoutputs/ViewModulesServerSideTests.IncludeViewModule.html, src/Tests/ControlTests/testoutputs/ViewModulesServerSideTests.IncludeViewModuleInControl.html
This allows using dotvvm.state (etc.) already in the module constructor.
resolves  #1592
=> Run module initialization in dotvvm.init event

src/Framework/Framework/Resources/Scripts/binding-handlers/js-component.ts, src/Framework/Framework/Resources/Scripts/binding-handlers/textbox-text.ts, src/Framework/Framework/Resources/Scripts/postback/queue.ts, src/Framework/Framework/Resources/Scripts/postback/updater.ts, src/Framework/Framework/Resources/Scripts/utils/promise.ts
Initialization, update and dispose of JsComponent
is now executed in the next event loop cycle - i.e. after all other knockout components have been initialized. The main reason for this is to NOT handle
exceptions from the JS component and avoid
crashing the entire page when one component fails to load.
=> Run all JsComponent interactions asynchronously

src/Framework/Testing/DotvvmTestHelper.cs, src/Tests/AspCore/Middleware/MiddlewareTest.cs, src/Tests/DotVVM.Framework.Tests.csproj, src/Tests/Runtime/DotvvmControlRenderedHtmlTests.cs, src/Tests/Runtime/DotvvmPropertyTests.cs, src/Tests/ViewModel/DefaultViewModelSerializerTests.cs
We were on old enough version to not be affected by the spyware, but we only used the lib in 2 places so it's easy to rip out.
See https://github.com/moq/moq/issues/1372 for context
=> Remove Moq dependency from tests

src/Framework/Framework/Compilation/Binding/StaticCommandBindingCompiler.cs, src/Framework/Framework/Compilation/Javascript/JavascriptTranslatableMethodCollection.cs, src/Framework/Framework/Compilation/Javascript/JavascriptTranslator.cs, src/Framework/Framework/Configuration/DotvvmMarkupConfiguration.cs, src/Framework/Framework/Configuration/FreezableList.cs, src/Framework/Framework/ViewModel/Validation/ValidationErrorFactory.cs
JavascriptTranslatorConfiguration constructor
initialized the translation collection on every invocation, which caused serious compilation slowdown of staticCommands which need to create new config every time.
=> Fix repeated initialization of JS translator collection

src/Framework/Framework/Routing/DotvvmRoute.cs, src/Framework/Framework/Routing/UrlHelper.cs, src/Tests/Routing/DotvvmRouteTests.cs
I've found that the route parameters were converted to `string` using `IConvertible` or plain `ToString()`. 
We should make sure that the primitive types are always serialized the same way.
Also, the query string parameters were using only `ToString()`. I've made these two share the same implementation.
=> Route parameter serialization made consistent for custom primitive types

src/Framework/Framework/Controls/CheckableControlBase.cs, src/Framework/Framework/Controls/HtmlGenericControl.cs, src/Framework/Framework/Controls/KnockoutBindingGroup.cs, src/Framework/Framework/Controls/KnockoutHelper.cs, src/Framework/Framework/Controls/RadioButton.cs, src/Samples/Common/Views/FeatureSamples/FormControlsEnabled/FormControlsEnabled.dothtml, src/Tests/ControlTests/SimpleControlTests.cs, src/Tests/ControlTests/testoutputs/SimpleControlTests.RadioButton.html, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json
* all properties (Checked, Enabled, GroupName) will render both knockout expression and the value
* if value binding is used and evaluation fails, the exception is ignored (as in HtmlGenericControl, new helper method was added for this)
* GroupName now allows value bindings - this might be useful for usage in client-side Repeater
resolves #1538
=> Refactor RadioButton to unify client/server rendering

src/Framework/Framework/Hosting/ErrorPages/ErrorPageTemplate.cs, src/Framework/Framework/Resources/Scripts/binding-handlers/markup-controls.ts, src/Framework/Framework/Resources/Scripts/dotvvm-root.ts, src/Framework/Framework/Resources/Scripts/global-declarations.ts, src/Framework/Framework/Resources/Scripts/state-manager.ts, src/Framework/Framework/Resources/Scripts/utils/objects.ts, src/Framework/Framework/Resources/Scripts/viewModules/viewModuleManager.ts, src/Framework/Framework/Runtime/DefaultOutputRenderer.cs, src/Samples/Common/CommonConfiguration.cs, src/Samples/Common/DotvvmStartup.cs, src/Samples/Common/Scripts/stateAwareViewModule.js, src/Samples/Common/Scripts/testViewModule.js, src/Samples/Common/ViewModels/FeatureSamples/ViewModules/ModuleStateManipulationViewModel.cs, src/Samples/Common/Views/FeatureSamples/ViewModules/StateIncrementer.dotcontrol, src/Samples/Common/Views/FeatureSamples/ViewModules/StateManipulation.dothtml, src/Samples/Tests/Abstractions/SamplesRouteUrls.designer.cs, src/Samples/Tests/Tests/Feature/ViewModuleTests.cs
Unified interface on dotvvm global, on our observables and on module context to
* `state` readonly property
* `setState(x)`
* `patchState(x)`
* `updateState(s => modify(s))`
=> Unify interfaces for state manipulation

src/Framework/Framework/Compilation/Parser/Dothtml/Parser/DothtmlParser.cs, src/Samples/Common/Views/Samples.dotmaster, src/Tests/Parser/Dothtml/DothtmlParserTests.cs
Enabling the warnings in #1659 reveals that our handling of unclosed tags is not ideal. This patch is attempt to improve it, while maintaining reasonable level of backwards compatibility.
The only behavior change is what happens when `</x>` has no opening tag
* previous: close currently open elements, then insert `<x />`
* new: insert `<x />` into the current element
a warning is issued in both cases. The new logic avoids a major problem of one accidental end tag closing the entire hierarchy, including the `<body>` and `<html>` elements. Since we insert script references at the end of body, this puts the scripts and viewmodel wherever the closing tag was. This change has the potential to break something
Other changes only affect the issued warning:
* no warning on an unclosed tags like …
=> More reasonable unclosed tag handling

src/Framework/Framework/Compilation/Javascript/JsViewModelPropertyAdjuster.cs, src/Tests/Binding/JavascriptCompilationTests.cs
The primitive will be a string client-side, and the property will thus always be `undefined`.
=> Validate that properties on custom primitive types are not used in JS

src/Framework/Framework/Compilation/ControlPrecompilationVisitor.cs, src/Framework/Framework/Controls/CompositeControl.cs, src/Tests/ControlTests/CompositeControlTests.cs, src/Tests/ControlTests/testoutputs/CompositeControlTests.AutoclonedPostbackHandlers.html, src/Tests/ControlTests/testoutputs/CompositeControlTests.CommandDataContextChange.html
PostBack.Handlers are copied onto the created controls, if they contain a matching command binding.
* We map postback handlers onto the command bindings set on the CompositeControl by comparing the EventName and property name
* For each control returned from GetContents, we enumerate its command bindings and compare them to the command bindings found on the CompositeControl.
* If a matching command binding is found, we clone its postback handlers onto the child control. EventName is adjusted to match the new property name
The control enumeration is done recursively before adding the control to Children, thus walking only through the tree created in this CompositeControl - nested CompositeControls,
initialized Repeaters, ... are not included.
In order to support templatws created in the …
=> Support PostBack.Handlers in CompositeControls

src/Framework/Framework/Binding/ExtractGenericArgumentDataContextChangeAttribute.cs, src/Framework/Framework/Utils/ReflectionUtils.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/ControlWithOverriddenRules.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/DefaultControlTreeResolverTests.cs
There was a bug in `ExtractGenericArgumentDataContextChange` attribute - the method overload with `Type` wasn't comparing the generic arguments correctly.
Also, when the DataContext was directly the requested type, it didn't match because we inspected only implemented interfaces and base types, but not self.
=> Fixed bug in ExtractGenericArgumentDataContextChangeAttribute

src/Framework/Framework/Hosting/DotvvmMetrics.cs, src/Tests/Runtime/MetricsTests.cs
The stupid prometheus-net library call the TryGetRecommendedBuckets function for every single datapoint...
I didn't want to cache the result arrays, as we'd have to undo that optimization when we add some configuration arguments to the TryGetRecommendedBuckets method. I also really needed to finally use The Float Trick :D
=> Fix mistakes in doccomments in DotvvmMetrics, optimize exponential buckets

src/Framework/Framework/Compilation/Binding/ExpressionNullPropagationVisitor.cs, src/Framework/Framework/Compilation/Binding/TypeConversions.cs, src/Samples/Common/DotVVM.Samples.Common.csproj, src/Samples/Common/ViewModels/FeatureSamples/ViewModelDeserialization/PropertyNullAssignmentViewModel.cs, src/Samples/Common/Views/FeatureSamples/ViewModelDeserialization/PropertyNullAssignment.dothtml, src/Samples/Tests/Abstractions/SamplesRouteUrls.designer.cs, src/Samples/Tests/Tests/ErrorsTests.cs, src/Samples/Tests/Tests/Feature/ViewModelDeserializationTests.cs, src/Tests/Binding/BindingCompilationTests.cs, src/Tests/Binding/NullPropagationTests.cs
I've found a bug, probably in the binding parser - `NullableProperty = null` doesn't work as expected - instead of assigning `null` to the property, it assigns the default value for its unwrapped type.
Repro sample is here: `/FeatureSamples/ViewModelDeserialization/PropertyNullAssignment`
=> Repro for a bug with null assignment

src/Framework/Framework/Resources/Scripts/tests/helper.ts, src/Framework/Framework/Resources/Scripts/tests/postback.test.ts
resolves #900
Note that it seems to work fine, but the nested postbacks must be in a different concurrency queue (regardless of the concurrency mode)
=> Add JS test for nested postbacks

src/Framework/Framework/Binding/ExtractGenericArgumentDataContextChangeAttribute.cs, src/Framework/Framework/Compilation/ControlTree/IAbstractPropertyDeclarationDirective.cs, src/Framework/Framework/Compilation/ControlTree/ITypeDescriptor.cs, src/Framework/Framework/Compilation/ControlTree/Resolved/ResolvedTypeDescriptor.cs, src/Framework/Framework/Compilation/Directives/BaseTypeDirectiveCompiler.cs, src/Framework/Framework/Compilation/Directives/MarkupDirectiveCompilerPipeline.cs, src/Framework/Framework/Compilation/Directives/MarkupDirectiveCompilerPipelineBase.cs, src/Framework/Framework/Compilation/Directives/PropertyDeclarationDirectiveCompiler.cs, src/Framework/Framework/Compilation/Directives/ResolvedBaseTypeDirectiveCompiler.cs, src/Framework/Framework/Compilation/Parser/Binding/Parser/BindingParser.cs, src/Tests/Parser/Binding/BindingParserTests.cs
It used naked type making it impossible to integrate in VS Extension.
=> ExtractGenericArgumentDataContextChangeAttribute attrribute VS Extension compatibility

src/Framework/Framework/Compilation/ControlTree/ControlTreeResolverBase.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/DefaultControlTreeResolverTests.cs
When setting HTML attributes on HierarchyRepeater Item and Level capabilites, it's more readable to uppercase the first letter, e.g. ItemClass instead of Itemclass. However, this triggered the "Class dotvvm property doesn't exist" warning.
=> Suppress the uppercase html attribute warning if it must have a prefix

src/Framework/Framework/Compilation/ViewCompiler/DefaultViewCompiler.cs
Tabs are replaced by tabs to preserve the string width, all other characters are replaced by a single space. Moreover we now count the unicode graphemes instead of UTF16 units. It still has the problem that some characters (Emoji, CJK) are wider even in monospace fonts, but that's not that easy to determine.
Before:
Now:
The 2 spaces after the emoji is actually a bug in the terminal emulator I use.
=> Fix whitespace padding width with tabs and Unicode combining characters

src/Framework/Framework/Compilation/Binding/ExpressionBuildingVisitor.cs, src/Tests/Binding/BindingCompilationTests.cs, src/Tests/Binding/ImplicitConversionTests.cs
Fixes compilation of ternary expressions with ambiguous conversion (in C?A:B A is convertible to B while B is also convertible to A). This is normally disallowed in C#, but I specifically allowed two cases
* one of them is `object` which can be converted to the other type - this occurs if the `object` is null
* one of them is `string` which is convertible to the other type - this occurs for our enum constant literals
should fix part of #1694
=> Fix implicit conversion in expressions like `C ? P : null`

src/Framework/Framework/Controls/CompositeControl.cs, src/Tests/ControlTests/CompositeControlTests.cs, src/Tests/ControlTests/testoutputs/CompositeControlTests.CompositeControlInheritance.html
According to  #1613 CompositeControl do not work with both base and derived types defining GetContents method. I could not replicate that, the provided example works for me, maybe it was fixed accidentally.
* I added test for that
* In any case, multiple GetContents overloads were handled poorly, I added better error for this case.
In the issue, I mentioned that it would be complex to handle potential redefinition or "removal" of properties in the derived type. That isn't really the case, both cases don't need any special code
* The "removal" - omission of an property in the derived type is simply ignored. I think that it's quite intuitive that properties can't disappear in derived types, if the GetContents doesn't ask for it it won't get it.
* Redefinition is already handled reasonably, …
=> CompositeControl: ambiguous GetContents error message, test inheritance

src/Framework/Framework/Runtime/Commands/EventValidator.cs, src/Framework/Framework/Runtime/Commands/InvalidCommandInvocationException.cs
Bindings with matching ID are most prefered,
then bindings from the correct control are prefered, then it's sorted by the number of matching properties.
=> Sort the bindings in invalid command invocation error

src/Framework/Framework/Compilation/Javascript/JavascriptTranslatableMethodCollection.cs, src/Framework/Framework/Diagnostics/CompilationPage.dothtml, src/Framework/Framework/Diagnostics/CompilationPageViewModel.cs, src/Tests/Binding/JavascriptCompilationTests.cs
Original goal was to add an "Errors" tab to the compilation which lists all failed pages, controls and master pages. Saves few clicks and scrolling when checking the compilation page.
However, I had to fix Linq translations on `ImmutableArray`. ImmutableArray is a struct so it has custom Linq method overloads to avoid allocations. These are preferred by the compiler over the `IEnumerable<T>` methods.
I also added .AsEnumerable and few other conversion methods to help users work around similar issues.
=> support Linq methods on ImmutableArray + added Errors tab to Compilation Page

src/Framework/Framework/Compilation/Javascript/JavascriptTranslatableMethodCollection.cs, src/Framework/Framework/Compilation/Javascript/PrimitiveToStringTranslator.cs, src/Samples/Common/DotVVM.Samples.Common.csproj, src/Samples/Common/ViewModels/FeatureSamples/Formatting/ToStringGlobalFunctionBugViewModel.cs, src/Samples/Common/Views/FeatureSamples/Formatting/ToStringGlobalFunctionBug.dothtml, src/Samples/Tests/Abstractions/SamplesRouteUrls.designer.cs, src/Samples/Tests/Tests/Feature/FormattingTests.cs, src/Tests/Binding/JavascriptCompilationTests.cs
If we call a global JS function from a binding and there is a viewmodel property with the same name, it takes precedence. In this case, we were converting `bool` to `string` by emitting `String(value)`, but if there was a property called `String` in the viewmodel, it assigned the value in it.
This is a crazy bug, and this PR doesn't by far fix all cases - I am afraid it is almost impossible.
I fixed the `String(...)` and `Number(...)` cases but what if someone has a property called `window` in the viewmodel... ☠️ 
Luckily, most JS global functions start with a lowercase letter while viewmodel properties commonly start with an uppercase letter.
=> Fixed string conversion bug with global function

src/Framework/Framework/Compilation/ControlTree/IAbstractTreeBuilder.cs, src/Framework/Framework/Compilation/ControlTree/Resolved/ResolvedTreeBuilder.cs, src/Framework/Framework/Compilation/Directives/PropertyDeclarationDirectiveCompiler.cs, src/Framework/Framework/Compilation/Parser/Binding/Parser/BindingParser.cs, src/Framework/Framework/Compilation/Parser/Binding/Parser/BindingParserNode.cs, src/Framework/Framework/Compilation/Parser/Binding/Parser/TypeOrFunctionReferenceBindingParserNode.cs, src/Tests/Parser/Binding/BindingParserTests.cs
With introduction of type reference nodes a bug appeared, where the type references had incorrect ranges and tokens.
=> BindingParser: Fixing missing tokens and ranges

src/Framework/Framework/Diagnostics/JsonSizeAnalyzer.cs, src/Framework/Framework/Diagnostics/PerformanceWarningTracer.cs
For some reason, the analyzer may sometimes throw NullReferenceException. Rather than failing the entire page, we now just log the error and continue.
=> Handle exceptions in JsonSizeAnalyzer

src/Framework/Framework/Controls/HtmlWriter.cs, src/Tests/Runtime/HtmlWriterTests.cs
=> Fix ampersand escaping

src/Framework/Framework/Hosting/DotvvmPresenter.cs, src/Framework/Framework/Hosting/DotvvmRequestContext.cs, src/Samples/Common/DotVVM.Samples.Common.csproj, src/Samples/Common/ViewModels/FeatureSamples/NoJsForm/NoJsFormViewModel.cs, src/Samples/Common/Views/FeatureSamples/NoJsForm/NoJsForm.dothtml, src/Samples/Tests/Abstractions/SamplesRouteUrls.designer.cs, src/Samples/Tests/Tests/Feature/NoJsFormTests.cs
We used to ignore the request method and only decide if we should run a command or a page initial "GET" based on the headers. This got rewritten in 4.2 and thus broke anyone manually doing and handling POST requests. It has been "expoited" by some users to do "API requests", but can also be used to implement classic POST forms,
as a no-JS or shitty network fallback.
To implement a no-JS form in DotVVM with this patch:
<form method="POST">
<input type="text" name="something" />
<button type=submit name=submit value=my-form>Submit</button>
</form>
and handle it in view model:
public override async Task Load()
{
var req = Context.HttpContext.Request;
if (req.Method == "POST")
{
using var body = new StreamReader(req.Body);
var data = HttpUtility.ParseQueryString(await body.ReadToEndAsync()); …
=> Add back support for manually handling POST requests

src/Framework/Framework/Controls/DotvvmBindableObjectHelper.cs
Useful when warnings are produced on control created from a CompositeControl. We still only show details of the nested control, but at least the line number now identifies where it comes from.
=> runtime warnings: include markup line number of nearest ancestor

src/Framework/Framework/Resources/Scripts/global-declarations.ts, src/Framework/Framework/Resources/Scripts/metadata/coercer.ts, src/Framework/Framework/Resources/Scripts/metadata/typeMap.ts, src/Framework/Framework/Resources/Scripts/state-manager.ts, src/Framework/Framework/Resources/Scripts/tests/coercer.test.ts
We already send `debugName` property in type metadata for this purpose. Type hash is also included in the message as it might also be useful
=> Include real type names in client-side error messages

src/Framework/Hosting.AspNetCore/DotVVM.Framework.Hosting.AspNetCore.csproj
This PR removes an unnecessary reference to `Microsoft.CodeAnalysis.CSharp` in the project `DotVVM.Framework.Hosting.AspNetCore`. This reference is unused yet brings a lot of transitive references to legacy `System` packages from .NET Core 1.x.
=> Remove reference to `Microsoft.CodeAnalysis.CSharp` in AspNetCore package

src/Framework/Framework/Compilation/ControlTree/ControlTreeResolverBase.cs
Ideas on other ways to solve this issue are welcome :/
=> Whitelist SVG attributes from the uppercase letter warning

src/Framework/Framework/Compilation/Parser/Binding/Parser/ArrayInitializerExpression.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/PropertyDirectiveTests.cs
- `EnumerateChildNodes` method incorectly returned the node itself leading to overflow in visitors.
=> Incorrect child nodes for array initializer fixed

src/Framework/Framework/Compilation/ControlTree/IAbstractDirectiveAttributeReference.cs, src/Framework/Framework/Compilation/ControlTree/IAbstractTreeBuilder.cs, src/Framework/Framework/Compilation/ControlTree/Resolved/ResolvedPropertyDeclarationDirective.cs, src/Framework/Framework/Compilation/ControlTree/Resolved/ResolvedPropertyDirectiveAttributeReference.cs, src/Framework/Framework/Compilation/ControlTree/Resolved/ResolvedTreeBuilder.cs, src/Framework/Framework/Compilation/Directives/PropertyDeclarationDirectiveCompiler.cs, src/Tests/AssertEx.cs, src/Tests/Parser/Binding/BindingParserTests.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/PropertyDirectiveTests.cs
Now the initializer of the attribute supports half written values for the VS extension.
The validation before was way too strict and replaced invalid values with empty literal.
=> Attribute value initializer of PropertyDirective changes

src/Framework/Framework/Compilation/GlobalizeResourceVisitor.cs, src/Samples/Common/DotVVM.Samples.Common.csproj, src/Samples/Common/ViewModels/FeatureSamples/Formatting/AutoResourceInclusionMasterViewModel.cs, src/Samples/Common/ViewModels/FeatureSamples/Formatting/AutoResourceInclusionViewModel.cs, src/Samples/Common/Views/FeatureSamples/Formatting/AutoResourceInclusion.dothtml, src/Samples/Common/Views/FeatureSamples/Formatting/AutoResourceInclusionMaster.dotmaster, src/Samples/Tests/Abstractions/SamplesRouteUrls.designer.cs, src/Samples/Tests/Tests/Feature/FormattingTests.cs, src/Tests/ControlTests/testoutputs/RepeaterTests.IdGeneration.html, src/Tests/ControlTests/testoutputs/RepeaterTests.IdGeneration_CreatedAtRuntime.html
The `GlobalizeResourceVisitor` had a bug that sometimes did not correctly detect the need to add `globalize` JS resource.
When the first binding that requires `globalize` resource was detected, a boolean flag was set, but the `RequiredResource` control was being added when the visitor reached the end of a template property, or the end of a `Content` control, or the end of the entire view. 
```html
{{value: BindingWithGlobalizeRequirement}}
<dot:SomeControl>
<SomeTemplate>
</SomeTemplate>
</dot:SomeControl>
```
This was leading to a behavior when the resource was added into a random template which may not get into the page control tree eventually (e. g. when it is in `AuthenticatedView` or something like that).
I am not sure if the fix is good - I removed adding the resource in the …
=> Fixed globalize resource visitor and added the test

src/Framework/Framework/Compilation/ControlTree/DefaultControlResolver.cs, src/Framework/Framework/Compilation/DefaultControlBuilderFactory.cs, src/Framework/Framework/Configuration/Dotvvm3StateFeatureFlag.cs, src/Framework/Framework/Configuration/DotvvmConfiguration.cs, src/Framework/Framework/Configuration/DotvvmControlConfiguration.cs, src/Framework/Framework/Configuration/DotvvmFeatureFlag.cs, src/Framework/Framework/Configuration/DotvvmGlobal3StateFeatureFlag.cs, src/Framework/Framework/Configuration/DotvvmGlobalFeatureFlag.cs, src/Framework/Framework/Configuration/DotvvmMarkupConfiguration.cs, src/Framework/Framework/Configuration/DotvvmRuntimeConfiguration.cs, src/Tests/Runtime/ConfigurationValidationTests.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/BaseTypeDirectiveTests.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/MarkupDeclaredPropertyTests.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/ServiceDirectiveTests.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/ViewModelDirectiveTest.cs, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.AuxOptions.json, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.ExperimentalFeatures.json, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.Markup.json, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.RestAPI.json, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeEmptyConfig.json, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeResources.json, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeRoutes.json
Adds a feature flag which enables markup file reloading even in Production environment. We always reloaded the files before v4.2, so this at least adds the "feature" back as opt-in. Just for symmetry, it can also be disabled even in Development mode.
I also made a number of fixes to the DotvvmConfiguration freezing, it is in separate commits.
=> feature flag to reenable dothtml reloading in Production environment

src/Framework/Framework/Compilation/Validation/ControlUsageError.cs, src/Framework/Framework/Compilation/Validation/ControlUsageValidationVisitor.cs, src/Framework/Framework/Compilation/Validation/ControlUsageValidatorAttribute.cs, src/Framework/Framework/Compilation/Validation/DefaultControlUsageValidator.cs, src/Framework/Framework/Controls/Validation.cs, src/Samples/Common/ViewModels/FeatureSamples/Validation/ValidationTargetIsCollectionViewModel.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/CompilationWarningsTests.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/DefaultControlTreeResolverTests.cs
It's not possible to add compilation warnings using control usage validators. It is also possible to validate attached properties on foreign controls.
```csharp
[ControlUsageValidator(IncludeAttachedProperties = true)]
public static IEnumerable<ControlUsageError> ValidateUsage(ResolvedControl control)
{
if (control.TryGetProperty(MyAttachedProperty, out var prop))
yield return new ControlUsageError("Test warning", DiagnosticSeverity.Warning, prop.DothtmlNode);
}
```
Used to implemented check that Validation.Target is not a primitive type (see #1583)
=> control usage validators can produce warning + validate attached properties

src/Framework/Framework/Compilation/CompiledAssemblyCache.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/ImportDirectiveTests.cs
reported by MarianV at https://forum.dotvvm.com/t/import-markup-directive-fails-for-namespace-with-all-top-level-classes-being-internal/116
=> Allow internal-only namespaces in `@import` directive

src/Framework/Framework/Compilation/Parser/Dothtml/Tokenizer/DothtmlTokenizer.cs, src/Tests/Parser/Dothtml/DothtmlTokenizerDirectivesTests.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/ViewModelDirectiveTest.cs
Fixes the problem reported in https://forum.dotvvm.com/t/nowrappertag-syntax/101/2
The bug currently only affects VS extension, not framework - we don't currently report tokenizer "errors" -> no need for 4.2 patch
=> Fix tokenizer error when empty directive is used

src/Framework/Framework/Binding/IExpressionToDelegateCompiler.cs
The interpreter is broken, it causes problems in #1742. The bug is reported in dotnet, without any response yet: https://github.com/dotnet/runtime/issues/96385
=> Disable Linq.Expression preferInterpretation for bindings

src/Framework/Framework/Compilation/ControlTree/ControlTreeResolverBase.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/CompilationWarningsTests.cs
This issue occurs when a markup control is declared in a file with dothtml extension and without `@baseType` nor `@property` directives. It usually works, but causes issues with `@js` directive and we want to deprecate it in the future.
=> Warning when DotvvmView is used as control

src/Framework/Framework/Controls/AddTemplateDecorator.cs, src/Tests/ControlTests/GridViewTests.cs, src/Tests/ControlTests/testoutputs/GridViewTests.GridView_RowDecorators_AddChildren.html, src/Tests/DotVVM.Framework.Tests.csproj, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json
The decorator appends or prepends content to the decorated control.
It can be used to add additional rows to GridView
=> New AddTemplateDecorator control

src/Framework/Framework/Compilation/Binding/ExpressionBuildingVisitor.cs, src/Framework/Framework/Compilation/Inference/InfererContext.cs, src/Framework/Framework/Compilation/Inference/Inferers/LambdaInferer.cs, src/Framework/Framework/Compilation/Inference/TypeInferer.cs, src/Framework/Framework/Utils/ReflectionUtils.cs, src/Tests/Binding/BindingCompilationTests.cs, src/Tests/Runtime/ReflectionUtilsTests.cs
=> lambda inferrer: support custom delegates

src/Framework/Framework/Compilation/ControlTree/Resolved/DirectiveCompilationService.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/ViewModelDirectiveTest.cs
We now try to find the type without the assembly, if it gets resolved we let the user know that a different assembly has the correct type.
=> Better error message for wrong assembly name in directives

src/Framework/Framework/Compilation/Directives/PropertyDeclarationDirectiveCompiler.cs, src/Samples/Common/DotVVM.Samples.Common.csproj, src/Samples/Common/ViewModels/Errors/MarkupControlPropertiesSameNameWithBase.cs, src/Samples/Common/Views/Errors/MarkupControlPropertiesSameName.dotcontrol, src/Samples/Common/Views/Errors/MarkupControlPropertiesSameName.dothtml, src/Samples/Common/Views/Errors/MarkupControlPropertiesSameNameWithBase.dotcontrol, src/Samples/Common/Views/Errors/MarkupControlPropertiesSameNameWithBase.dothtml, src/Samples/Tests/Abstractions/SamplesRouteUrls.designer.cs, src/Samples/Tests/Tests/ErrorsTests.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/PropertyDirectiveTests.cs
If user defines two properties of the same name in the same markup file, there should be an error.
=> Properties with the same name defined by `@property` directive

src/Framework/Framework/Runtime/HotReloadMetadataUpdateHandler.cs, src/Framework/Framework/ViewModel/Serialization/DefaultViewModelSerializer.cs, src/Framework/Framework/ViewModel/Serialization/ViewModelTypeMetadataSerializer.cs, src/Tests/ViewModel/ViewModelTypeMetadataSerializerTests.cs
We moved validation rules to the type metadata, but we didn't remove the old validation rules from the view model. The new code also didn't respect the config.ClientSideValidation (which disables client-side validation rules).
This patchs removes the old duplicated validationRules and adds config.ClientSideValidation to the type mapper.
=> Fix config.ClientSideValidation switch, remove redundant vm.validationRules property

src/Framework/Framework/Resources/Scripts/metadata/coercer.ts, src/Framework/Framework/Resources/Scripts/tests/stateManagement.test.ts
We have to freeze the viewmodel value, not the CoerceResult object...
=> JS: Fix viewmodel freezing

src/Samples/Common/ViewModels/FeatureSamples/Validation/ClientSideRulesViewModel.cs, src/Samples/Common/Views/FeatureSamples/Validation/ClientSideRules.dothtml, src/Samples/Tests/Tests/Feature/ValidationClientSideRulesTests.cs
it doesn't work on older frameworks, so I switched it to DateTime
=> Fix UI test - DateOnly in RangeAttribute

src/Framework/Framework/Compilation/Binding/ExpressionNullPropagationVisitor.cs, src/Tests/Binding/NullPropagationTests.cs
Throw expression is not allowed for technical
reasons inside more complex expression, such as
`TimeSpan.FromHours(1 + (throw ...)).Milliseconds`. However, calling a method which throws is fine
(CIL stack doesn't need to be spilled).
this is minimal demo of the Linq.Expression issue: https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoIgBgAIiyA6AGQEs8BHZgUQQAOsAM7D2EPMIDc1OozJJ5bTj35CYo8ZL6CRYiTKrUAbgEMo9cwHN6AXnoAFc6YC2MDDCgAKDAE8BMBAAZl7AEBAANgCUUYYA9HFmFgAWEDhQwnb0AMISACbsGFpe1mg5EsIYpngYXiy0UWUAKslQEADuXgByMJ1+AcFeAIJQVjhuNQDyOBiTQQBK1VYw/GAwAkUSMWX9gSF5acARMDGxJub0qemZ9i1tnT19/nvDo+MwUzNzi3jLq+ubPDbei7QYHHBHE5nKhJEHsNzCATVLLZUwRCJeaj0bEg56DJrwmAAZSRQOYAHF3ABZdypPJeABEADE2i4ABJpDIMsp4XoAbQAuvQAN64gb7Q7HKL0AC+jSxOKGeXpuUkVRqdWYDTKVwyMUMsIQWQcbQCUD8PkJiOqZQZTQgVQiVPY6PYwhg …
=> null propagation: Fix Throw expression bug

src/Framework/Framework/Controls/ModalDialog.cs, src/Framework/Framework/Resources/Scripts/binding-handlers/all-handlers.ts, src/Framework/Framework/Resources/Scripts/binding-handlers/modal-dialog.ts, src/Samples/Common/ViewModels/FeatureSamples/ModalDialog/ModalDialogViewModel.cs, src/Samples/Common/Views/FeatureSamples/ModalDialog/ModalDialog.dothtml, src/Samples/Tests/Abstractions/SamplesRouteUrls.designer.cs, src/Samples/Tests/Tests/Feature/CompilationPageTests.cs, src/Samples/Tests/Tests/Feature/ModalDialogTests.cs, src/Samples/Tests/Tests/Feature/PostbackConcurrencyTests.cs, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json
The control closes or shows the modal based on an Open property. The modal is always shown using the .showModal() method, non-modal dialog is already accessible by binding the open attribute of dialog HTML element.
The Open property may either be a boolean or a nullable object, the dialog is shown if the value isn't false nor null.
On close event, false or null is written back into the Open property. Otherwise, we'd quickly have inconsistent viewModel whenever the user closes the dialog with ESC.
Close event is also provided for explicit event handling.
We also optionaly provide a helper for implementing "close after backdrop click" functionality. It is not supported by the dialog element natively and could not be otherwise implemented without writing custom JS.
It is enabled by setting …
=> New dot:ModalDialog control, wrapper for <dialog>

src/Framework/Testing/ControlTestHelper.cs, src/Framework/Testing/DotvvmTestHelper.cs, src/Tests/ControlTests/SimpleControlTests.cs, src/Tests/ControlTests/testoutputs/SimpleControlTests.Literal_ClientServerRendering.html, src/Tests/Runtime/DotvvmControlRenderedHtmlTests.cs
For some reason dotnet prefixes PM/AM  with a different space on different systems. This replaces `en` culture with sv culture in the two problematic and fixes some issues with passing the culture into the DotvvmTestHelper
=> Fix culture in literal tests

src/Framework/Framework/Compilation/Javascript/JavascriptTranslatableMethodCollection.cs, src/Framework/Framework/Resources/Scripts/metadata/enums.ts, src/Framework/Framework/Resources/Scripts/tests/arrayHelper.test.ts, src/Framework/Framework/Resources/Scripts/tests/stateManagement.data.ts, src/Framework/Framework/Resources/Scripts/translations/arrayHelper.ts, src/Framework/Framework/Resources/Scripts/translations/dictionaryHelper.ts, src/Framework/Framework/Resources/Scripts/translations/sortingHelper.ts, src/Framework/Framework/Resources/Scripts/utils/isNumber.ts, src/Tests/Binding/JavascriptCompilationTests.cs
=> Avoid exceptions in JS translations, add support First, Last 

src/Framework/Hosting.AspNetCore/Hosting/DotvvmHealthCheck.cs
Adding HealthChecks this way caused `IDotvvmViewCompilationService` and `DotvvmConfiguration` to resolve too early on the startup. 
Because of that, `configuration.Debug` was not set yet to `true` and even in the development mode, DotVVM was not reloading modified markup files until the application got restarted.
This PR goes to `4.2`, but we should cherry-pick it to `main` also.
=> Fixed too early initialization of view compilation service

src/Tracing/ApplicationInsights.AspNetCore/OperationNameTelemetryInitializer.cs, src/Tracing/ApplicationInsights.AspNetCore/TracingBuilderExtensions.cs, src/Tracing/ApplicationInsights.Owin/DotVVM.Tracing.ApplicationInsights.Owin.csproj, src/Tracing/ApplicationInsights.Owin/OperationNameTelemetryInitializer.cs, src/Tracing/ApplicationInsights.Owin/TracingBuilderExtensions.cs
Application insights request telemetry on DOTVVM pages is identified by request URL. If there are path variables app insights considers them as different operations and does not apply grouping. Results are hard to read with tables consisted of many rows pointing to the same route.
I was inspired by Web API where operation name ignores variables and used DOTVVM route URL as new name. I was also considering DOTVVM route name, but from my experience URL is always provided by problem reporter (imagine non IT users as reporters) but route name can be more problematic to guess at first look. 
As you can see on second screenshot "vyuctovanie" was grouped and I can see overal behavior of this page.
=> Use grouped operation name in application insights telemetry

src/Samples/Tests/Tests/Complex/SPAErrorReportingTests.cs
Test Complex_SPAErrorReporting_NavigationAndPostbacks is failing when run on MS Edge due to wrong type casting.
=> Changed type casting of ChromeDriver to ChromiumDriver - MS Edge fix

src/Framework/Framework/Resources/Scripts/state-manager.ts
observable.state now formally issues a state update in order to gain access to the current state.
It works, but it's counterintuitive when debugging and might be inefficient
=> JS state manager: clean up the hack for .state accessor

.github/setup/action.yml
This PR solves faulty .net installation on macos-latest
=> Updated actions/setup-dotnet to version 4

src/Framework/Framework/Runtime/DefaultDotvvmViewBuilder.cs, src/Framework/Testing/ControlTestHelper.cs, src/Tests/ControlTests/ServerSideStyleTests.cs, src/Tests/ControlTests/testoutputs/ServerSideStyleTests.AddResourceWithMasterPage.html
When the RequiredResource controls are added at the end of the page, the DefaultDotvvmViewBuilder would crash.
This patch specialcases the RequiredResource - since it doesn't render anything, it's safe to include anywhere
=> Fix global resource registration in master pages

src/Framework/Framework/Configuration/RestApiRegistrationHelpers.cs, src/Framework/Framework/Controls/Infrastructure/BodyResourceLinks.cs, src/Framework/Framework/ResourceManagement/InlineScriptResource.cs, src/Tests/ControlTests/testoutputs/ServerSideStyleTests.AddResourceWithMasterPage.html, src/Tests/ControlTests/testoutputs/ViewModulesServerSideTests.IncludeViewModule.html, src/Tests/ControlTests/testoutputs/ViewModulesServerSideTests.IncludeViewModuleInControl.html, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.RestAPI.json
1. type=module scripts are deferred and allow inline content, allowing us to bypass the base64 trick
2. it is necessary if someone wants to import other modules from the inline script
Unfortunatelly, we cannot make it the default when defer is requested, as type=module also enabled JS strict mode.
=> Allow type=module in InlineScriptResource

src/Framework/Framework/ResourceManagement/ResourceRepositoryExtensions.cs, src/Framework/Framework/ResourceManagement/ScriptModuleResource.cs, src/Tests/ControlTests/testoutputs/ServerSideStyleTests.AddResourceWithMasterPage.html, src/Tests/ControlTests/testoutputs/ViewModulesServerSideTests.IncludeViewModule.html, src/Tests/ControlTests/testoutputs/ViewModulesServerSideTests.IncludeViewModuleInControl.html, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json
The module scripts are always deferred and the defer attribute is actually invalid on the element
=> Remove defer attribute from `<script type=module` elements

src/Directory.Build.props, src/Framework/Framework/Compilation/ControlTree/ControlResolverBase.cs, src/Framework/Framework/Compilation/ControlTree/ControlTreeHelper.cs, src/Framework/Framework/Compilation/ControlTree/ControlTreeResolverBase.cs, src/Framework/Framework/Compilation/ControlTree/DefaultControlResolver.cs, src/Framework/Framework/Compilation/ControlTree/DefaultControlTreeResolver.cs, src/Framework/Framework/Compilation/ControlTree/IControlResolver.cs, src/Framework/Framework/Compilation/ControlTree/ResolvedTreeHelpers.cs, src/Framework/Framework/Compilation/ControlType.cs, src/Framework/Framework/Compilation/IControlType.cs, src/Framework/Framework/Compilation/Parser/Dothtml/Parser/DotHtmlCommentNode.cs, src/Framework/Framework/Compilation/Parser/Dothtml/Parser/DothtmlAttributeNode.cs, src/Framework/Framework/Compilation/Parser/Dothtml/Parser/DothtmlBindingNode.cs, src/Framework/Framework/Compilation/Parser/Dothtml/Parser/DothtmlDirectiveNode.cs, src/Framework/Framework/Compilation/Parser/Dothtml/Parser/DothtmlElementNode.cs, src/Framework/Framework/Compilation/Parser/Dothtml/Parser/DothtmlLiteralNode.cs, src/Framework/Framework/Compilation/Parser/Dothtml/Parser/DothtmlNodeHelper.cs, src/Framework/Framework/Compilation/Parser/Dothtml/Parser/DothtmlValueBindingNode.cs, src/Framework/Framework/Utils/StringSimilarity.cs, src/Samples/Tests/Tests/ErrorsTests.cs, src/Tests/ControlTests/CompositeControlTests.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/CompilationWarningsTests.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/DefaultControlTreeResolverTests.cs, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/DefaultControlTreeResolverTestsBase.cs, src/Tests/Runtime/ViewCompilationServiceTests.cs
Mainly adds warnings and more detailed errors to cover some rough edges of inner element properties.
Also includes similarity matching of control types.
=> Improve error reporting on tag names

src/Framework/Framework/Compilation/ControlTree/ControlTreeHelper.cs, src/Framework/Framework/Compilation/ControlTree/IAbstractControl.cs, src/Framework/Framework/Compilation/ControlTree/Resolved/ResolvedControl.cs, src/Framework/Framework/Controls/JsComponent.cs, src/Framework/Framework/Resources/Scripts/global-declarations.ts, src/Framework/Framework/Resources/Scripts/viewModules/viewModuleManager.ts, src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/CompilationWarningsTests.cs, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json
=> JsComponent: improve error reporting and doccomments

src/Framework/Framework/Resources/Scripts/shared-classes.ts, src/Framework/Framework/Resources/Scripts/tests/coercer.test.ts
JavaScript is happy throwing any objects, but it doesn't neccessarily show it well in the console (Only something like "Uncaught {...}"). When the class extends error, it has the correct toString conversion
Resolves #1831
=> JS: make CoerceError inherit Error, fixing console log

src/Framework/Core/Controls/Options/PagingOptions.cs
... which can very plausibly occur when rows get removed
fixes  #1835
=> Fix near page indexes crashing on invalid page number

src/Framework/Framework/Binding/DotvvmProperty.cs, src/Framework/Framework/Binding/Expressions/BindingExpression.cs, src/Framework/Framework/Compilation/ControlTree/DotvvmPropertyGroup.cs, src/Framework/Framework/Compilation/ExtensionMethodsCache.cs, src/Framework/Framework/Compilation/Styles/ResolvedControlHelper.cs, src/Framework/Framework/Runtime/Caching/SimpleLruDictionary.cs
There could have been a race condition on systems with weak memory ordering:
Another thread can read the result value before we exit the critical section. Without a strong memory ordering, the pointer to the result value might get written before the value itself. The other thread might therefore read zeroed-out memory.
=> Add memory barries to writes at the end of a lock

src/Framework/Framework/Binding/DotvvmBindingCacheHelper.cs, src/Framework/Framework/Binding/Expressions/CommandBindingExpression.cs, src/Framework/Framework/Binding/Expressions/ResourceBindingExpression.cs, src/Samples/Owin/Web.config
The `bindingCompilationService.Cache` already had methods to build `value` and `staticCommand` bindings. 
I have added methods for creating `command` bindings as well.
Does `resource` binding also make sense here?
=> Helper methods to build command binding expressions

src/Framework/Framework/Compilation/DotvvmViewCompilationService.cs
* in all cases, we now limit the paralelism using a semaphore instead of pushing 500 tasks onto the ThreadPool
* in AfterApplicationStart mode, paralelism is limited to cpu_count/2
=> view compiler: avoid blocking the ThreadPool in the AfterApplicationStart mode

src/Framework/Framework/Controls/AlternateCultureLinks.cs, src/Framework/Framework/Routing/LocalizedDotvvmRoute.cs, src/Samples/Common/Views/FeatureSamples/Localization/LocalizableRoute.dothtml, src/Samples/Tests/Tests/Feature/LocalizationTests.cs, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json
Since we have localizable routes, we are able to automatically generate the list of `<link rel=alternate>` elements, as described at https://developers.google.com/search/docs/specialty/international/localized-versions#html
=> Added AlternateCultureLinks control

src/Framework/Framework/Compilation/Javascript/Ast/JsAstHelpers.cs, src/Framework/Framework/Compilation/Javascript/JavascriptTranslatableMethodCollection.cs, src/Framework/Framework/Resources/Scripts/dotvvm-root.ts, src/Samples/Common/Views/FeatureSamples/JavascriptTranslation/DateOnlyTranslations.dothtml, src/Samples/Common/Views/FeatureSamples/JavascriptTranslation/DateTimeTranslations.dothtml, src/Samples/Common/Views/FeatureSamples/JavascriptTranslation/TimeOnlyTranslations.dothtml, src/Samples/Tests/Abstractions/SamplesRouteUrls.designer.cs, src/Samples/Tests/Tests/Feature/DateTimeTranslationTests.cs, src/Tests/Binding/JavascriptCompilationTests.cs
Support for TimeOnly, and DateOnly instance properties (Year, Month, ..., Hour, Minute, ...) in JS bindings. Similar DateTime properties are already supported.
Support for DateOnly.FromDateTime and TimeOnly.FromDateTime methods
Support for DateTime.Now, DateTime.UtcNow and DateTime.Today static properties. Before this patch, these properties expanded into the compile-time value, which could give the impression of working correctly during development.
=> js translations: TimeOnly, DateOnly and DateTime.Now

src/Framework/Framework/Resources/Scripts/dotvvm-base.ts, src/Samples/Tests/Tests/Complex/TaskListTests.cs, src/Samples/Tests/Tests/Feature/FormControlsEnabledTests.cs
* In Firefox, this worked, but also restored it on page reloads
* In Chromium, viewmodel was always reset to the initial state
This patch unifies the behavior to restore the viewmodel, but not if it is in page reload
=> Fix viewmodel restore on back/forward navigation

src/Framework/Framework/Controls/DotvvmBindableObject.cs, src/Tests/Runtime/DotvvmBindableObjectTests.cs
CopyProperty used the HasBinding method which only checks if the current control has that property set.
Apart from fixing that behavior, the new implementation limits the number of executed GetValue calls and `is IBinding` checks.
See https://forum.dotvvm.com/t/bp-gridviewtemplatecolumn-how-to-filter/230/4 for some context
=> Fix and maybe optimize CopyProperty for inherited properties

src/Framework/Framework/Hosting/DotvvmRequestContextExtensions.cs, src/Framework/Framework/Hosting/HttpRedirectService.cs, src/Framework/Framework/Resources/Scripts/postback/redirect.ts, src/Framework/Framework/Resources/Scripts/tests/eventArgs.test.ts, src/Framework/Framework/Resources/Scripts/utils/magic-navigator.ts, src/Framework/Framework/Resources/Scripts/utils/promise.ts, src/Framework/Framework/ViewModel/Serialization/DefaultViewModelSerializer.cs, src/Samples/Common/ViewModels/FeatureSamples/Redirect/RedirectPostbackConcurrencyViewModel.cs, src/Samples/Common/Views/FeatureSamples/Redirect/RedirectPostbackConcurrency.dothtml, src/Samples/Tests/Abstractions/SamplesRouteUrls.designer.cs, src/Samples/Tests/Tests/Feature/RedirectTests.cs
The page does not unload right after we  perform
a navigation, and allows the user to hit the submit button a second time. In the past, we used to disable all postbacks after a redirect, but that also blocks the page after a file is returned. There probably isn't a 100% reliable way to detect if the location change is a navigation or a file return.
With this patch, we will block the page again, but only for a limited time (5 seconds). We also only only block the postback queue, which means that only postbacks with Concurrency=Deny or Queue will be affected.
Standard file returns as provided by DotVVM are
excluded from this, but it should also work acceptably with custom file returns (some buttons will not work for 5 seconds after the file return)
=> Block postbacks for 5s after redirects

src/Framework/Framework/Controls/HtmlWriter.cs
The same warning is emitted compile-time, which makes this one redundant. Moreover, the compile-time warning includes smarter checks, and allows certain cases of uppercase attributes (in prefixed capabilities)
=> HtmlWriter: remove upper attribute warning, as it is redundant

src/Framework/Framework/Binding/DotvvmCapabilityProperty.Helpers.cs, src/Framework/Framework/Controls/CompositeControl.cs, src/Tests/Runtime/CapabilityPropertyTests.cs
Nullable ValueOrBinding, for example ValueOrBinding<int>? semantially means that the property is not set.
If the property is set to null, we would like to return null inside of the ValueOrBinding.
However, that is not possible if T is non-nullable value type, so either have to throw, or return an "outer" null. This patch changes the behavior to return null instead of failing. Users are unlikely to care about "not set" and "set to null", and throwing the exception creates unnecessary friction.
=> capabilities: avoid NRE when ValueOrBinding<int>? is set to null

src/Framework/Framework/ViewModel/Validation/ViewModelValidator.cs, src/Tests/ViewModel/ViewModelValidatorTests.cs
This resolves issue reported in #1868.
This change allows users to use complex validation attributes that need access to various services via service provider.
=> Initialized service provider in validation context.

src/Framework/Framework/Binding/DotvvmCapabilityProperty.CodeGeneration.cs, src/Framework/Framework/Binding/DotvvmCapabilityProperty.Helpers.cs, src/Tests/Runtime/CapabilityPropertyTests.cs
Seems that we forgot to use the getValue expression which was correctly created (apart from the negated nullable condition)
=> capabilities: fix Get of inherited property

src/Analyzers/Analyzers.Tests/Serializability/ViewModelSerializabilityTest.cs, src/Analyzers/Analyzers/Serializability/ViewModelSerializabilityAnalyzer.cs
We now ignore override properties if the base has JsonIgnore or Bind(None) attribute.
Technically, the patch introduces a false negative if the base is ignored and the derived isn't. However, DotVVM behavior regarding this is complex (you cannot override JsonIgnore, only Bind(None)...) and given the rarity of virtual properties, I don't want to unnecessarily complicate the analyzer.
fix #1784
I'd release this as a 4.3 patch
=> Fix DotVVM02 warning on overriden ignored property

src/Analyzers/Analyzers.Tests/ApiUsage/UnsupportedCallSiteAttributeTests.cs, src/Analyzers/Analyzers/ApiUsage/UnsupportedCallSiteAttributeAnalyzer.cs, src/Analyzers/Analyzers/DiagnosticCategory.cs, src/Analyzers/Analyzers/RoslynTreeHelper.cs
resolves #1572
I'd release this as a 4.3 patch
=> Supress DotVVM04 in Linq.Expressions

src/Framework/Framework/Compilation/Javascript/JavascriptTranslatableMethodCollection.cs, src/Tests/Binding/JavascriptCompilationTests.cs, src/Tests/Binding/StaticCommandCompilationTests.cs
This is a lighterweight alternative to #1870,
which we might not want to merge to 4.3.
This PR does only fixes the 4.3 regression,
the problem with .Select(...).ToArray()[0] is not fixed
=> Hot fix for missing ko.unwrap in Linq Last,First,ElementAt translations

src/Framework/Framework/Compilation/Javascript/ParametrizedCode.cs, src/Framework/Framework/Controls/KnockoutHelper.cs, src/Samples/Common/ViewModels/FeatureSamples/PostBack/PostBackHandlerBindingViewModel.cs, src/Samples/Common/Views/FeatureSamples/PostBack/PostBackHandlerBinding.dothtml, src/Samples/Tests/Abstractions/SamplesRouteUrls.designer.cs, src/Samples/Tests/Tests/Feature/PostBackTests.cs, src/Tests/Binding/BindingCompilationTests.cs, src/Tests/Binding/JavascriptCompilationTests.cs, src/Tests/ControlTests/PostbackHandlerTests.cs, src/Tests/ControlTests/testoutputs/PostbackHandlerTests.ButtonHandlers.html, src/Tests/ControlTests/testoutputs/ServerSideStyleTests.PostbackHandlers.html, src/Tests/Runtime/JavascriptCompilation/JsFormatterTests.cs, src/Tests/Runtime/JavascriptCompilation/JsParametrizedCodeTests.cs
Referencing `_parent` in properties of postback handlers is translated to an incorrect JS:
```
DotHTML:
<dot:SuppressPostBackHandler Suppress="{value: _parent.Enabled}" />
Translated JS:
(c,d) => $parent.Enabled
```
=> Binding translation issue in PostBackHandler properties

src/Framework/Framework/Hosting/DotvvmPresenter.cs
We check that the page is not being loaded with
JS, which should prevent attackers from scraping
all other pages if they gain access to one.
It seems that this check is incompatible with Chrome prefetching (and obviously also any JS-based prefetching). The issue seems to be that Chrome does not know
how will the prefetched document be used.
According to their documentation, it should ignore prefetch requests with non-2XX status code.
Our rejections are 403, so it should not display them to the user.
=> Add info about pre-loading to the Sec-Fetch-Dest GET check

src/Framework/Framework/Compilation/Javascript/GenericMethodCompiler.cs, src/Framework/Framework/Compilation/Javascript/JavascriptTranslatableMethodCollection.cs, src/Framework/Framework/Compilation/Javascript/JavascriptTranslator.cs, src/Framework/Framework/Compilation/Javascript/JsViewModelPropertyAdjuster.cs, src/Framework/Framework/Hosting/DotvvmPresenter.cs, src/Tests/Binding/JavascriptCompilationTests.cs, src/Tests/Binding/StaticCommandCompilationTests.cs
* FirstOrDefault, LastOrDefault, ... should behave like indexers
- return observable, if the array contains observables, which then needs to be unwrapped
- this is a regression in 4.3
* Where, Order, Take, ... return the same structure which the original array has
* Select is weird as it unwraps all observables in the array, but not recursively. That's why patch adds the JsObjectObservableMap object, which can represent this mid-state (and many other combinations)
- Indexing after Select was apparently always broken in DotVVM
=> Fix ko.observable handling in Linq translations

src/Framework/Framework/ResourceManagement/ResourceRepositoryExtensions.cs
this was most likely added by accided to both overload instead of only the following one.
fixes #1887
=> Remove Obsolete attribute from RegisterScriptModule

src/Framework/Framework/Compilation/ErrorCheckingVisitor.cs, src/Framework/Framework/Controls/Repeater.cs, src/Framework/Framework/Utils/ReferenceEqualityComparer.cs, src/Tests/Runtime/RepeaterMemoizationTest.cs
If the ConditionalWeakTable references itself, it will get leaked by .NET Core GC: https://github.com/dotnet/runtime/issues/12255
Fortunately, we don't really need the ConditinalWeakTable here:
* Repeater should generally be a short-lived object, so strong references will also be collected reasonably soon
* Between Load and PreRender, the viewmodels were pinned in the DataContext of all children and the children are in Children collection. Only after PreRender could those references be useful, but we can as well Clear the dictionary at that point.
=> Fix Repeater memoization memory leak

SECURITY.md
Update the security policy:
* deprecate 4.0 and 4.1 releases, we will no longer guarantee security fixes
* promise that users will always have at least 1 year to upgrade
* old stable versions now have support expiration date in the table
In practice we will backport fixes of critical vulnerabilities even for unsupported versions, but don't need to promise that.
=> Drop support for 4.1 and 4.0, provide clear support timelines for other versions

src/Framework/Framework/Resources/Scripts/dotvvm-root.ts, src/Framework/Framework/Resources/Scripts/postback/http.ts, src/Framework/Framework/Resources/Scripts/state-manager.ts
Most notably, this makes it possible to manually dispatch a ko.observable update using
```js
dotvvm.rootStateManager.doUpdateNow()
```
The patch should be fully backwards compatible and I'd consider releasing it as a 4.3 patch, as it will allow us to gradually migrate parts of BP and fix some of its ko.observable related bugs sooner.
=> Export the JS StateManager instance

.github/test-report/action.yml
`actions/upload-artifact@v3` will stop working in December.
=> Upgraded actions/upload-artifact from deprecated version

src/Samples/Tests/Tests/Control/TextBoxTests.cs, src/Samples/Tests/Tests/Feature/AutoUITests.cs, src/Samples/Tests/Tests/Feature/DataSetTests.cs, src/Samples/Tests/Tests/Feature/DateTimeTranslationTests.cs, src/Samples/Tests/Tests/Feature/SerializationTests.cs, src/Samples/Tests/Tests/Feature/StaticCommandTests.cs, src/Samples/Tests/Tests/Feature/ViewModelDeserializationTests.cs
ICU update probably caused different whitespace
being generated before AM/PM (no whitespace,
&nbsp, and simple space are all possible).
=> UI tests tolerate whispace changes in datetime format

src/Framework/Framework/Configuration/DotvvmExperimentalFeaturesConfiguration.cs, src/Framework/Framework/Hosting/StaticCommandExecutor.cs, src/Framework/Testing/DotvvmTestHelper.cs, src/Samples/Common/DotvvmStartup.cs
=> Enable UseDotvvmSerializationForStaticCommandArguments by default

src/Framework/Framework/Controls/DotvvmBindableObjectHelper.cs, src/Framework/Framework/Hosting/ErrorPages/DotvvmErrorPageRenderer.cs, src/Framework/Framework/Hosting/ErrorPages/ErrorFormatter.cs, src/Tests/Runtime/ErrorPageTests.cs
Before it would show `<_:Control1>` and `<_:Control2>`, now:
=> Fix control prefixes in error page "Control Hierarchy" section

src/Framework/Framework/Resources/Scripts/binding-handlers/js-component.ts, src/Framework/Framework/Resources/Scripts/binding-handlers/markup-controls.ts, src/Framework/Framework/Resources/Scripts/controls/fileUpload.ts, src/Framework/Framework/Resources/Scripts/state-manager.ts, src/Framework/Framework/Resources/Scripts/tests/markupControls.test.ts, src/Framework/Framework/Resources/Scripts/viewModules/viewModuleManager.ts, src/Samples/Common/DotvvmStartup.cs, src/Samples/Common/ViewModels/FeatureSamples/JavascriptTranslation/CommandInsideWhereViewModel.cs, src/Samples/Common/Views/FeatureSamples/JavascriptTranslation/CommandInsideWhere.dothtml, src/Samples/Common/Views/FeatureSamples/JavascriptTranslation/CommandInsideWhereControl.dotcontrol
I have a scenario when an invalid value is passed as a command argument, caused when the JS translator uses `.state` on an observable that is not DotVVM observable.
The PR contains a sample page with a button inside Repeater. The button is nested in a custom control, and its `Click` property is exposed as `Action<int>` property. Therefore, the page needs to pass lambda there, and this is where the issue probably occurs.
If the Repeater is bound to a collection in the ViewModel, it works as the objects are FakeObservableObject with the `state` property. However, when the Repeater is bound to `collection.Where(...)`, it looks like the results are just classic observables and `state` is evaluated as `undefined`, which is then passed to the command argument as `null` (and produces an …
=> Bug in JS translator when using Where and using lambda in commands

src/Framework/Framework/Compilation/Parser/Dothtml/DotvvmSyntaxConfiguration.cs, src/Framework/Framework/Compilation/Parser/Dothtml/Tokenizer/DothtmlTokenizer.cs, src/Framework/Framework/Compilation/Parser/TokenizerBase.cs, src/Framework/Framework/Configuration/DotvvmMarkupConfiguration.cs, src/Tests/Parser/Dothtml/DothtmlTokenizerElementsTests.cs, src/Tests/Parser/Dothtml/DothtmlTokenizerTestsBase.cs
In HTML, the content of <script> and <style> tags should not be parsed as HTML, the parser should simply look for the end tag.
This eliminates the need to HTML-encode all `<` operators (or even HTML inlined in string literals).
To align dothtml and HTML, the patch implements this behavior in dothtml. The change may easily break someone's code, if they already have a script element with entities like &lt;, so it is possible to configure which tags will be parsed as "raw text".
By default, it is script, style and also dot:InlineScript and dot:HtmlLiteral (as suggested in #1428). This setting is up for debate.
resolves #1445
=> Special-case parsing of <script> and <style> elements, similarly to HTML

src/Samples/Tests/Tests/Control/GridViewTests.cs, src/Samples/Tests/Tests/Control/HierarchyRepeaterTests.cs
See https://github.com/SeleniumHQ/selenium/issues/15358 https://issuetracker.google.com/issues/394760806
=> Add workaround for Selenium Maximize() not working on Linux Chromium

src/Framework/Framework/Compilation/Binding/GeneralBindingPropertyResolvers.cs, src/Framework/Framework/Compilation/Binding/InitOnlyPropertyCheckingVisitor.cs, src/Tests/Binding/BindingCompilationTests.cs, src/Tests/Binding/StaticCommandCompilationTests.cs
See https://forum.dotvvm.com/t/intended-behaviour-coherence-of-init-only-properties-between-c-code-and-dotvvm-front-end/295 for some context. In short, it is OK to allow this in JS code (IMHO we want to simplify staticCommands with records, given that we don't support `with` / `new` yet it's necessary).
However, it can be quite dangerous on server, where this might allow you to accidentally mutate a shared singleton object (imagine defining `public static readonly MyRecord Default = new() { ... }` and then using it to initialize a view model property)
=> Disallow asigning to init-only properties in bindings

src/Framework/Framework/Controls/Timer.cs, src/Framework/Framework/Resources/Scripts/binding-handlers/all-handlers.ts, src/Framework/Framework/Resources/Scripts/binding-handlers/timer.ts, src/Samples/Common/ViewModels/ControlSamples/Timer/LongCommandViewModel.cs, src/Samples/Common/ViewModels/ControlSamples/Timer/RemovalViewModel.cs, src/Samples/Common/ViewModels/ControlSamples/Timer/TimerViewModel.cs, src/Samples/Common/Views/ControlSamples/Timer/LongCommand.dothtml, src/Samples/Common/Views/ControlSamples/Timer/Removal.dothtml, src/Samples/Common/Views/ControlSamples/Timer/Timer.dothtml, src/Samples/Tests/Abstractions/SamplesRouteUrls.designer.cs, src/Samples/Tests/Tests/Control/TimerTests.cs, src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json
Usage:
```
<dot:Timer Interval="1000" Command="{command: Value1 = Value1 + 1}" Enabled="{value: Enabled1}" />
```
=> Timer control added

src/Framework/Framework/Resources/Scripts/binding-handlers/markup-controls.ts, src/Framework/Framework/Resources/Scripts/tests/markupControls.test.ts, src/Framework/Framework/Resources/Scripts/utils/evaluator.ts
who'd think most of BP is broken without this obscurity...
=> Maybe support observableArray in markup control properties

src/Framework/Framework/Compilation/DotHtmlFileInfo.cs, src/Framework/Framework/Compilation/DotvvmViewCompilationService.cs, src/Framework/Framework/Compilation/Static/StaticViewCompiler.cs, src/Framework/Framework/Configuration/FreezableDictionary.cs, src/Framework/Framework/Controls/RouteLinkHelpers.cs, src/Framework/Framework/Hosting/AggregateMarkupFileLoader.cs, src/Framework/Framework/Hosting/DefaultMarkupFileLoader.cs, src/Framework/Framework/Hosting/EmbeddedMarkupFileLoader.cs, src/Framework/Framework/ResourceManagement/LocalResourceUrlManager.cs, src/Framework/Framework/Routing/DefaultRouteStrategy.cs, src/Framework/Framework/Routing/DotvvmRoute.cs, src/Framework/Framework/Routing/DotvvmRouteParser.cs, src/Framework/Framework/Routing/DotvvmRouteTable.cs, src/Framework/Framework/Routing/LocalizedDotvvmRoute.cs, src/Framework/Framework/Routing/RouteBase.cs, src/Framework/Framework/Routing/RouteHelper.cs, src/Framework/Framework/Routing/RouteTableGroup.cs, src/Framework/Framework/Routing/RouteTableJsonConverter.cs, src/Framework/Testing/ControlTestHelper.cs, src/Framework/Testing/FakeMarkupFileLoader.cs, src/Tests/Routing/DotvvmRouteTests.cs, src/Tests/Routing/RouteSerializationTests.cs, src/Tests/Routing/RouteTableGroupTests.cs, src/Tests/Runtime/DotvvmControlRenderedHtmlTests.cs
We had several issues in route groups when used in combination with URL and route redirections:
```csharp
config.RouteTable.AddGroup(
"CmsAdmin", urlPrefix, "embedded://Shared.Infrastructure.Cms.Admin", routes =>
{
routes.AddRouteRedirection(
"Index", 
"", // this URL was not concatenated with the group prefix, 
"CmsAdmin_Articles");
routes.Add("Preview", 
"articles/preview", 
"some_valid_virtual_path", // this cannot be null and requires a valid embedded resource path even though it is not used 
presenterFactory: _ => new PreviewPopupPresenter());
});
```
=> Refactoring & cleanup in routes & route groups + bug fixes

src/Framework/Framework/Hosting/Middlewares/DotvvmRoutingMiddleware.cs, src/Framework/Framework/Routing/DotvvmRouteTable.cs, src/Framework/Framework/Routing/LocalizedDotvvmRoute.cs, src/Framework/Framework/Routing/RouteTableGroup.cs, src/Framework/Hosting.AspNetCore/DotVVM.Framework.Hosting.AspNetCore.csproj, src/Framework/Hosting.AspNetCore/Localization/DotvvmRoutingRequestCultureProvider.cs, src/Tests/Routing/RouteTableGroupTests.cs
When using the localizable routes feature, I discovered two unpleasant things:
* Route groups did not have support localized route fragments.
* The `IsPartialMatch` method did not return which culture was matched. I needed that when using ASP.NET Core's Request Localization feature to be able to determine the culture from the URL.
=> Enhancements of localizable routes

src/Framework/Core/Controls/GridViewDataSetExtensions.cs, src/Framework/Core/Controls/GridViewDataSetResult.cs, src/Framework/Core/Controls/Options/IPagingOptionsLoadingPostProcessor.cs, src/Framework/Core/Controls/Options/PagingImplementation.cs, src/Framework/Core/Controls/Options/PagingOptions.cs, src/Samples/Common/ViewModels/ControlSamples/GridView/GridViewStaticCommandViewModel.cs, src/Tests/DotVVM.Framework.Tests.csproj, src/Tests/ViewModel/EFCoreGridViewDataSetTests.cs
It is primarily based on the IAsyncEnumerable interface, but requires some hacks to get access to the CountAsync method.
=> Add async LoadFromQueryable

src/Framework/Framework/Compilation/Binding/BindingExpressionBuilder.cs
This was causing the instability of extension method compilation, which we tried to debug in #1780
=> Fix race condition in BindingExpressionBuilder

src/Framework/Framework/Compilation/Javascript/ParametrizedCode.cs, src/Framework/Framework/Controls/KnockoutHelper.cs, src/Framework/Framework/Controls/PostbackScriptOptions.cs, src/Tests/Binding/JavascriptCompilationTests.cs, src/Tests/Binding/KnockoutHelperTests.cs
Resolves #1908
We now store all options as nullable, and the default value is determined by the KnockoutHelper function called. It is necessary, as GenerateClientPostbackLambda has a different set of default values than GenerateClientPostbackLambda, and GenerateClientPostbackScript.
Notable exception is the ReturnValue, which already is nullable and null means that `null` should be returned. It's thus technically difficult to make this property "optional", and this issue isn't really relevant for this property anyway
=> Fix default values of PostbackScriptOptions

src/Framework/Framework/Controls/SpaContentPlaceHolder.cs, src/Framework/Framework/Resources/Scripts/postback/updater.ts
Should improve "visual" loads times, and SEO.
Hiding the page is currently unnecessary
it was added back in 2015 (9c11159), because we used to rely on the URL path fragment (`#/something`), which could be different from the page which was currently being loaded.
=> Do not hide SPA page while JS is loading

src/Framework/Framework/Hosting/DotvvmRequestContextExtensions.cs, src/Framework/Framework/Hosting/HostingConstants.cs, src/Framework/Framework/Hosting/Middlewares/DotvvmReturnedFileMiddleware.cs, src/Framework/Framework/Hosting/Middlewares/DotvvmRoutingMiddleware.cs, src/Framework/Framework/Resources/Scripts/postback/http.ts, src/Framework/Framework/Resources/Scripts/spa/navigation.ts, src/Framework/Framework/Resources/Scripts/tests/eventArgs.test.ts, src/Samples/Common/ViewModels/FeatureSamples/Redirect/RedirectPostbackConcurrencyViewModel.cs, src/Tests/ControlTests/testoutputs/ServerSideStyleTests.AddResourceWithMasterPage.html, src/Tests/ControlTests/testoutputs/SimpleControlTests.FileUpload.html, src/Tests/ControlTests/testoutputs/ViewModulesServerSideTests.IncludeViewModule.html, src/Tests/ControlTests/testoutputs/ViewModulesServerSideTests.IncludeViewModuleInControl.html, src/Tracing/ApplicationInsights/RequestTelemetryFilter.cs, src/Tracing/MiniProfiler.AspNetCore/MiniProfilerBuilderExtensions.cs, src/Tracing/MiniProfiler.Owin/MiniProfilerBuilderExtensions.cs
resolves #1539 (unless I forgot about some requests we do)
=> v5 cleanup: Move HTTP requests to resources, file upload/return under /_dotvvm/

src/Framework/Core/Runtime/IDebugHtmlFormattableObject.cs, src/Framework/Framework/Binding/BindingProperties.cs, src/Framework/Framework/Compilation/BindingParserOptions.cs, src/Framework/Framework/Controls/DotvvmControl.cs, src/Framework/Framework/Controls/DotvvmControlException.cs, src/Framework/Framework/Hosting/ErrorPages/CookiesSection.cs, src/Framework/Framework/Hosting/ErrorPages/DictionarySection.cs, src/Framework/Framework/Hosting/ErrorPages/DotvvmMarkupErrorSection.cs, src/Framework/Framework/Hosting/ErrorPages/ErrorFormatter.cs, src/Framework/Framework/Hosting/ErrorPages/ErrorPageTemplate.cs, src/Framework/Framework/Hosting/ErrorPages/ExceptionModel.cs, src/Framework/Framework/Hosting/ErrorPages/ExceptionSectionFormatter.cs, src/Framework/Framework/Hosting/ErrorPages/IErrorWriter.cs, src/Framework/Framework/Resources/Styles/DotVVM.Internal.css, src/Framework/Framework/Runtime/IDotvvmException.cs, src/Framework/Framework/Utils/HtmlFormattingUtils.cs, src/Framework/Framework/ViewModel/Serialization/DefaultViewModelSerializer.cs, src/Framework/Hosting.AspNetCore/Hosting/DotvvmHttpContext.cs, src/Samples/Tests/Tests/Control/ButtonTests.cs, src/Samples/Tests/Tests/Control/ComboBoxTests.cs, src/Samples/Tests/Tests/ErrorsTests.cs, src/Samples/Tests/Tests/Feature/HotReloadTests.cs, src/Samples/Tests/Tests/Feature/ViewModelProtectionTests.cs
* Any exception can implement the interface, the returned string will be used instead of its message
* Some other object such as binding properties also may implement the interface. The return value is used instead of ToString
While adjusting the error page I also made slight changes it appearance:
This is how the Binding tab looks like after changes:
=> Add IDebugHtmlFormattableObject for error page formatting

src/Framework/Framework/Configuration/DotvvmRuntimeConfiguration.cs, src/Framework/Framework/Hosting/Middlewares/DotvvmLocalResourceMiddleware.cs, src/Framework/Framework/ResourceManagement/ClientGlobalize/JQueryGlobalizeResourceLocation.cs, src/Framework/Framework/ResourceManagement/DefaultResourceHashService.cs, src/Framework/Framework/ResourceManagement/ILinkResource.cs, src/Framework/Framework/ResourceManagement/LinkResourceBase.cs, src/Framework/Framework/ResourceManagement/LocalResourceUrlManager.cs, src/Framework/Testing/ControlTestHelper.cs, src/Framework/Testing/DotvvmTestHelper.cs, src/Tests/ControlTests/testoutputs/ServerSideStyleTests.AddResourceWithMasterPage.html, src/Tests/ControlTests/testoutputs/ViewModulesServerSideTests.IncludeViewModule.html, src/Tests/ControlTests/testoutputs/ViewModulesServerSideTests.IncludeViewModuleInControl.html, src/Tracing/ApplicationInsights/RequestTelemetryFilter.cs
* this is more backward compatible with v4, as relative references like `../../something`  will keep working
* version hash is moved to query string, which is more conventional (and does not cause compatibility issues for a long time already)
=> Change dotvvm resource URL to /_dotvvm/resource-{name}/{name}
