src/Redwood.Framework/Configuration/RedwoodConfiguration.cs
src/Redwood.Framework/Controls/Panel.cs
src/Redwood.Framework/Controls/SelectHtmlControlBase.cs
src/Redwood.Framework/Controls/TextBox.cs
src/Redwood.Framework/KnockoutHelper.cs
src/Redwood.Framework/Redwood.Framework.csproj

Fixing Configuration Debug settings
Fixing SelectHtmlControlBase Server rendering.

Fixing Configuration Debug settings, Fixing SelectHtmlControlBase Server rendering.

---

src/DotVVM.Framework/Hosting/ErrorPages/ErrorPageTemplate.cs
src/DotVVM.Framework/Hosting/ErrorPages/ExceptionSectionFormatter.cs

I did small changes to error page font sizes. IMHO they brings better readability and shows more text on page without scrolling

Error page font size changes

---

src/DotVVM.Framework/Controls/GridViewTextColumn.cs

Issue https://github.com/riganti/dotvvm/issues/368
I chose the name `Changed` for the property to be consistent with other properties with similar functionality.

Added Changed property to GridViewTextColumn

---

src/DotVVM.Framework/Configuration/DotvvmConfiguration.cs
src/DotVVM.Framework/Resources/Scripts/DotVVM.Debug.js

remove jQuery from Debug mode

---

src/DotVVM.Core/Controls/GridViewDataSet.cs
src/DotVVM.Core/Controls/IBaseGridViewDataSet.cs
src/DotVVM.Core/Controls/IPageableGridViewDataSet.cs
src/DotVVM.Framework/Binding/Expressions/CommandBindingExpression.cs
src/DotVVM.Framework/Controls/DataPager.cs
src/DotVVM.Framework/Controls/GridView.cs
src/DotVVM.Framework/Controls/GridViewColumn.cs

Grid view data set: All synchronous methods are now obsolete

---

src/DotVVM.Framework.Tests.Common/Binding/JavascriptCompilationTests.cs
src/DotVVM.Framework.Tests.Common/Runtime/JavascriptCompilation/JsFormatterTests.cs
src/DotVVM.Framework.Tests.Common/Runtime/JavascriptCompilation/JsParensInsersionTests.cs
src/DotVVM.Framework/Binding/Expressions/CommandBindingExpression.cs
src/DotVVM.Framework/Compilation/Binding/StaticCommandBindingCompiler.cs
src/DotVVM.Framework/Compilation/Javascript/Ast/JsSymbolicParameter.cs
src/DotVVM.Framework/Compilation/Javascript/JavascriptCompilationHelper.cs
src/DotVVM.Framework/Compilation/Javascript/JavascriptTranslationVisitor.cs
src/DotVVM.Framework/Compilation/Javascript/JavascriptTranslator.cs
src/DotVVM.Framework/Compilation/Javascript/JsFormattingVisitor.cs
src/DotVVM.Framework/Compilation/Javascript/JsTemporaryVariableResolver.cs
src/DotVVM.Framework/Compilation/Javascript/ParametrizedCode.cs
src/DotVVM.Framework/Controls/KnockoutHelper.cs
src/DotVVM.Framework/Utils/ReflectionUtils.cs
src/DotVVM.Samples.Common/ViewModels/FeatureSamples/Validation/ClientSideValidationDisablingViewModel.cs

It allows data-context shifting for command/staticCommand bindings.
It should also improve performance of value binding rendering a bit.

Added default values to ParametrizedCode's parameters.

---

README.md

The point is to explain what does DotVVM actually do for you and how it's different from MVC/Django/WebForms/Rails/React/WhateverYouLike

Added How it works section to README

---

src/DotVVM.Framework/Controls/DataPager.cs

Added ways how to modify individual parts (buttons) of datapager

Refactored DataPager - added extensibility points

---

src/DotVVM.Framework/Controls/Repeater.cs
src/DotVVM.Samples.Common/DotVVM.Samples.Common.csproj
src/DotVVM.Samples.Common/ViewModels/ControlSamples/Repeater/RequiredResourceViewModel.cs
src/DotVVM.Samples.Common/Views/ControlSamples/Repeater/RequiredResource.dothtml
src/DotVVM.Samples.Tests.New/Control/RepeaterTests.cs
src/DotVVM.Testing.Abstractions/SamplesRouteUrls.designer.cs

Fixes RequiredResources not working in Repeater when DataSource is empty

---

src/DotVVM.Framework/Controls/Infrastructure/HeadResourceLinks.cs
src/DotVVM.Framework/ResourceManagement/ILinkResource.cs
src/DotVVM.Framework/ResourceManagement/IPreloadResource.cs
src/DotVVM.Framework/ResourceManagement/ResourcesRenderer.cs
src/DotVVM.Framework/ResourceManagement/ScriptResource.cs

Added ability to preload link resource
* I added preloading only to scripts, because stylesheets are loaded immediately before preload links
* I'm not convinced that I have chosen the right approach to add preload links
#528

Added ability to preload link resource

---

src/DotVVM.Framework.Hosting.Owin/AppBuilderExtensions.cs
src/DotVVM.Framework/Configuration/DotvvmConfiguration.cs
src/DotVVM.Framework/Configuration/ServiceLocator.cs
src/DotVVM.Framework/Runtime/DefaultStaticCommandServiceLoader.cs

Solution based on a conversation in #628

Added factory method for IServiceProvider on OWIN

---

src/DotVVM.Framework/Controls/GridView.cs

Changed methods which are used to construct control to be protected virtual instead of private.

GridView - extensibility

---

src/DotVVM.Framework.Tests.Common/Routing/UrlHelperTests.cs
src/DotVVM.Framework/Hosting/DotvvmRequestContextExtensions.cs
src/DotVVM.Framework/Routing/UrlHelper.cs

The implementation of `IsLocalUrl` is copied from ASP.NET Core MVC.

Added RedirectToLocalUrl

---

src/DotVVM.Framework/Controls/MultiSelect.cs
src/DotVVM.Samples.Common/DotVVM.Samples.Common.csproj
src/DotVVM.Samples.Common/ViewModels/ControlSamples/MultiSelect/MultiSelectViewModel.cs
src/DotVVM.Samples.Common/Views/ControlSamples/MultiSelect/binded.dothtml
src/DotVVM.Samples.Common/Views/ControlSamples/MultiSelect/hardcoded.dothtml
src/DotVVM.Samples.Tests/Control/MultiSelectTests.cs
src/DotVVM.Testing.Abstractions/SamplesRouteUrls.designer.cs

Add multiselect control

---

src/DotVVM.Framework.Tests.Common/ViewModel/SerializerTests.cs
src/DotVVM.Framework/Configuration/RestApiRegistrationHelpers.cs
src/DotVVM.Framework/Utils/ReflectionUtils.cs
src/DotVVM.Framework/ViewModel/Serialization/ViewModelJsonConverter.cs
src/DotVVM.Framework/ViewModel/Serialization/ViewModelSerializationMapper.cs

Also, I have deduplicated the code that checks if we can serialize a value using our converter.
resolves #829

Serialization: KeyValuePair and ValueTuple are handled by Newtonsoft.Json

---

src/DotVVM.Framework.Hosting.AspNetCore/Hosting/RequestCancellationTokenProvider.cs
src/DotVVM.Framework.Hosting.AspNetCore/ServiceCollectionExtensions.cs
src/DotVVM.Framework.Hosting.Owin/AppBuilderExtensions.cs
src/DotVVM.Framework.Hosting.Owin/Hosting/RequestCancellationTokenProvider.cs
src/DotVVM.Framework/Hosting/DotvvmRequestContextExtensions.cs
src/DotVVM.Framework/Hosting/IRequestCancellationTokenProvider.cs

This PR adds `CancellationToken` to `IDotvvmRequestContextExtensions`. Resolves #810

Added CancellationToken to IDotvvmRequestContextExtensions

---

src/DotVVM.Framework.Api.Swashbuckle.AspNetCore/SwashbuckleExtensions.cs
src/DotVVM.Samples.BasicSamples.Api.AspNetCore/Startup.cs
src/DotVVM.Samples.BasicSamples.Api.AspNetCoreLatest/Startup.cs

This PR makes it a little easier for users to configure swashbuckle

Simplified swashbuckle configuration

---

src/DotVVM.Framework/Resources/Scripts/dotvvm-root.ts
src/DotVVM.Framework/Resources/Scripts/events.ts
src/DotVVM.Framework/Resources/Scripts/global-declarations.ts
src/DotVVM.Framework/Resources/Scripts/tests/eventArgs.test.ts

Adds `initCompleted` event to `dotvvm.events` which is triggered after `init` function is finished and bindings have been applied.

Add initCompleted JavaScript event

---

src/DotVVM.Framework.Tests.Common/Binding/GenericPropertyResolverTests.cs
src/DotVVM.Framework/Binding/BindingProperties.cs
src/DotVVM.Framework/Compilation/Binding/GeneralBindingPropertyResolvers.cs

Added ExpectedAsStringBindingExpression that adds ExpectedTypeBindingProperty to properties of IValueBinding.

Added ExpectedAsStringBindingExpression

---

src/DotVVM.Framework/Hosting/DotvvmRequestContextExtensions.cs
src/DotVVM.Framework/Routing/DotvvmRouteTable.cs
src/DotVVM.Samples.Common/DotvvmStartup.cs
src/DotVVM.Samples.Tests/Feature/RedirectTests.cs

I tried to use this new route redirection feature and found out that it doesn't have a way to work with query string parameters so I added this extensibility point.

Added urlSuffixProvider to AddRouteRedirection

---

src/DotVVM.Framework/ResourceManagement/LinkResourceBase.cs
src/DotVVM.Framework/ResourceManagement/ScriptResource.cs

Fixes usage of `defer` attribute on a fallback script.

Fixed loading of the fallback script when a defer attribute is used

---

src/DotVVM.Framework/Resources/Scripts/Polyfills/utils.js
src/DotVVM.Framework/Resources/Scripts/spa/spa.ts
src/DotVVM.Framework/Resources/Scripts/state-manager.ts
src/DotVVM.Framework/package.json

Cherry-picked IE11-related fixes from PR #965

Added polyfill for Symbol and fixed other IE11-related issues

---

src/DotVVM.Framework/Resources/Scripts/dotvvm-base.ts

Previously this caused error like "v is undefined", now it says that "DotVVM is not initialized".

Better error message when state is used before init

---

src/DotVVM.Framework.Tests.Common/Binding/ExpressionHelperTests.cs
src/DotVVM.Framework/Compilation/Binding/MemberExpressionFactory.cs

Resolves #942. This is a continuation of #937.

Fix generics resolving in method overloads search (2)

---

src/DotVVM.Framework/Hosting/DotvvmPresenter.cs

Ensure OnCommandExecutedAsync gets called for each command

---

src/DotVVM.Samples.Common/DotVVM.Samples.Common.csproj
src/DotVVM.Samples.Common/ViewModels/FeatureSamples/CommandActionFilter/CommandActionFilterViewModel.cs
src/DotVVM.Samples.Common/Views/FeatureSamples/CommandActionFilter/CommandActionFilter.dothtml
src/DotVVM.Samples.Tests/Feature/CommandActionFilterTests.cs
src/DotVVM.Testing.Abstractions/SamplesRouteUrls.designer.cs

This PR is a continuation of #1000. Added test that ensures both callbacks are received.

Added test for OnCommandExecutingAsync and OnCommandExecutedAsync

---

src/DotVVM.Framework/Hosting/DotvvmPresenter.cs
src/DotVVM.Samples.Common/DotVVM.Samples.Common.csproj
src/DotVVM.Samples.Common/ViewModels/FeatureSamples/CommandActionFilter/CommandActionFilterViewModel.cs
src/DotVVM.Samples.Common/Views/FeatureSamples/CommandActionFilter/CommandActionFilter.dothtml
src/DotVVM.Samples.Tests/Feature/CommandActionFilterTests.cs
src/DotVVM.Testing.Abstractions/SamplesRouteUrls.designer.cs

This PR backports a fix for issue #999 to version 3.0

Backported fix for OnCommandExecutedAsync to 3.0

---

src/DotVVM.Framework.Tests.Common/Runtime/DotvvmControlRenderedHtmlTests.cs
src/DotVVM.Framework/Controls/RouteLink.cs

Fixed RouteLinks with targets in SPA

---

src/DotVVM.Framework/Compilation/DefaultControlBuilderFactory.cs

I don't really know how to replicate it, @quigamdev could you please try if this fixes the issue?

Fix control compiler deadlock

---

src/DotVVM.Framework/Compilation/Javascript/JavascriptTranslatableMethodCollection.cs

.NET 6 added several new overloads to existing LINQ methods which break the registration of JS translators. 
I've added parameters filter overload which makes matching the methods easier.
This is working with .NET 6 Preview 4.

Updated JS translation registration for LINQ methods to work with .NET 6

---

src/DotVVM.Framework/Configuration/DotvvmConfiguration.cs
src/DotVVM.Framework/Controls/SpaContentPlaceHolder.cs

Updated obsolete comments in SpaContentPlaceHolder

---

src/DotVVM.Samples.Common/Views/FeatureSamples/JavascriptTranslation/DictionaryIndexerTranslation.dothtml
src/DotVVM.Samples.Tests/Feature/DictionaryTranslationTests.cs

I have rewritten the tests to use RIGANTI Selenium AssertUI class

Fixed DictionaryTranslationTests

---

src/DotVVM.Framework/Resources/Scripts/binding-handlers/textbox-text.ts
src/DotVVM.Samples.Common/ViewModels/ControlSamples/TextBox/TextBoxTypesViewModel.cs
src/DotVVM.Samples.Common/Views/ControlSamples/TextBox/TextBox_Types.dothtml
src/DotVVM.Samples.Tests/Control/TextBoxTests.cs

TextBox doesn't show numeric value of 0

---

README.md
contributing.md

DotVVM 3.1 is out :tada:
We should also do something about the file `roadmap.md` as it is becoming outdated as well.

Updated information in markdown files about new version of DotVVM

---

.azure/pipelines/ci.yml
.gitignore
ci/linux/Linux.sln
ci/linux/run.sh
ci/linux/test.ps1
ci/linux/test.sh
ci/windows/GenericPublish.pubxml
ci/windows/NuGet.config
ci/windows/Windows.sln
ci/windows/run.ps1
ci/windows/test.ps1
src/Directory.Build.props
src/DotVVM.Framework.Api.Swashbuckle.Owin.old/DotVVM.Framework.Api.Swashbuckle.Owin.csproj
src/DotVVM.Framework.Tests/Binding/BindingCompilationTests.cs
src/DotVVM.Framework/package-lock.json
src/DotVVM.Framework/package.json
src/DotVVM.Framework/yarn.lock
src/DotVVM.Samples.BasicSamples.Api.Common/DotVVM.Samples.BasicSamples.Api.Common.csproj
src/DotVVM.Samples.Common/DotVVM.Samples.Common.csproj
src/DotVVM.Samples.Common/DotvvmStartup.cs
src/DotVVM.Samples.Tests/DotVVM.Samples.Tests.csproj
src/DotVVM.Samples.Tests/Feature/ApiTests.cs
src/DotVVM.Samples.Tests/Profiles/seleniumconfig.aspnetcore.chrome.json
src/DotVVM.Samples.Tests/Profiles/seleniumconfig.aspnetcorelatest.chrome.json
src/DotVVM.Samples.Tests/Profiles/seleniumconfig.owin.chrome.json
src/EmbeddedResourceControls/EmbeddedResourceControls.csproj

Adds and modifies scripts, configs, csprojs, and other files so that our C# unit tests, Jest tests, and UI tests can run in Azure Pipelines.
(This is the complete implementation and thus closes #1046.)

Configure Azure Pipelines (YAML)

---

src/DotVVM.Framework/Resources/Scripts/global-declarations.ts
src/Tools/npm/dotvvm-types/package.json

I have changed the type of `dotvvm.state`  to any, otherwise, you have to cast the state to any or your viewmodel every time.

Changed type of viewmodel to any

---

src/DotVVM.Framework.Tests/Binding/BindingCompilationTests.cs
src/DotVVM.Framework.Tests/Binding/JavascriptCompilationTests.cs
src/DotVVM.Framework.Tests/Parser/Binding/BindingTokenizerTests.cs
src/DotVVM.Framework/Compilation/Binding/ExpressionBuildingVisitor.cs
src/DotVVM.Framework/Compilation/Binding/ExpressionNullPropagationVisitor.cs
src/DotVVM.Framework/Compilation/Javascript/JavascriptTranslatableMethodCollection.cs
src/DotVVM.Framework/Compilation/Parser/Binding/Parser/BindingParser.cs
src/DotVVM.Framework/Compilation/Parser/Binding/Tokenizer/BindingTokenizer.cs
src/DotVVM.Framework/Resources/Scripts/DotVVM.Globalize.ts
src/DotVVM.Framework/Resources/Scripts/collections/arrayHelper.ts
src/DotVVM.Framework/Resources/Scripts/utils/stringHelper.ts
src/DotVVM.Samples.BasicSamples.Owin/package-lock.json
src/DotVVM.Samples.Common/DotVVM.Samples.Common.csproj
src/DotVVM.Samples.Common/ViewModels/FeatureSamples/JavascriptTranslation/ArrayTranslationViewModel.cs
src/DotVVM.Samples.Common/ViewModels/FeatureSamples/JavascriptTranslation/ListIndexerTranslationViewModel.cs
src/DotVVM.Samples.Common/ViewModels/FeatureSamples/StringInterpolation/StringInterpolationViewModel.cs
src/DotVVM.Samples.Common/Views/FeatureSamples/JavascriptTranslation/ArrayTranslation.dothtml
src/DotVVM.Samples.Common/Views/FeatureSamples/JavascriptTranslation/ListIndexerTranslation.dothtml
src/DotVVM.Samples.Common/Views/FeatureSamples/StringInterpolation/StringInterpolation.dothtml
src/DotVVM.Samples.Tests/Feature/ArrayTranslationTests.cs
src/DotVVM.Samples.Tests/Feature/ListTranslationTests.cs
src/DotVVM.Samples.Tests/Feature/StringInterpolationTests.cs
src/DotVVM.Testing.Abstractions/SamplesRouteUrls.designer.cs

This PR contains cherry-picked PRs to be released within a bugfix release v3.1.1:
* #1052
* #1071
* #1068

Backported bugfixes into 3.1

---

src/DotVVM.Framework/Resources/Scripts/viewModules/viewModuleManager.ts

Improved error reporting when a function from JS module fails

---

src/DotVVM.Framework.Tests/Runtime/ScriptEndingTests.cs
src/DotVVM.Framework/ResourceManagement/InlineScriptResource.cs
src/DotVVM.Framework/ResourceManagement/TemplateResource.cs

This should make it more reliable, since templates can be nested

Use template element instead of script tag

---

src/DotVVM.Samples.Tests/Feature/MarkupControlTests.cs

Fixed unstable Feature_MarkupControl_MultiControlHierarchy test

Added waitfor loop to Feature_MarkupControl_MultiControlHierarchy

---

README.md
src/Samples/Api.Common/Utilities/DateTimeConverter.cs
src/Samples/Owin/DotVVM.Samples.BasicSamples.Owin.csproj
src/Tools/CommandLine/DotVVM.CommandLine.csproj

Fixes compilation errors created in recent pull requests.

Fix recently introduced compilation errors

---

.github/workflows/main.yml
src/Framework/Framework/Binding/BindingPropertyException.cs
src/Framework/Framework/Compilation/Binding/ExpressionNullPropagationVisitor.cs
src/Framework/Framework/Hosting/ErrorPages/ErrorFormatter.cs
src/Framework/Framework/Hosting/ErrorPages/ErrorPageTemplate.cs
src/Framework/Framework/package-lock.json
src/Framework/Framework/package.json
src/Framework/Framework/tsconfig.json
src/Framework/Framework/yarn.lock
src/Tests/DotVVM.Framework.Tests.csproj

When build or unit tests fail, it's quite annying to go though the Azure CI,
so I have added a simple github action that will say that.
It also checks that we can build DotVVM.Framework without warnings

 Add github action for unit tests 

---

src/Samples/Common/Views/ComplexSamples/SPAViewModelReapplication/pageA.dothtml
src/Samples/Common/Views/ComplexSamples/SPAViewModelReapplication/pageB.dothtml
src/Samples/Tests/Tests/Complex/SPAViewModelReapplicationTests.cs

This PR tries to fix timing issue in Complex_SPAViewModelReapplication test

Added WaitForOptions to Complex_SPAViewModelReapplication

---

src/Framework/Framework/DotVVM.Framework.csproj

See the comment above the target for explanation.

Fix Framework's CompileJS BeforeTargets

---

src/Framework/Framework/Hosting/VisualStudioHelper.cs
src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json

Fixes a bug in test that currently breaks CI.

Fix ConfigurationSerializationTests

---

src/Framework/Framework/Configuration/DotvvmConfiguration.cs
src/Framework/Framework/Configuration/RestApiRegistrationHelpers.cs
src/Framework/Framework/ResourceManagement/ResourceRepositoryExtensions.cs
src/Samples/Common/CommonConfiguration.cs
src/Tests/Runtime/ResourceManagerTests.cs
src/Tracing/MiniProfiler.AspNetCore/MiniProfilerBuilderExtensions.cs

This could help a bit with the annoyance of resource registration.
I also plan to add something like our the route registration strategy, but that is for another PR.

Add helper functions for script & css resources

---

src/Framework/Framework/Controls/HtmlWriter.cs
src/Framework/Framework/Controls/IHtmlWriter.cs
src/Framework/Framework/Controls/KnockoutHelper.cs
src/Framework/Framework/Controls/PostbackScriptOptions.cs

This behavior only lead to strange behavior when used by accident.
resolves  #1026

Throw if html writer contains attribute and text/end tag is written

---

.github/workflows/main.yml
src/Framework/Hosting.AspNetCore/ApplicationBuilderExtensions.cs
src/Framework/Hosting.AspNetCore/AuthorizationExtensions.cs
src/Framework/Hosting.AspNetCore/DotVVM.Framework.Hosting.AspNetCore.csproj
src/Framework/Hosting.AspNetCore/Hosting/DotvvmEnvironmentNameProvider.cs
src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json

This mostly reduces the number of dependencies we have.

Add net5.0 target to AspNetCore hosting

---

ci/linux/run.sh
ci/windows/run.ps1
src/Samples/Common/Views/FeatureSamples/ClientExtenders/PasswordStrength.dothtml
src/Samples/Common/Views/FeatureSamples/MarkupControl/HierarchyControlPage.dothtml
src/Samples/Common/Views/FeatureSamples/ViewModelCache/ViewModelCacheMiss.dothtml
src/Samples/Common/Views/FeatureSamples/ViewModules/IncrementerInRepeater.dothtml
src/Samples/Tests/Tests/DotVVM.Samples.Tests.csproj
src/Samples/Tests/Tests/Feature/ClientExtendersTests.cs
src/Samples/Tests/Tests/Feature/JsComponentIntegrationTests.cs
src/Samples/Tests/Tests/Feature/StaticCommandTests.cs
src/Samples/Tests/Tests/Feature/ViewModuleTests.cs
src/Samples/Tests/Tests/Profiles/seleniumconfig.aspnetcore.chrome.json
src/Samples/Tests/Tests/Profiles/seleniumconfig.aspnetcore.firefox.json
src/Samples/Tests/Tests/Profiles/seleniumconfig.aspnetcorelatest.chrome.json
src/Samples/Tests/Tests/Profiles/seleniumconfig.aspnetcorelatest.firefox.json
src/Samples/Tests/Tests/Profiles/seleniumconfig.owin.chrome.json
src/Samples/Tests/Tests/Profiles/seleniumconfig.owin.firefox.json

This PR solves several things
1) .net6.0 SDK was missing on windows machines. So I have added a task to CI that installs it.
2) NPM in samples - samples requires to run rollup to build react samples - so I have added this step to CI, unfortunately, csproj integration with npm does not work as intended. 
3) fixed tests that have been failing just due to poorly written code of tests
4) Fixed tests that have been using obsolete UpdateTextOnKeyDown prop that has been removed.

Fix of main

---

src/Framework/Framework/Compilation/Binding/GeneralBindingPropertyResolvers.cs

probably, I'm not able to replicate it atm

Fix a bug in finding ElementAt method on net6

---

src/Framework/Framework/Controls/HtmlWriter.cs

data-bind should be joined with , - it's a javascript object, not javascript
statements

Fix joining of data-bind attributes

---

src/Framework/Framework/Storage/FileSystemReturnedFileStorage.cs

This will maybe fix the problem reported by @darilek at https://matrix.to/#/!WrfMXMmXzbYrOMCMCo:gitter.im/$1oz9tZTaunT_q72f2rSgWzGyuTY6nIJlEa1px8ZDu1Y?via=gitter.im&via=matrix.org

returned file storage: open files as read-only streams

---

src/Framework/Framework/Resources/Scripts/dotvvm-root.ts

BusinessPack kinda needs this, they have been hacking it a bit, but we broke it (we probably broke it in v3 and nobody noticed)

Expose in JS if dotvvm is running in debug mode

---

ci/scripts/CopyBetweenNugetFeeds.ps1
ci/scripts/publish.ps1

I noticed that we haven't included all packages in our publish scripts.

Added missing NuGet packages to publish scripts

---

src/Framework/Hosting.Owin/AppBuilderExtensions.cs

Fixes a compilation error in `AppBuilderExtensions`.

Fix AppBuilderExtensions

---

src/Framework/Framework/Controls/Literal.cs
src/Tests/ControlTests/testoutputs/SimpleControlTests.Literal_ClientServerRendering.html
src/Tests/Runtime/DotvvmControlRenderedHtmlTests.cs

For server-only mode, there is resource binding.

Literal render binding even in server mode

---

src/Framework/Framework/Binding/DotvvmCapabilityProperty.cs
src/Tests/Runtime/CapabilityPropertyTests.cs
src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json

The prefix will be accumulated in such case

Fix nested capabilities with a prefix

---

src/Framework/Framework/Controls/FileUpload.cs
src/Tests/ControlTests/SimpleControlTests.cs
src/Tests/ControlTests/testoutputs/SimpleControlTests.FileUpload.html

FileUpload: Fix non-sensical error when server-rendered

---

src/Framework/Framework/Compilation/BindingParserOptions.cs
src/Framework/Framework/Compilation/ControlTree/BindingExtensionParameter.cs
src/Framework/Framework/Compilation/ControlTree/ControlTreeResolverBase.cs
src/Framework/Testing/ControlTestHelper.cs
src/Tests/ControlTests/SimpleControlTests.cs
src/Tests/ControlTests/testoutputs/SimpleControlTests.Auth.html

Allows accessing the current user in `resource` bindinging. Allows doing bit more complex authentication conditions in the markup than simple AuthenticatedView or RoleView

Add _user extension parameter

---

ci/scripts/publish.ps1
src/Directory.Build.props

This PR changes two things about publish.ps1
- Removed `SetVersion` as it seems to be setting an obsolete / unused tag anyway
- Removed auto-commits `Nuget package version ...`

Adjusted publish script

---

src/Framework/Framework/Controls/KnockoutHelper.cs
src/Framework/Framework/Controls/ValidationSummary.cs
src/Framework/Framework/Resources/Scripts/utils/evaluator.ts
src/Framework/Framework/Resources/Scripts/validation/validation.ts
src/Tests/Runtime/DefaultViewCompilerTests.cs

This gets rid of one more eval in our codebase ;)

validation target: Use lambda function instead of a string

---

src/Framework/Framework/Resources/Scripts/tests/eventArgs.test.ts
src/Framework/Framework/Resources/Scripts/tests/postback.test.ts

I forgot to do that in  #1369, so this is a followup PR.

Fix JS unit validation tests

---

src/Tools/HotReload/Common/HotReloadMarkupFileLoader.cs

When the user saves a file in Visual Studio, it doesn't rewrite the file on disk - instead, it creates a temp file and then renames it to the original file. 
During the process, the original file is renamed to some other tmp file to be deleted later. 
This file was picked by DotVVM so Visual Studio couldn't delete it and it got sometimes stuck in the folder. This PR fixes the behavior - we ignore the files being renamed to tmp as they are not interesting to us any more, and we won't try to read them.

Hot reload ignores TMP files created by Visual Studio

---

src/Framework/Framework/Controls/HtmlGenericControl.cs
src/Tests/ControlTests/IdGeneration.cs
src/Tests/ControlTests/testoutputs/IdGeneration.AutomaticIdGeneration_IdAttributeConflict.html

Don't render id twice when both ID property and id attribute are set

---

src/Framework/Framework/ViewModel/Serialization/ViewModelSerializationMap.cs
src/Tests/ViewModel/SerializerTests.cs

In some convoluted scenarios when users had incomplete objects
in the viewmodel before deserialization,
we'd touch all property in order to copy them to
a potential new instance.
This could cause NullReferenceException, if the getters
computed something from missing nested objects.
cc @Ropack

deserializer: don't touch getters irrelevant for deserialization

---

src/Tests/Binding/NullPropagationTests.cs

...and make it a bit easier to debug

Fix a glitch in the null propagation test

---

src/Framework/Framework/Resources/Scripts/binding-handlers/textbox-text.ts

Is part of solution for #1438 
We probably should not reset value of input if element has invalid value inside. It may be half filled date/number

Resetting half written inputs

---

src/Framework/Framework/Binding/DotvvmProperty.cs
src/Tests/Runtime/DotvvmPropertyTests.cs

Disable static value in IBinding property

Disable static value in IBinding property

---

src/Tools/CommandLine/CompilerCommands.cs
src/Tools/CommandLine/MSBuild.cs

This should fix problems with incorrect escaping of arguments
fixes #1476

Use Process.ArgumentList instead of Arguments

---

src/Framework/Framework/Compilation/Directives/BaseTypeDirectiveCompiler.cs

this should avoid changing the type when only body of the markup control changes. Should mostly fix  #1474

property directive: cache the generated type

---

src/Framework/Framework/Binding/Expressions/CommandBindingExpression.cs
src/Framework/Framework/Binding/HelperNamespace/JsBindingApi.cs
src/Framework/Framework/Compilation/Binding/StaticCommandBindingCompiler.cs
src/Framework/Framework/Compilation/Javascript/JavascriptTranslator.cs
src/Framework/Framework/Configuration/RestApiRegistrationHelpers.cs
src/Framework/Framework/Controls/KnockoutHelper.cs
src/Framework/Framework/Resources/Scripts/utils/logging.ts
src/Framework/Framework/Resources/Scripts/viewModules/viewModuleManager.ts
src/Samples/Common/DotVVM.Samples.Common.csproj
src/Samples/Common/DotvvmStartup.cs
src/Samples/Common/Scripts/testViewModule.js
src/Samples/Common/Views/FeatureSamples/ViewModules/LinkModuleControl.cs
src/Samples/Common/Views/FeatureSamples/ViewModules/LinkModuleControl.dotcontrol
src/Samples/Common/Views/FeatureSamples/ViewModules/ModuleControl.dotcontrol
src/Samples/Common/Views/FeatureSamples/ViewModules/ModuleInMarkupControl.dothtml
src/Samples/Common/Views/FeatureSamples/ViewModules/ModuleInPage.dothtml
src/Samples/Tests/Tests/Feature/ViewModuleTests.cs
src/Tests/ControlTests/MarkupControlTests.cs
src/Tests/ControlTests/testoutputs/MarkupControlTests.MarkupControl_JsInvoke.html

I realized that `_js.Invoke` does not work in value bindings in markup control. It works nicely in the page. I added sample for problematic case.

Added sample for _js.Invoke in value binding.

---

src/Framework/Framework/package.json
src/Framework/Framework/yarn.lock
src/Framework/Hosting.Owin/DotVVM.Framework.Hosting.Owin.csproj
src/Samples/Api.Owin/Web.config
src/Samples/ApplicationInsights.Owin/DotVVM.Samples.ApplicationInsights.Owin.csproj
src/Samples/ApplicationInsights.Owin/Web.config
src/Samples/MiniProfiler.Owin/DotVVM.Samples.MiniProfiler.Owin.csproj
src/Samples/MiniProfiler.Owin/Web.config
src/Samples/Owin/DotVVM.Samples.BasicSamples.Owin.csproj
src/Samples/Owin/Web.config

This PR fixes current dependabot issues.

Fixed dependabot issues

---

SECURITY.md

This PR adds a `Security.md` files that describes what are our policies when it comes to issuing security patches. Furthermore, it contains a section that describes how to report vulnerabilities confidentially.

Created Security.md file

---

src/Framework/Hosting.Owin/DotVVM.Framework.Hosting.Owin.csproj
src/Samples/Api.Owin/DotVVM.Samples.BasicSamples.Api.Owin.csproj
src/Samples/ApplicationInsights.Owin/DotVVM.Samples.ApplicationInsights.Owin.csproj
src/Samples/MiniProfiler.Owin/DotVVM.Samples.MiniProfiler.Owin.csproj
src/Samples/Owin/DotVVM.Samples.BasicSamples.Owin.csproj
src/Samples/Owin/Web.config
src/Tools/HotReload/Owin/DotVVM.HotReload.Owin.csproj

This PR is a continuation for #1491

Updated all Microsoft.Owin.* packages to 4.2.2

---

README.md
contributing.md

This PR updates some old stuff in our markdown files. We should also decide on how to update roadmap.

Updated markdown files

---

src/Framework/Framework/Controls/CompositeControl.cs

Avoids wrapping any exception from GetContents into TargetInvocationExpression.

CompositeControl: avoid throwing TargetInvocationExpression

---

src/Framework/Framework/Resources/Scripts/translations/arrayHelper.ts
src/Samples/Tests/Tests/Feature/StaticCommandTests.cs

Fix Array.Contains translation

---

src/Framework/Framework/Resources/Scripts/metadata/primitiveTypes.ts
src/Framework/Framework/Resources/Scripts/tests/coercer.test.ts

This PR removes coercer's dependency on globalize library

Removed usage of globalize from coercer

---

.github/setup/action.yml
.github/test-report/action.yml
.github/unittest/action.yml
.github/workflows/main.yml
src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json

* Uploads TRXes.
* Is prepared for running tests on `net7.0` once someone upgrades the project.
**Please squash.**

Make minor changes to CI

---

src/AutoUI/Core/AutoUIContext.cs
src/AutoUI/Core/PropertyHandlers/FormEditors/MultiSelectorCheckBoxFormEditorProvider.cs
src/AutoUI/Core/PropertyHandlers/FormEditors/SelectorComboBoxFormEditorProvider.cs
src/Framework/Framework/Controls/ListBox.cs
src/Framework/Framework/Controls/ListBoxSelectionMode.cs
src/Framework/Framework/Controls/MultiSelect.cs
src/Framework/Framework/Controls/MultiSelectHtmlControlBase.cs
src/Framework/Framework/Controls/MultiSelector.cs
src/Framework/Framework/Controls/Selector.cs
src/Framework/Framework/Controls/SelectorBase.cs
src/Samples/Common/ViewModels/ControlSamples/ListBox/ListBoxViewModel.cs
src/Samples/Common/Views/ControlSamples/ListBox/ListBox.dothtml
src/Samples/Tests/Tests/Control/ComboBoxTests.cs
src/Samples/Tests/Tests/Control/ListBoxTests.cs
src/Tests/ControlTests/SimpleControlTests.cs
src/Tests/ControlTests/testoutputs/SimpleControlTests.MultiSelect.html
src/Tests/Runtime/DotvvmControlErrorsTests.cs
src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json

I migrated @Mylan719's changes (validators, tests) of ListBox to the existing MultiSelect control.

Migrate ListBox Multiple to MultiSelect

---

src/Framework/Framework/Controls/RouteLinkHelpers.cs
src/Tests/ControlTests/SimpleControlTests.cs
src/Tests/ControlTests/testoutputs/SimpleControlTests.RouteLink.html

We have to unwrap the knockout observable before calling buildUrlSuffix or concatenating strings

Fix RouteLink.UrlSuffix={value: Property}

---

src/Directory.Build.props
src/Framework/Framework/Controls/DotvvmControl.cs
src/Framework/Framework/Controls/HierarchyRepeater.cs
src/Framework/Framework/Hosting/ErrorPages/DotvvmMarkupErrorSection.cs
src/Framework/Framework/Hosting/ErrorPages/ErrorPageTemplate.cs
src/Framework/Framework/Hosting/ErrorPages/ExceptionSectionFormatter.cs
src/Framework/Framework/Resources/Styles/DotVVM.Internal.css
src/Framework/Testing/ControlTestHelper.cs
src/Samples/Common/DotVVM.Samples.Common.csproj
src/Samples/Common/DotvvmStartup.cs
src/Samples/Common/ViewModels/ControlSamples/HierarchyRepeater/BasicViewModel.cs
src/Samples/Common/Views/ControlSamples/HierarchyRepeater/Basic.dothtml
src/Samples/Common/Views/ControlSamples/HierarchyRepeater/NodeControl.dotcontrol
src/Samples/Common/Views/ControlSamples/HierarchyRepeater/WithMarkupControl.dothtml
src/Samples/Tests/Abstractions/SamplesRouteUrls.designer.cs
src/Samples/Tests/Tests/Control/ButtonTests.cs
src/Samples/Tests/Tests/Control/ComboBoxTests.cs
src/Samples/Tests/Tests/Control/HierarchyRepeaterTests.cs
src/Samples/Tests/Tests/ErrorsTests.cs
src/Tests/ControlTests/HierarchyRepeaterTests.cs
src/Tests/ControlTests/testoutputs/CompositeControlTests.WrappedHierarchyRepeaterControlWithGeneratedIds.html
src/Tests/ControlTests/testoutputs/HierarchyRepeaterTests.CommandInMarkupControl-client.html
src/Tests/ControlTests/testoutputs/HierarchyRepeaterTests.CommandInMarkupControl-server.html
src/Tests/ControlTests/testoutputs/ServerSideStyleTests.ChildrenMatching.html
src/Tests/ControlTests/testoutputs/ServerSideStyleTests.ContentInTemplates.html
src/Tests/ControlTests/testoutputs/SimpleControlTests.JsComponent.html

Resolves  #1422
I'd suggest reviewing by commits, there is number of changes, many of them to the testing infra or error handling.
UI test is missing

Fix command in markup control in HierarchyRepeater

---

src/Framework/Framework/Compilation/ControlTree/DefaultControlResolver.cs

This should help with debugging why is DotVVM trying to load some assembly, which shouldn't even be there

Include referencing assembly in "could not load" error

---

README.md

Updated READMEs with new supported DotVVM and .NET runtime versions

DotVVM 4.1 released 🎉

---

src/AutoUI/Core/AutoUIExtensions.cs
src/AutoUI/Core/Controls/AutoEditor.cs
src/AutoUI/Core/Controls/AutoForm.cs
src/AutoUI/Core/Controls/AutoFormBase.cs
src/AutoUI/Core/Controls/BootstrapForm.cs
src/Samples/Common/CommonConfiguration.cs
src/Samples/Common/DotVVM.Samples.Common.csproj
src/Samples/Common/DotvvmStartup.cs
src/Samples/Common/ViewModels/FeatureSamples/AutoUI/BootstrapFormViewModel.cs
src/Samples/Common/Views/FeatureSamples/AutoUI/BootstrapForm3.dothtml
src/Samples/Common/Views/FeatureSamples/AutoUI/BootstrapForm4.dothtml
src/Samples/Common/Views/FeatureSamples/AutoUI/BootstrapForm5.dothtml
src/Samples/Tests/Abstractions/SamplesRouteUrls.designer.cs
src/Samples/Tests/Tests/Feature/AutoUITests.cs
src/Tests/ControlTests/testoutputs/AutoUIFormTests.BootstrapFormTest.html
src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json

Fixed issues with `BootstrapForm` rendering and added tests to ensure compatibility with Bootstrap 3, 4, and 5.

Fixed various issues in BootstrapForm

---

.github/workflows/publish-internal.yml

...also fixes a bug with incorrectly composed version if the package is 'Stable'.

Add additional preview suffix to publish-internal

---

src/Framework/Framework/Resources/Scripts/global-declarations.ts
src/Framework/Framework/Resources/Scripts/metadata/coercer.ts
src/Framework/Framework/Resources/Scripts/metadata/metadataHelper.ts
src/Framework/Framework/Resources/Scripts/metadata/typeMap.ts
src/Framework/Framework/Resources/Scripts/serialization/deserialize.ts
src/Framework/Framework/Resources/Scripts/serialization/serialize.ts
src/Framework/Framework/Resources/Scripts/state-manager.ts
src/Framework/Framework/Resources/Scripts/tests/metadata.test.ts
src/Framework/Framework/Resources/Scripts/validation/validation.ts

This PR fixes a couple of bugs I found while attempting to fix some bugs in BP in connection with filters and usage of dynamics.

Improved support for dynamics in JS

---

src/Framework/Framework/Compilation/Binding/MemberExpressionFactory.cs
src/Tests/Binding/BindingCompilationTests.cs

Fix ?? expression on non-nullable value types

---

src/Framework/Framework/Resources/Scripts/metadata/coercer.ts
src/Framework/Framework/Resources/Scripts/metadata/typeMap.ts
src/Framework/Framework/Resources/Scripts/postback/postbackCore.ts
src/Framework/Framework/Resources/Scripts/serialization/deserialize.ts
src/Samples/Common/ViewModels/FeatureSamples/Serialization/ListOfObjectsViewModel.cs
src/Samples/Common/Views/FeatureSamples/Serialization/ListOfObject.dothtml
src/Samples/Tests/Abstractions/SamplesRouteUrls.designer.cs
src/Samples/Tests/Tests/Feature/SerializationTests.cs

Fix a postback commit crash when new type metadata is needed

---

src/AutoUI/Core/Controls/AutoFormBase.cs
src/Samples/Common/ViewModels/FeatureSamples/AutoUI/AutoFormViewModel.cs
src/Samples/Common/Views/FeatureSamples/AutoUI/AutoForm.dothtml
src/Samples/Tests/Tests/Feature/AutoUITests.cs

Fix NRE in `AutoFormBase` when using FieldTemplates

---

src/Framework/Framework/Controls/FileUpload.cs
src/Tests/Runtime/config-tests/ConfigurationSerializationTests.SerializeDefaultConfig.json

Add FileUpload.Capture property for input capture attribute

---

.github/workflows/publish-internal.yml
ci/scripts/Publish-NuGetPackages.ps1
src/.config/dotnet-tools.json

.NET Foundation is moving to a new code signing service for NuGet packages. This PR updates the publishing process to work with the new signing service.

Migrated to the new .NET Foundation code signing service

---

src/Framework/Framework/Binding/BindingCombinator.cs
src/Framework/Framework/Controls/Label.cs
src/Framework/Framework/Controls/SelectHtmlControlHelpers.cs
src/Tests/ControlTests/IdGeneration.cs
src/Tests/ControlTests/SimpleControlTests.cs
src/Tests/ControlTests/testoutputs/IdGeneration.AutomaticIdGeneration_Label.html
src/Tests/ControlTests/testoutputs/SimpleControlTests.ClickEvents.html
src/Tests/ControlTests/testoutputs/SimpleControlTests.ComboBox.html
src/Tests/ControlTests/testoutputs/SimpleControlTests.EmptyData.html
src/Tests/ControlTests/testoutputs/SimpleControlTests.FormControlsEnabled.html
src/Tests/ControlTests/testoutputs/SimpleControlTests.MultiSelect.html

* EmptyData now works even when IncludeInPage is set to a binding (shows if the condition holds AND the dataset is empty)
* ComboBox and MultiSelect support GridViewDataSet in the DataSource property (as all other controls do)
Few other controls are now covered with unit tests

Fix few glitches in controls

---

src/Framework/Framework/Hosting/ErrorPages/DotvvmErrorPageRenderer.cs

ASP.NET Core also logs the error, see the link in sources.

Log the exception when serving an error page

---

src/Framework/Framework/Compilation/Javascript/JsViewModelPropertyAdjuster.cs
src/Framework/Testing/BindingTestHelper.cs
src/Tests/Binding/BindingCompilationTests.cs
src/Tests/Binding/JavascriptCompilationTests.cs

When a property without a DotvvmProperty (or property group) registration
is used in value binding, it will not work, since only DotvvmProperties
are included in the with-control-properties binding.
With this patch we report error in compilation, instead of failing client-side (sometimes silently)
The first commit is a small refactoring in tests to allow me to use ExecuteBinding method in other tests than BindingCompilationTests
Resolves issue reported in https://forum.dotvvm.com/t/markup-controls-with-code-behind/50

Report error when plain property is used in markup control 

---

src/Framework/Framework/Compilation/ControlTree/ControlTreeResolverBase.cs
src/Framework/Framework/Compilation/Parser/Dothtml/Parser/DothtmlAttributeNode.cs
src/Tests/Runtime/ControlTree/DefaultControlTreeResolver/DefaultControlTreeResolverTests.cs

Fix compilation of html attributes with prefixes

---

src/Framework/Framework/Controls/DataPager.cs

We should make it possible to implement:
- `aria-label`s 
- custom classes on links
- reader only spans inside navigation and page number buttons
I implemented extensibility points

Data pager extensibility improvements

---

src/Analyzers/Analyzers.Tests/DotVVM.Analyzers.Tests.csproj
src/Analyzers/Analyzers.Tests/Serializability/ViewModelSerializabilityTest.cs
src/Samples/Tests/Tests/Control/CheckBoxTests.cs
src/Samples/Tests/Tests/Control/IncludeInPagePropertyTests.cs
src/Samples/Tests/Tests/Control/ListBoxTests.cs
src/Samples/Tests/Tests/Control/RepeaterTests.cs
src/Samples/Tests/Tests/Control/UpdateProgressTests.cs
src/Samples/Tests/Tests/DotVVM.Samples.Tests.csproj
src/Samples/Tests/Tests/Feature/StaticCommandTests.cs
src/Samples/Tests/Tests/Feature/ValidationSummaryTests.cs
src/Samples/Tests/Tests/Feature/ValidationTests.cs
src/Tests/DotVVM.Framework.Tests.csproj

This PR updates xUnit to latest version and fixed unnecessary warnings in tests

Updated xUnit to latest version and fixed test warnings

---

src/Framework/Framework/Runtime/DefaultOutputRenderer.cs

Make SetCacheHeaders protected virtual, and add no-store to the header
